/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Client52 } from '../models/client52.js';
import { ExtraParam26 } from '../models/extraParam26.js';
import { IssuerDetails } from '../models/issuerDetails.js';
import { Payment3 } from '../models/payment3.js';
import { Purchase1 } from '../models/purchase1.js';
import { StatusHistory } from '../models/statusHistory.js';
import { TransactionData40 } from '../models/transactionData40.js';

/**
 * Creates an instance of Cancel
 */
interface Cancel {
  purchaseId: string;
  client: Client52;
  updated_on: number;
  type: string;
  paymentMethod: string;
  amountUnit: string;
  errorMsg: string;
  errorCode: string;
  force_recurring: boolean;
  created_on: number;
  extraParam: ExtraParam26;
  merchantRef: string;
  purchase: Purchase1;
  payment: Payment3;
  issuer_details: IssuerDetails;
  transaction_data: TransactionData40;
  status: string;
  status_history: StatusHistory[];
  is_test: boolean;
  brand_id: string;
  send_receipt: boolean;
  is_recurring_token: boolean;
  skip_capture: boolean;
  reference_generated: string;
  issued: string;
  due: number;
  refund_upto: number;
  cc_descriptor: string;
  fraudScore: string;
  trustScore: string;
  extraFee: string;
  pix_payload?: unknown;
  payInDetails?: unknown;
  paidOn: number;
  receivedAmt: number;
  taxAmount: number;
  surcharge: number;
  surchargeType: string;
  sessionId: string;
  refund_availability: string;
  refundable_amount: number;
  success_redirect: string;
  failure_redirect: string;
  cancel_redirect: string;
  success_callback: string;
  failure_callback: string;
  platform: string;
  created_from_ip: string;
  checkout_url: string;
  direct_post_url: string;
  payoutProcess: boolean;
  additionalProperties?: Record<string, unknown>;
}

export class CancelError extends ApiError<Cancel> {}
