/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Error1
 */
interface Error1 {
  message: string;
  code: string;
  additionalProperties?: Record<string, unknown>;
}

export class Error1Error extends ApiError<Error1> {}
