/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Failure
 */
interface Failure {
  message: string;
  code: string;
  additionalProperties?: Record<string, unknown>;
}

export class FailureError extends ApiError<Failure> {}
