/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of InvalidPurchaseId
 */
interface InvalidPurchaseId {
  message: string;
  code: string;
  additionalProperties?: Record<string, unknown>;
}

export class InvalidPurchaseIdError extends ApiError<InvalidPurchaseId> {}
