/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of M401Unauthorized
 */
interface M401Unauthorized {
  message: string;
  code: string;
  additionalProperties?: Record<string, unknown>;
}

export class M401UnauthorizedError extends ApiError<M401Unauthorized> {}
