/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { All } from '../models/all.js';

/**
 * Creates an instance of PaymentMethods
 */
interface PaymentMethods {
  _all_: All[];
  additionalProperties?: Record<string, unknown>;
}

export class PaymentMethodsError extends ApiError<PaymentMethods> {}
