/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of RefundAmtIs0OrVe
 */
interface RefundAmtIs0OrVe {
  message: string;
  code: string;
  additionalProperties?: Record<string, unknown>;
}

export class RefundAmtIs0OrVeError extends ApiError<RefundAmtIs0OrVe> {}
