/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of RefundOnAnAlreadyRefundedPurchase
 */
interface RefundOnAnAlreadyRefundedPurchase {
  message: string;
  code: string;
  additionalProperties?: Record<string, unknown>;
}

export class RefundOnAnAlreadyRefundedPurchaseError extends ApiError<
  RefundOnAnAlreadyRefundedPurchase
> {}
