/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of RefundExceedsRemainingBalanceAfterAPartialRefund
 */
interface RefundExceedsRemainingBalanceAfterAPartialRefund {
  message: string;
  code: string;
  additionalProperties?: Record<string, unknown>;
}

export class RefundExceedsRemainingBalanceAfterAPartialRefundError extends ApiError<
  RefundExceedsRemainingBalanceAfterAPartialRefund
> {}
