/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Client100 } from '../models/client100.js';
import { IssuerDetails } from '../models/issuerDetails.js';
import { Mandate2 } from '../models/mandate2.js';
import { Purchase1 } from '../models/purchase1.js';
import { StatusHistory } from '../models/statusHistory.js';
import { TransactionData } from '../models/transactionData.js';

/**
 * Creates an instance of Success33
 */
interface Success33 {
  purchaseId: string;
  client: Client100;
  updated_on: number;
  type: string;
  paymentMethod: string;
  amountUnit: string;
  errorMsg: string;
  errorCode: string;
  force_recurring: boolean;
  created_on: number;
  merchantRef: string;
  purchase: Purchase1;
  issuer_details: IssuerDetails;
  transaction_data: TransactionData;
  status: string;
  status_history: StatusHistory[];
  is_test: boolean;
  brand_id: string;
  send_receipt: boolean;
  is_recurring_token: boolean;
  skip_capture: boolean;
  reference_generated: string;
  issued: string;
  due: number;
  refund_upto: number;
  cc_descriptor: string;
  fraudScore: string;
  trustScore: string;
  extraFee: string;
  totalRefunded: number;
  paidOn: number;
  receivedAmt: number;
  taxAmount: number;
  surcharge: number;
  surchargeType: string;
  sessionId: string;
  refund_availability: string;
  refundable_amount: number;
  success_redirect: string;
  failure_redirect: string;
  pending_redirect: string;
  cancel_redirect: string;
  success_callback: string;
  failure_callback: string;
  platform: string;
  created_from_ip: string;
  checkout_url: string;
  direct_post_url: string;
  payoutProcess: boolean;
  payment_type: string;
  mandate: Mandate2;
  additionalProperties?: Record<string, unknown>;
}

export class Success33Error extends ApiError<Success33> {}
