/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Data2 } from '../models/data2.js';

/**
 * Creates an instance of Success44
 */
interface Success44 {
  data: Data2;
  additionalProperties?: Record<string, unknown>;
}

export class Success44Error extends ApiError<Success44> {}
