/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Success51
 */
interface Success51 {
  refundId: string;
  purchaseId: string;
  amount: number;
  createdOn: number;
  refundOn: number;
  status: string;
  reason: string;
  currency: string;
  additionalProperties?: Record<string, unknown>;
}

export class Success51Error extends ApiError<Success51> {}
