/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Success36
 */
interface Success36 {
  status: string;
  frequency: string;
  rule: string;
  value: number;
  totalDeductedAmount: string;
  recurringMandateIds: string[];
  email: string;
  nextMandateDate: number;
  customer_id: string;
  mandate_id: string;
  mandate_max_amount: number;
  amount_variability: string;
  start_date: string;
  end_date: string;
  pause_start_date: string;
  pause_end_date: string;
  session_id: string;
  additionalProperties?: Record<string, unknown>;
}

export class Success36Error extends ApiError<Success36> {}
