/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, oneOf, Schema } from '../../schema.js';

/** This is a container type for one-of types. */
export type FeeAmount = number;

export const feeAmountSchema: Schema<FeeAmount> = oneOf([number()]);

export namespace FeeAmount {
  /**
   * Validation method to narrow down union type to number type case.
   *
   * This is Precision case.
   */
  export function isNumber(value: unknown): value is number {
    return typeof value === 'number';
  }
}
