/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  nullable,
  oneOf,
  Schema,
  string,
} from '../../schema.js';
import { Error7, error7Schema } from '../error7.js';

/** This is a container type for one-of types. */
export type Gateway1Error = Error7 | string | null;

export const gateway1ErrorSchema: Schema<Gateway1Error> = lazy(() =>
  oneOf([nullable(error7Schema), nullable(string())])
);

export namespace Gateway1Error {
  /**
   * Validation method to narrow down union type to Error7 | null type case.
   *
   * This is Error7 case.
   */
  export function isNullableError7(value: unknown): value is Error7 | null {
    return isMappedValueValidForSchema(value, nullable(error7Schema));
  }

  /**
   * Validation method to narrow down union type to string | null type case.
   *
   * This is String case.
   */
  export function isNullableString(value: unknown): value is string | null {
    return value === null || typeof value === 'string';
  }
}
