/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import { Balance, balanceSchema } from '../balance.js';
import { Balance1, balance1Schema } from '../balance1.js';

/** This is a container type for one-of types. */
export type Gateway1Balances = Balance1 | Balance;

export const gateway1BalancesSchema: Schema<Gateway1Balances> = lazy(() =>
  oneOf([balance1Schema, balanceSchema])
);

export namespace Gateway1Balances {
  /**
   * Validation method to narrow down union type to Balance1 type case.
   *
   * This is Balance1 case.
   */
  export function isBalance1(value: unknown): value is Balance1 {
    return isMappedValueValidForSchema(value, balance1Schema);
  }

  /**
   * Validation method to narrow down union type to Balance type case.
   *
   * This is Balance case.
   */
  export function isBalance(value: unknown): value is Balance {
    return isMappedValueValidForSchema(value, balanceSchema);
  }
}
