/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  PartialRefundApiRequest,
  partialRefundApiRequestSchema,
} from '../models/partialRefundApiRequest.js';
import {
  PartialRefundStatusApiRequest,
  partialRefundStatusApiRequestSchema,
} from '../models/partialRefundStatusApiRequest.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { Success51Error } from '../errors/success51Error.js';

export class Api extends BaseApi {
  /**
   * ## Refund Scenarios
   *
   * ### Partial Refund
   *
   * Purchase Amount: 10
   *
   * Refund Amount: 8
   *
   * Result:
   *
   * - Refunded Amount: 8
   *
   * - Remaining Refundable Amount: 2
   *
   * - Transaction Status: PARTIALLY_REFUNDED
   *
   *
   * Full Refund Using Partial Refund API
   *
   * Purchase Amount: 10
   *
   * Refund Amount: 10
   *
   * Result:
   *
   * - Refunded Amount: 10
   *
   * - Remaining Refundable Amount: 0
   *
   * - Transaction Status: PARTIAL REFUNDED
   *
   *
   * ### Multiple Partial Refunds
   *
   * Purchase Amount: 10
   *
   * - Refund #1: 3
   *
   * - Refund #2: 2
   *
   * - Refund #3: 5
   *
   *
   * Result:
   *
   * - Total Refunded Amount: 10
   *
   * - Remaining Refundable Amount: 0
   *
   *
   * Final Transaction Status: PARTIAL REFUNDED
   *
   * @param accept
   * @param body
   * @return Response from the API call
   */
  async partialRefundApi(
    accept: string,
    body: PartialRefundApiRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest(
      'POST',
      '/api/v1/purchases/purchaseid/refund'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      accept: [accept, string()],
      body: [body, partialRefundApiRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.header('Accept', mapped.accept);
    req.json(mapped.body);
    req.throwOn(401, Success51Error, 'Unauthorized');
    req.authenticate([]);
    return req.call(requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async partialRefundStatusApi(
    body: PartialRefundStatusApiRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/api/v1/refundStatus/purchaseid');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      body: [body, partialRefundStatusApiRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(401, Success51Error, 'Unauthorized');
    req.authenticate([]);
    return req.call(requestOptions);
  }
}
