/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CustomerRequest,
  customerRequestSchema,
} from '../models/customerRequest.js';
import {
  CustomerRequest1,
  customerRequest1Schema,
} from '../models/customerRequest1.js';
import { M202Success, m202SuccessSchema } from '../models/m202Success.js';
import { PayoutSession, payoutSessionSchema } from '../models/payoutSession.js';
import {
  PayoutSessionRequest,
  payoutSessionRequestSchema,
} from '../models/payoutSessionRequest.js';
import {
  PurchaseSessionRequest,
  purchaseSessionRequestSchema,
} from '../models/purchaseSessionRequest.js';
import { Success14, success14Schema } from '../models/success14.js';
import { Success19, success19Schema } from '../models/success19.js';
import { Success29, success29Schema } from '../models/success29.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ExistingCustomerError } from '../errors/existingCustomerError.js';
import { FailureError } from '../errors/failureError.js';
import { InvalidCustomerError } from '../errors/invalidCustomerError.js';
import { InvalidSessionError } from '../errors/invalidSessionError.js';
import { M400BadRequestError } from '../errors/m400BadRequestError.js';
import { M401UnauthorizedError } from '../errors/m401UnauthorizedError.js';

export class CashierApIsApi extends BaseApi {
  /**
   * **OVERIEW**
   *
   * The **createCustomer API** allows merchants to create a customer profile on PaySecure when a user
   * visits their website, facilitating a seamless payment experience by pre-filling the customer's
   * details, on the PaySecure Cashier. The API takes in customer information and returns a unique
   * customerID that can be passed in purchase payload, eliminating the need for customers to manually
   * enter their details during transactions.
   *
   * | Parameter | Type | **Required** | Description | Example |
   * | --- | --- | --- | --- | --- |
   * | merchantCustomerId | String | Yes | unique customer ID provided by merchant. This can be email,
   * mobile or an alphanumeric string | [rahultestcustomer@paysecure.net](https://mailto:
   * rahultestcustomer@paysecure.net) |
   * | fullName | String | Yes | Full name of the customer. | Rahul Agarwal |
   * | emailId | String | Yes | Email address of the customer. | [test@paysecure.net](https://mailto:
   * test@paysecure.net) |
   * | dateOfBirth | String | Optional | Customer's date of birth in YYYY-MM-DD format. | 1995-12-27 |
   * | phoneNo | String | Yes | Customer's phone number. Preferred with the country code | +91 797639082
   * |
   * | city | String | Optional | City of the customer. | Jaipur |
   * | stateCode | String | Yes | State code of the customer. | RJ |
   * | zipCode | String | Optional | Postal code of the customer's location. | 302018 |
   * | address | String | Optional | Full address of the customer. | House Number 53, Vaishali Nagar,
   * Jaipur |
   * | country | String | Yes | Country code (ISO 3166-1 alpha-2). | IN |
   * | custRegDate | Sting | Optional | Customer registration date on merchant site in YYYY-MM-DD format.
   * | 2023-12-27 |
   * | successTxn | String | Optional | Number of successful transactions customer has carried on
   * merchant site. | 32 |
   *
   * ### **User Flow**
   *
   * 1. **Customer visits merchant's website**: The customer selects the product or service and proceeds
   * to checkout page.
   *
   * 2. **Merchant calls the** **`createCustomer`** **API**: The merchant sends a `POST` request to the
   * Paysecure API with the customer's details.
   *
   * 3. **Customer ID generation**: Paysecure processes the request and generates a unique `customerId`
   * which is returned in the response.
   *
   * 4. **Payment Process**: The merchant uses the `customerId` for subsequent session creation, ensuring
   * the customer doesn’t need to re-enter their details for future payments.
   *
   *
   * ---
   *
   * ### **Benefits**
   *
   * - **Seamless user experience**: The customer does not have to enter their details manually for every
   * purchase.
   *
   * - **Faster Checkout**: The merchant can use the `customerId` for faster payment processing.
   *
   * - **Data Security**: Customer details are stored securely and can be reused across transactions,
   * reducing the chances of errors.
   *
   *
   * ### Implementing createCustomer on merchant site:
   *
   * The `createCustomer` can be implemented on merchant site in one of two ways, depending on merchant’s
   * integration flow:
   *
   * **At Checkout:**
   *
   * When a customer initiates the checkout process, your system should invoke the `createCustomer` API,
   * before actually starting the session.
   *
   * - **Call** **`createCustomer`**: This API call generates a unique customer ID.
   *
   * - **Use of Customer ID:** Pass the returned customer ID in Session API, when creating a payment
   * session.
   *
   *
   * **Upon Customer Login:**
   *
   * Alternatively, merchants may choose to call `createCustomer` at the time of customer login on their
   * site.
   *
   * - **Persistent Customer Profiles:** This approach can help build or maintain a persistent customer
   * profile, ensuring the customer ID is available for any subsequent payment sessions without needing
   * to call `createCustomer` again.
   *
   * - **Integration Flexibility:** This is useful for merchants who want to initialize customer data
   * early in the customer journey rather than during checkout.
   *
   *
   * The method you choose depends on your business requirements and how your system is architected.
   * Regardless of when you call it, the resulting customer ID must be passed to the `createSession` API
   * to initiate a payment session.
   *
   * @param brandId
   * @param body
   * @return Response from the API call
   */
  async customer(
    brandId: string,
    body: CustomerRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success19>> {
    const req = this.createRequest('POST', '/api/v1/customer');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      brandId: [brandId, string()],
      body: [body, customerRequestSchema],
    });
    req.header('BrandId', mapped.brandId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, FailureError, 'Bad Request');
    req.throwOn(401, ExistingCustomerError, 'Unauthorized');
    req.authenticate([]);
    return req.callAsJson(success19Schema, requestOptions);
  }

  /**
   * This endpoint makes an HTTP GET request to retrieve customer information from the Paysecure API.
   *
   * ### Request
   *
   * The request does not include any query parameters, but it uses a raw request body with the following
   * parameter "merchantCustomerId", which will be the customer id on the merchant's side.
   *
   * ### Response
   *
   * The response of this request can be documented as a JSON schema.
   *
   * @param brandId
   * @param accept
   * @return Response from the API call
   */
  async customer1(
    brandId: string,
    accept: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success19>> {
    const req = this.createRequest('GET', '/customer');
    req.baseUrl('Server 2');
    const mapped = req.prepareArgs({
      brandId: [brandId, string()],
      accept: [accept, string()],
    });
    req.header('BrandId', mapped.brandId);
    req.header('Content-Type', 'application/json');
    req.header('Accept', mapped.accept);
    req.throwOn(400, InvalidCustomerError, 'Bad Request');
    req.authenticate([]);
    return req.callAsJson(success19Schema, requestOptions);
  }

  /**
   * Whenever a customer or the merchant updates customer details on the merchant site, a PATCH request
   * must be made to synchronize these changes with Paysecure.
   *
   * This API endpoint allows you to update the customer details using an HTTP PATCH request. The request
   * should be sent to [https://api.paysecure.net/api/v1/{customerId}/patchCustomer](https://api.
   * paysecure.net/api/v1/%7BcustomerId%7D/patchCustomer).
   *
   * ### Request Body
   *
   * The request body should be in raw format and include the following parameters:
   *
   * - `fullName` (string): The full name of the customer.
   *
   * - `emailId` (string): The email address of the customer.
   *
   * - `dateOfBirth` (string): The date of birth of the customer.
   *
   * - `phoneNo` (string): The phone number of the customer.
   *
   * - `city` (string): The city of the customer.
   *
   * - `stateCode` (string): The state code of the customer.
   *
   * - `zipCode` (string): The zip code of the customer.
   *
   * - `address` (string): The address of the customer.
   *
   * - `country` (string): The country of the customer.
   *
   * - `createdOn` (string): Time when the customer was created.
   *
   * - `custRegDate` (string): Customer registration date (Non-Mandatory).
   *
   * - `successTxn` (string): Success transaction details (Non-Mandatory).
   *
   * - `lastActivity` (string): Time of the last activity.
   *
   * - `lastUpdated` (string): Time when the last patch was called.
   *
   * - `extraParam` (object): Additional parameters including `param1`, `param2`, `param3`, `param4` with
   * their respective values.
   *
   *
   * ### Response
   *
   * The response will contain the updated customer details or a success message upon successful update.
   *
   * @param brandId
   * @param accept
   * @param body
   * @param paysecureCustomerId
   * @return Response from the API call
   */
  async customer2(
    brandId: string,
    accept: string,
    body: CustomerRequest1,
    paysecureCustomerId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success19>> {
    const req = this.createRequest('PATCH');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      brandId: [brandId, string()],
      accept: [accept, string()],
      body: [body, customerRequest1Schema],
      paysecureCustomerId: [paysecureCustomerId, string()],
    });
    req.header('BrandId', mapped.brandId);
    req.header('Accept', mapped.accept);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/${mapped.paysecureCustomerId}/patchCustomer`;
    req.authenticate([]);
    return req.callAsJson(success19Schema, requestOptions);
  }

  /**
   * **OVERIEW**
   *
   * The `createSession` API is designed to initiate a payment session for a customer after their profile
   * has been created via the **createCustomer** API. The session is automatically generated at the
   * backend on the merchant’s checkout URL. This session allows the customer to continue with their
   * transaction without having to manually interact with the session URL, and ensures the session
   * remains active until the payment is completed or the session expires.
   *
   * This API improves the user experience by reducing transaction failures and enhancing the overall
   * payment process, thus reducing transaction churn rates.
   *
   * ### Mandatory Parameters
   *
   * | Parameter | Type | Description | Example |
   * | --- | --- | --- | --- |
   * | customerId | String | The unique ID of the customer (generated from createCustomer). |
   * 6731a609b6bb5a43ad66c4a6 |
   *
   * #### Show Crypto Conversion
   *
   * Additionally, there are some default extra parameters that you can pass for allowing Crypto
   * Conversion on Paysecure's cashier itself.
   *
   * |  | **Type** | **Description** | **Example** |
   * | --- | --- | --- | --- |
   * | extraParam.showCryptoConversion | String | This optional parameter allows customer to see crypto
   * value equivelant to the Fiat amount the customer is planning to pay. | Yes |
   * | extraParam.cryptoCurrencies | String | Pass here the allowed crypto tokens on the cashier, where
   * customer can see the the conversion value | \[\\"BTC\\",\\"ETH\\",\\"USDT\\",\\"XRP\\",\\"LTC\\",
   * \\"DOGE\\",\\"ETC\\",\\"BNB\\",\\"USDC\\",\\"SOL\\",\\"ADA\\",\\"BCH\\",\\"DASH\\",\\"BTG\\",
   * \\"ZEC\\",\\"DGB\\",\\"EOS\\",\\"XLM\\",\\"TRX\\",\\"QTUM\\",\\"POL\\",\\"SHIB\\",\\"LINK\\",
   * \\"DAI\\",\\"TON\\",\\"AVAX\\",\\"FDUSD\\",\\"ARB\\",\\"OP\\"\] |
   *
   * ### **Usage Flow**
   *
   * 1. **Customer completes the** **`createCustomer`** **API**: Once the customer is created via the
   * `createCustomer` API, the merchant proceeds to call the `createSession` API to generate a session.
   *
   * 2. **Merchant sends** **`createSession`** **request**: The merchant sends a `POST` request to the
   * `createSession` API with the customer’s `customerId` and the merchant’s `brandId`.
   *
   * 3. **Session created automatically on the checkout URL**: PaySecure creates the session and
   * associates it with the merchant’s checkout page. This session remains active on the backend,
   * allowing the customer to continue the payment process without interruption.
   *
   * 4. **Customer proceeds to checkout**: The customer is redirected to the checkout page as part of the
   * merchant's payment flow, where the session is automatically validated. The session remains active
   * for a set period, allowing the customer to complete the payment without needing to manually interact
   * with the session URL.
   *
   * 5. **Session Expiry**: The session expires after the set expiration time (`expiryOn`), ensuring the
   * payment process is completed within the defined window. Default is 15 mins from the creation time.
   *
   *
   * ---
   *
   * ### **Benefits**
   *
   * - **Seamless Checkout**: The session URL is automatically generated and active at the backend,
   * ensuring a smoother and uninterrupted customer experience.
   *
   * - **Reduced Transaction Failures**: By ensuring the session remains active during the payment
   * process, the chances of transaction failures due to session timeouts are minimized.
   *
   * - **Improved User Experience**: The customer does not need to click on a session URL or navigate
   * away from the page, leading to faster and more secure payment processing.
   *
   * @param brandId
   * @param accept
   * @param body
   * @return Response from the API call
   */
  async purchaseSession(
    brandId: string,
    accept: string,
    body: PurchaseSessionRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success14>> {
    const req = this.createRequest('POST', '/api/v1/createSession');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      brandId: [brandId, string()],
      accept: [accept, string()],
      body: [body, purchaseSessionRequestSchema],
    });
    req.header('BrandId', mapped.brandId);
    req.header('Accept', mapped.accept);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, InvalidSessionError, 'Bad Request');
    req.authenticate([]);
    return req.callAsJson(success14Schema, requestOptions);
  }

  /**
   * This API is used to initiate a payout session for a customer. By passing the `customerId` (generated
   * via the `createCustomer` API) and specifying `"type": "payout"`, a payout session is started.
   * A `sessionURL` is returned in the response, which can be used to redirect the customer to the payout
   * cashier. The customer can then select the payout method, pass required parameters, and the payout
   * will be processed.
   *
   * #### Parameters:
   *
   * | **Parameter** | **Type** | **Description** |
   * | --- | --- | --- |
   * | **customerId** | string | The unique ID of the customer for whom the payout session is created.
   * This ID is generated by the `createCustomer` API. |
   * | **currency** | string | The currency of the payout session (e.g., USD). |
   * | **products** | array | A list of products associated with the payout (e.g., name and price). |
   * | **totalAmount** | string | The total payout amount (optional. calculated dynamically if value is
   * not passed). |
   * | **tax_amount** | string | The tax amount to be applied (optional). |
   * | **tax_percent** | string | The tax percentage to be applied (optional). |
   * | **type** | string | Should be set to "payout" to initiate a payout session. |
   * | **success_redirect** | string | The URL where the customer will be redirected after a successful
   * payout. |
   * | **pending_redirect** | string | The URL where the customer will be redirected after a pending
   * payout. |
   * | **failure_redirect** | string | The URL where the customer will be redirected after a failed
   * payout attempt. |
   * | **success_callback** | string | The callback URL for successful payout. |
   * | **failure_callback** | string | The callback URL for failed payout. |
   * | **extraParam** | object | Contains additional parameters for the payout session. |
   * | **extraParam.showCryptoConversion** | string | Set to "yes" to display cryptocurrency conversion.
   * |
   * | **extraParam.cryptoCurrencies** | string | A list of accepted cryptocurrencies (e.g., BTC, ETH,
   * USDT). |
   *
   * #### Request Headers:
   *
   * - **BrandId**: Your unique brand ID (required).
   *
   * - **Content-Type**: application/json (required).
   *
   *
   * #### Response:
   *
   * The API will return a JSON object containing the `sessionURL` that can be used to redirect the
   * customer to the payout cashier.
   *
   * ``` json
   * {
   * "sessionUrl": "https://api.paysecure.net/payoutSession/68341ad35f895955355d5452/",
   * "brandId": "brand_id_value",
   * "customerId": "67c9983fba18400ab6cceb8f",
   * "sessionId": "68341ad35f895955355d5452",
   * "expiryOn": 1748246103,
   * "createdOn": 1748245203
   * }
   *
   * ```
   *
   * @param brandId
   * @param accept
   * @param body
   * @return Response from the API call
   */
  async payoutSession(
    brandId: string,
    accept: string,
    body: PayoutSessionRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PayoutSession>> {
    const req = this.createRequest('POST', '/api/v1/createSession');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      brandId: [brandId, string()],
      accept: [accept, string()],
      body: [body, payoutSessionRequestSchema],
    });
    req.header('BrandId', mapped.brandId);
    req.header('Content-Type', 'application/json');
    req.header('Accept', mapped.accept);
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsJson(payoutSessionSchema, requestOptions);
  }

  /**
   * This endpoint retrieves the details of a session identified by the provided session ID.
   *
   * > Note that this API only respond once the SessionURL, received in the response for session API, is
   * clicked.
   *
   * > Once the SessionURL is clicked and the user has selected a payment method and click on "Pay"
   * button, a purchase is created on our backend. If you call this API before that, you will get an
   * error.
   *
   * @return Response from the API call
   */
  async checkStatusPayin(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<M202Success>> {
    const req = this.createRequest('GET', '/api/v1/purchases/{Session ID}');
    req.baseUrl('Server 3');
    req.throwOn(400, M400BadRequestError, 'Bad Request');
    req.throwOn(401, M401UnauthorizedError, 'Unauthorized');
    req.authenticate([]);
    return req.callAsJson(m202SuccessSchema, requestOptions);
  }

  /**
   * This API tells you about all the details of a Payout, including its history
   *
   * ### Mandatory
   *
   * you need to pass the payoutId or session id in the API URL
   *
   * ### Possible Value of Status
   *
   * | **Status** | **Notes** |
   * | --- | --- |
   * | paid | Transaction Successful |
   * | payout_in_process | payout is under Processing. |
   * | error | Transaction has Failed. |
   *
   * @return Response from the API call
   */
  async checkStatusPayout(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success29>> {
    const req = this.createRequest('GET', '/api/v1/getpayout/{Session ID}');
    req.baseUrl('Server 3');
    req.authenticate([]);
    return req.callAsJson(success29Schema, requestOptions);
  }
}
