/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  BulkUpdateInvoiceNo,
  bulkUpdateInvoiceNoSchema,
} from '../models/bulkUpdateInvoiceNo.js';
import {
  BulkUpdateInvoiceNoRequest,
  bulkUpdateInvoiceNoRequestSchema,
} from '../models/bulkUpdateInvoiceNoRequest.js';
import { CreateBrandId, createBrandIdSchema } from '../models/createBrandId.js';
import {
  CreateBrandIdRequest,
  createBrandIdRequestSchema,
} from '../models/createBrandIdRequest.js';
import {
  CreateMerchantApi,
  createMerchantApiSchema,
} from '../models/createMerchantApi.js';
import {
  CreateMerchantApiRequest,
  createMerchantApiRequestSchema,
} from '../models/createMerchantApiRequest.js';
import {
  CreateMerchantApiToken,
  createMerchantApiTokenSchema,
} from '../models/createMerchantApiToken.js';
import {
  CreateMerchantApiTokenRequest,
  createMerchantApiTokenRequestSchema,
} from '../models/createMerchantApiTokenRequest.js';
import { DeleteBrandId, deleteBrandIdSchema } from '../models/deleteBrandId.js';
import {
  DeleteMerchantApi,
  deleteMerchantApiSchema,
} from '../models/deleteMerchantApi.js';
import {
  DeleteMerchantToken,
  deleteMerchantTokenSchema,
} from '../models/deleteMerchantToken.js';
import {
  GetGlobalAccounts,
  getGlobalAccountsSchema,
} from '../models/getGlobalAccounts.js';
import { GetMerchants, getMerchantsSchema } from '../models/getMerchants.js';
import {
  GetMissingInvoiceTransactions,
  getMissingInvoiceTransactionsSchema,
} from '../models/getMissingInvoiceTransactions.js';
import {
  GetSettlementData,
  getSettlementDataSchema,
} from '../models/getSettlementData.js';
import {
  GetSingleMerchant,
  getSingleMerchantSchema,
} from '../models/getSingleMerchant.js';
import {
  RequestGlobalAccount,
  requestGlobalAccountSchema,
} from '../models/requestGlobalAccount.js';
import {
  RequestGlobalAccountRequest,
  requestGlobalAccountRequestSchema,
} from '../models/requestGlobalAccountRequest.js';
import {
  UpdateMerchant,
  updateMerchantSchema,
} from '../models/updateMerchant.js';
import {
  UpdateMerchantRequest,
  updateMerchantRequestSchema,
} from '../models/updateMerchantRequest.js';
import { array, number, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class GlobalCollectionApi extends BaseApi {
  /**
   * @param page
   * @param size
   * @param requestId
   * @return Response from the API call
   */
  async getMerchants(
    page: number,
    size: number,
    requestId: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetMerchants>> {
    const req = this.createRequest(
      'GET',
      '/api/v1/external/gc/partner/merchants'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      page: [page, number()],
      size: [size, number()],
      requestId: [requestId, number()],
    });
    req.header('requestId', mapped.requestId);
    req.query('page', mapped.page);
    req.query('size', mapped.size);
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(getMerchantsSchema, requestOptions);
  }

  /**
   * @param merchantId
   * @param requestId
   * @return Response from the API call
   */
  async deleteMerchantApi(
    merchantId: number,
    requestId: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeleteMerchantApi>> {
    const req = this.createRequest(
      'DELETE',
      '/api/v1/external/gc/partner/merchant'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      merchantId: [merchantId, number()],
      requestId: [requestId, number()],
    });
    req.header('requestId', mapped.requestId);
    req.query('merchantId', mapped.merchantId);
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(deleteMerchantApiSchema, requestOptions);
  }

  /**
   * @param requestId
   * @param body
   * @return Response from the API call
   */
  async createMerchantApi(
    requestId: string,
    body: CreateMerchantApiRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateMerchantApi>> {
    const req = this.createRequest(
      'POST',
      '/api/v1/external/gc/partner/merchant'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      requestId: [requestId, string()],
      body: [body, createMerchantApiRequestSchema],
    });
    req.header('requestId', mapped.requestId);
    req.json(mapped.body);
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(createMerchantApiSchema, requestOptions);
  }

  /**
   * @param requestId
   * @param body
   * @return Response from the API call
   */
  async updateMerchant(
    requestId: number,
    body: UpdateMerchantRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UpdateMerchant>> {
    const req = this.createRequest(
      'PUT',
      '/api/v1/external/gc/partner/merchant/4230'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      requestId: [requestId, number()],
      body: [body, updateMerchantRequestSchema],
    });
    req.header('requestId', mapped.requestId);
    req.json(mapped.body);
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(updateMerchantSchema, requestOptions);
  }

  /**
   * @param requestId
   * @param body
   * @return Response from the API call
   */
  async createMerchantApiToken(
    requestId: string,
    body: CreateMerchantApiTokenRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateMerchantApiToken>> {
    const req = this.createRequest(
      'POST',
      '/api/v1/external/gc/partner/merchant/4230/api-key'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      requestId: [requestId, string()],
      body: [body, createMerchantApiTokenRequestSchema],
    });
    req.header('requestId', mapped.requestId);
    req.json(mapped.body);
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(createMerchantApiTokenSchema, requestOptions);
  }

  /**
   * @param requestId
   * @return Response from the API call
   */
  async getSingleMerchant(
    requestId: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetSingleMerchant>> {
    const req = this.createRequest(
      'GET',
      '/api/v1/external/gc/partner/merchant/4230'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ requestId: [requestId, number()] });
    req.header('requestId', mapped.requestId);
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(getSingleMerchantSchema, requestOptions);
  }

  /**
   * @param page
   * @param size
   * @param requestId
   * @return Response from the API call
   */
  async getMissingInvoiceTransactions(
    page: number,
    size: number,
    requestId: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetMissingInvoiceTransactions>> {
    const req = this.createRequest(
      'GET',
      '/api/v1/external/gc/partner/transactions/missing-invoice'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      page: [page, number()],
      size: [size, number()],
      requestId: [requestId, number()],
    });
    req.header('requestId', mapped.requestId);
    req.query('page', mapped.page);
    req.query('size', mapped.size);
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(getMissingInvoiceTransactionsSchema, requestOptions);
  }

  /**
   * @param fromDate
   * @param toDate
   * @param status
   * @param pageNo
   * @param size
   * @param requestId
   * @return Response from the API call
   */
  async getSettlementData(
    fromDate: string,
    toDate: string,
    status: string,
    pageNo: number,
    size: number,
    requestId: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetSettlementData>> {
    const req = this.createRequest(
      'GET',
      '/api/v1/external/gc/partner/settlements'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      fromDate: [fromDate, string()],
      toDate: [toDate, string()],
      status: [status, string()],
      pageNo: [pageNo, number()],
      size: [size, number()],
      requestId: [requestId, number()],
    });
    req.header('requestId', mapped.requestId);
    req.query('fromDate', mapped.fromDate);
    req.query('toDate', mapped.toDate);
    req.query('status', mapped.status);
    req.query('pageNo', mapped.pageNo);
    req.query('size', mapped.size);
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(getSettlementDataSchema, requestOptions);
  }

  /**
   * @param token
   * @param requestId
   * @return Response from the API call
   */
  async deleteMerchantToken(
    token: string,
    requestId: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeleteMerchantToken>> {
    const req = this.createRequest(
      'DELETE',
      '/api/v1/external/gc/partner/merchant/4230/api-key'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      token: [token, string()],
      requestId: [requestId, number()],
    });
    req.header('requestId', mapped.requestId);
    req.query('token', mapped.token);
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(deleteMerchantTokenSchema, requestOptions);
  }

  /**
   * @param requestId
   * @param body
   * @return Response from the API call
   */
  async createBrandId(
    requestId: number,
    body: CreateBrandIdRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateBrandId>> {
    const req = this.createRequest(
      'POST',
      '/api/v1/external/gc/partner/merchant/4230/brand'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      requestId: [requestId, number()],
      body: [body, createBrandIdRequestSchema],
    });
    req.header('requestId', mapped.requestId);
    req.json(mapped.body);
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(createBrandIdSchema, requestOptions);
  }

  /**
   * @param brandId
   * @param requestId
   * @return Response from the API call
   */
  async deleteBrandId(
    brandId: string,
    requestId: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeleteBrandId>> {
    const req = this.createRequest(
      'DELETE',
      '/api/v1/external/gc/partner/merchant/4230/brand'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      brandId: [brandId, string()],
      requestId: [requestId, number()],
    });
    req.header('requestId', mapped.requestId);
    req.query('brandId', mapped.brandId);
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(deleteBrandIdSchema, requestOptions);
  }

  /**
   * @param requestId
   * @param body
   * @return Response from the API call
   */
  async requestGlobalAccount(
    requestId: number,
    body: RequestGlobalAccountRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RequestGlobalAccount>> {
    const req = this.createRequest(
      'POST',
      '/api/v1/external/gc/partner/merchant/4230/global-account'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      requestId: [requestId, number()],
      body: [body, requestGlobalAccountRequestSchema],
    });
    req.header('requestId', mapped.requestId);
    req.json(mapped.body);
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(requestGlobalAccountSchema, requestOptions);
  }

  /**
   * @param requestId
   * @return Response from the API call
   */
  async getGlobalAccounts(
    requestId: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetGlobalAccounts>> {
    const req = this.createRequest(
      'GET',
      '/api/v1/external/gc/partner/merchant/4212/global-account'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ requestId: [requestId, number()] });
    req.header('requestId', mapped.requestId);
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(getGlobalAccountsSchema, requestOptions);
  }

  /**
   * @param requestId
   * @param body
   * @return Response from the API call
   */
  async bulkUpdateInvoiceNo(
    requestId: string,
    body: BulkUpdateInvoiceNoRequest[],
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BulkUpdateInvoiceNo>> {
    const req = this.createRequest(
      'PATCH',
      '/api/v1/external/gc/partner/transactions/invoice'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      requestId: [requestId, string()],
      body: [body, array(bulkUpdateInvoiceNoRequestSchema)],
    });
    req.header('requestId', mapped.requestId);
    req.json(mapped.body);
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(bulkUpdateInvoiceNoSchema, requestOptions);
  }
}
