/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreateCustomerRequest,
  createCustomerRequestSchema,
} from '../models/createCustomerRequest.js';
import {
  CreatePayOutRequest5,
  createPayOutRequest5Schema,
} from '../models/createPayOutRequest5.js';
import { Success19, success19Schema } from '../models/success19.js';
import { Success21, success21Schema } from '../models/success21.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ExistingCustomerError } from '../errors/existingCustomerError.js';
import { FailureError } from '../errors/failureError.js';
import { InvalidCustomerError } from '../errors/invalidCustomerError.js';

export class MVirtualCardsPayoutApi extends BaseApi {
  /**
   * **OVERIEW**
   *
   * The **createCustomer API** allows merchants to create a customer profile on PaySecure when a user
   * visits their website, facilitating a seamless payment experience by pre-filling the customer's
   * details, on the PaySecure Cashier. The API takes in customer information and returns a unique
   * customerID that can be passed in purchase payload, eliminating the need for customers to manually
   * enter their details during transactions.
   *
   * | Parameter | Type | **Required** | Description | Example |
   * | --- | --- | --- | --- | --- |
   * | merchantCustomerId | String | Yes | unique customer ID provided by merchant. This can be email,
   * mobile or an alphanumeric string | [rahultestcustomer@paysecure.net](https://mailto:
   * rahultestcustomer@paysecure.net) |
   * | fullName | String | Yes | Full name of the customer. | Rahul Agarwal |
   * | emailId | String | Yes | Email address of the customer. | [test@paysecure.net](https://mailto:
   * test@paysecure.net) |
   * | dateOfBirth | String | Optional | Customer's date of birth in YYYY-MM-DD format. | 1995-12-27 |
   * | phoneNo | String | Yes | Customer's phone number. Preferred with the country code | +91 797639082
   * |
   * | city | String | Optional | City of the customer. | Jaipur |
   * | stateCode | String | Yes | State code of the customer. | RJ |
   * | zipCode | String | Optional | Postal code of the customer's location. | 302018 |
   * | address | String | Optional | Full address of the customer. | House Number 53, Vaishali Nagar,
   * Jaipur |
   * | country | String | Yes | Country code (ISO 3166-1 alpha-2). | IN |
   * | custRegDate | Sting | Optional | Customer registration date on merchant site in YYYY-MM-DD format.
   * | 2023-12-27 |
   * | successTxn | String | Optional | Number of successful transactions customer has carried on
   * merchant site. | 32 |
   *
   * ### **User Flow**
   *
   * 1. **Customer visits merchant's website**: The customer selects the product or service and proceeds
   * to checkout page.
   *
   * 2. **Merchant calls the** **`createCustomer`** **API**: The merchant sends a `POST` request to the
   * Paysecure API with the customer's details.
   *
   * 3. **Customer ID generation**: Paysecure processes the request and generates a unique `customerId`
   * which is returned in the response.
   *
   * 4. **Payment Process**: The merchant uses the `customerId` for subsequent session creation, ensuring
   * the customer doesn’t need to re-enter their details for future payments.
   *
   *
   * ---
   *
   * ### **Benefits**
   *
   * - **Seamless user experience**: The customer does not have to enter their details manually for every
   * purchase.
   *
   * - **Faster Checkout**: The merchant can use the `customerId` for faster payment processing.
   *
   * - **Data Security**: Customer details are stored securely and can be reused across transactions,
   * reducing the chances of errors.
   *
   *
   * ### Implementing createCustomer on merchant site:
   *
   * The `createCustomer` can be implemented on merchant site in one of two ways, depending on merchant’s
   * integration flow:
   *
   * **At Checkout:**
   *
   * When a customer initiates the checkout process, your system should invoke the `createCustomer` API,
   * before actually starting the session.
   *
   * - **Call** **`createCustomer`**: This API call generates a unique customer ID.
   *
   * - **Use of Customer ID:** Pass the returned customer ID in Session API, when creating a payment
   * session.
   *
   *
   * **Upon Customer Login:**
   *
   * Alternatively, merchants may choose to call `createCustomer` at the time of customer login on their
   * site.
   *
   * - **Persistent Customer Profiles:** This approach can help build or maintain a persistent customer
   * profile, ensuring the customer ID is available for any subsequent payment sessions without needing
   * to call `createCustomer` again.
   *
   * - **Integration Flexibility:** This is useful for merchants who want to initialize customer data
   * early in the customer journey rather than during checkout.
   *
   *
   * The method you choose depends on your business requirements and how your system is architected.
   * Regardless of when you call it, the resulting customer ID must be passed to the `createSession` API
   * to initiate a payment session.
   *
   * @param brandId
   * @param body
   * @return Response from the API call
   */
  async createCustomer(
    brandId: string,
    body: CreateCustomerRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success19>> {
    const req = this.createRequest('POST', '/api/v1/customer');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      brandId: [brandId, string()],
      body: [body, createCustomerRequestSchema],
    });
    req.header('BrandId', mapped.brandId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, FailureError, 'Bad Request');
    req.throwOn(401, ExistingCustomerError, 'Unauthorized');
    req.authenticate([]);
    return req.callAsJson(success19Schema, requestOptions);
  }

  /**
   * This endpoint makes an HTTP GET request to retrieve customer information from the Paysecure API.
   *
   * ### Request
   *
   * The request does not include any query parameters, but it uses a raw request body with the following
   * parameter "merchantCustomerId", which will be the customer id on the merchant's side.
   *
   * ### Response
   *
   * The response of this request can be documented as a JSON schema.
   *
   * @param brandId
   * @param accept
   * @return Response from the API call
   */
  async getCustomer(
    brandId: string,
    accept: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success19>> {
    const req = this.createRequest('GET', '/customer');
    req.baseUrl('Server 2');
    const mapped = req.prepareArgs({
      brandId: [brandId, string()],
      accept: [accept, string()],
    });
    req.header('BrandId', mapped.brandId);
    req.header('Content-Type', 'application/json');
    req.header('Accept', mapped.accept);
    req.throwOn(400, InvalidCustomerError, 'Bad Request');
    req.authenticate([]);
    return req.callAsJson(success19Schema, requestOptions);
  }

  /**
   * To Initiate a payout, the very first call to make is /payout/
   *
   * with the required data in the request body.
   *
   * To generate a Payout, you are required to provide the `API key` (in the header) can be located in
   * the Dashboard section of your merchant account login.
   *
   * The request body structure is shown on the request body of the example request shown here.
   *
   * @param body
   * @return Response from the API call
   */
  async createPayOut(
    body: CreatePayOutRequest5,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success21>> {
    const req = this.createRequest('POST', '/api/v1/payout');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      body: [body, createPayOutRequest5Schema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsJson(success21Schema, requestOptions);
  }
}
