/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreatePurchaseRequest,
  createPurchaseRequestSchema,
} from '../models/createPurchaseRequest.js';
import {
  CreatePurchaseRequest2,
  createPurchaseRequest2Schema,
} from '../models/createPurchaseRequest2.js';
import {
  PayinApIsRequest,
  payinApIsRequestSchema,
} from '../models/payinApIsRequest.js';
import { Purchases1, purchases1Schema } from '../models/purchases1.js';
import {
  PurchasesRequest,
  purchasesRequestSchema,
} from '../models/purchasesRequest.js';
import {
  PurchasesRequest11,
  purchasesRequest11Schema,
} from '../models/purchasesRequest11.js';
import {
  PurchasesRequest2,
  purchasesRequest2Schema,
} from '../models/purchasesRequest2.js';
import {
  PurchasesRequest3,
  purchasesRequest3Schema,
} from '../models/purchasesRequest3.js';
import {
  PurchasesRequest4,
  purchasesRequest4Schema,
} from '../models/purchasesRequest4.js';
import {
  PurchasesRequest5,
  purchasesRequest5Schema,
} from '../models/purchasesRequest5.js';
import {
  PurchasesRequest8,
  purchasesRequest8Schema,
} from '../models/purchasesRequest8.js';
import {
  PurchasesRequest9,
  purchasesRequest9Schema,
} from '../models/purchasesRequest9.js';
import {
  PurchasesSuccess1,
  purchasesSuccess1Schema,
} from '../models/purchasesSuccess1.js';
import {
  PurchasesSuccess2,
  purchasesSuccess2Schema,
} from '../models/purchasesSuccess2.js';
import {
  PurchaseSuccess,
  purchaseSuccessSchema,
} from '../models/purchaseSuccess.js';
import {
  PurchaseSuccess1,
  purchaseSuccess1Schema,
} from '../models/purchaseSuccess1.js';
import {
  PurchaseSuccess2,
  purchaseSuccess2Schema,
} from '../models/purchaseSuccess2.js';
import {
  PurchaseSuccess3,
  purchaseSuccess3Schema,
} from '../models/purchaseSuccess3.js';
import { Success10, success10Schema } from '../models/success10.js';
import { Success11, success11Schema } from '../models/success11.js';
import { Success13, success13Schema } from '../models/success13.js';
import { Success16, success16Schema } from '../models/success16.js';
import { Success17, success17Schema } from '../models/success17.js';
import { Success22, success22Schema } from '../models/success22.js';
import { Success3, success3Schema } from '../models/success3.js';
import { Success7, success7Schema } from '../models/success7.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class PayinApIsApi extends BaseApi {
  /**
   * To Initiate a payment, the very first call to make is `/purchases` with the required data in the
   * request body.
   *
   * To generate a Purchase, you are required to provide the `Brand ID` (in the request body) and `API
   * key` (in the header) which can be located in the Dashboard section of your merchant account login.
   *
   * The request body structure is shown on the request body of the example request shown here.
   *
   * The following (see table below) are the mandatory parameters that are required to create a purchase
   * request.
   *
   * ### **Mandatory parameters in the request body:**
   *
   * | **Parameter** | **Notes** |
   * | --- | --- |
   * | client.email | An Identifier for a user |
   * | client.city | An Identifier for a user |
   * | client.country | ISO-3166 Country Code. It must be upper case.  <br>This should be "CA" for
   * Interac |
   * | client.stateCode | Example “AL”, “XZ”.. Must be in upper case. |
   * | client.street_address |  |
   * | client.zip_code |  |
   * | client.phone |  |
   * | client.full_name |  |
   * | purchase.currency | ISO 4217 code for currency you want to send the transaction in.  <br>This
   * should be 'CAD' for Interac |
   * | purchase.products.name | name of the product or service |
   * | purchase.products.price | Price in decimal format.  <br>example 1:  <br>EUR 5 , should be sent as
   * 5.00  <br>  <br>example 2:  <br>USD 10 and 37 cents , should be sent as 10.37 |
   * | brand_id | Obtain from Dashboard section of your merchant account login. |
   * | success_redirect | URL to send the user if the transactions is successful |
   * | pending_redirect | URL to send the user if the transactions is in progress |
   * | failure_redirect | URL to send the user if the transactions is UNSUCCESSFUL |
   *
   * ## Optional Parameters
   *
   * ### expireInMin
   *
   * The `purchase.expireInMin`, when passed in the PayIn request, sets the time window within which a
   * customer should make the Interac payment through their bank's app. If a customer doesn't complete
   * the payment within the configured time window, the status of the payment will be marked as 'EXPIRED'
   * in Paysecure.
   *
   * However, in certain cases, a payment made outside of this window could still be successful i.e.
   * customer's account may be debited which would result in inconsistencies among Paysecure's,
   * merchant's and customer's status of the transaction. To avoid such cases it is advised to set the
   * expiry time limit appropriately and advise the customers to make payment within this window. However,
   * if there is an inconsistency between the status at Paysecure and at customer's Bank, the merchant
   * and Paysecure will reconcile the amounts during the settlement.
   *
   * ### merchantRef
   *
   * The `merchantRef` parameter, although not mandatory, is strongly advised for merchants to specify.
   * Its inclusion offers two significant advantages for the merchant:
   *
   * 1. **Prevention of Duplicate Requests:** When a `merchantRef` is utilized, it acts as a unique
   * identifier. This means that if a second purchase request is made using the same `merchantRef`
   * (reference number), the system will recognize it and prevent duplicate transactions from occurring.
   * This prevents unintended or duplicate purchases.
   *
   * 2. **Facilitation of Transaction Retrieval:** In situations where the response from the initial
   * purchase request times out or the 'purchaseId' isn't received, having the `merchantRef` allows the
   * merchant to retrieve detailed transaction information. This ensures they can track and access the
   * specific purchase details related to that reference, even if the immediate response was not received.
   *
   *
   * However, if the merchant does not specify the 'merchantRef' parameter, the platform will
   * automatically assign and use an internal 'purchaseId' as a reference for that transaction.
   *
   * ### paymentMethod
   *
   * The `paymentMethod` parameter identifies which payment solution merchant wants to use to perform a
   * transaction. If parameter is provided, than Paysecure will perform direct payment with the selected
   * payment method instead of loading Paysecure URL.
   *
   * ### Possible Error Messages
   *
   * | **Error Messages** | **Description** |
   * | --- | --- |
   * | Invalid format of Date_of_Birth\[allowed format: yyyy-mm-dd\] |  |
   * | Enter Valid Email |  |
   * | Please submit Valid Alpha2 Country Code Ex:(AF,IN) in \\"country\\" parameter |  |
   * | Please pass Valid State Code |  |
   * | Please pass valid street address in \\"street_address\\" parameter |  |
   * | Please pass valid city name in \\"city\\" parameter |  |
   * | Please pass valid postal Code name in \\"zip_code\\" parameter |  |
   * | You are not Allowed for Live Transaction |  |
   * | Minimum amount is not set for this merchant |  |
   * | success_redirect/failure_redirect/brand_id is missing |  |
   * | brand_id cannot be null |  |
   * | success_redirect cannot be null |  |
   * | failure_redirect cannot be null |  |
   * | Invalid failure_redirect: minimum 10 characters |  |
   * | purchase.products.price cannot be null |  |
   * | purchase.products\[0\].name/purchase.products\[0\].price are missing |  |
   * | Your charges setting is incomplete .Plese Contact to Administrator. |  |
   * | Currency "{curr_name}" is Not Allowed |  |
   * | Transaction amount must be equal or greater to minimum trans amount |  |
   * | Allowed Limit for this card for particular time period has been consumed |  |
   *
   * **Note:** For certain use cases, in addition to long format purchase Id, Paysecure also provides a 7
   * digit unique code for each purchase starting with digit 4, eg 4000001
   *
   * _“purchaseIdShortCode”: “4000013"_
   *
   * @param body
   * @return Response from the API call
   */
  async purchases(
    body: PurchasesRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PurchaseSuccess>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ body: [body, purchasesRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsJson(purchaseSuccessSchema, requestOptions);
  }

  /**
   * This API tells you about all the details of a purchase (PayIn), including its history
   *
   * **Note:** With respect to bank transfers, the purchase request is synonymous with the PayIn request.
   *
   * ### Mandatory
   *
   * you need to pass the `PurchaseID` in the API URL
   *
   * ### Possible Value of Status
   *
   * | **Status** | **Notes** |
   * | --- | --- |
   * | paid | Transaction Successful |
   * | payment_in_process | Payment is under Processing |
   * | expired | Purchase has Expired. |
   * | error | Transaction has Failed. |
   *
   * ### Response Examples
   *
   * In the response examples you can see instances of both `Paid` and `Error` Status purchases.
   *
   * ### Error Details
   *
   * If there are any issues on the Purchase you can get more details from the `transaction_data.attempts.
   * error` attribute of the response object
   *
   * ### Errors
   *
   * If there are any errors then it'll be in the format of :
   *
   * ``` json
   * {
   * "message": "descriptive error message",
   * "code": "error_code"
   * }
   *
   * ```
   *
   * Please see the Status Code section for further details.
   *
   * @param purchaseId
   * @return Response from the API call
   */
  async getStatus(
    purchaseId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PurchasesSuccess1>> {
    const req = this.createRequest('GET');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ purchaseId: [purchaseId, string()] });
    req.header('Content-Type', 'application/json');
    req.appendTemplatePath`/api/v1/purchases/${mapped.purchaseId}`;
    req.authenticate([]);
    return req.callAsJson(purchasesSuccess1Schema, requestOptions);
  }

  /**
   * To Initiate a payment, the very first call to make is `/purchases` with the required data in the
   * request body.
   *
   * To generate a Purchase, you are required to provide the `Brand ID` (in the request body) and `API
   * key` (in the header) Both can be located in the Dashboard section of your merchant account login.
   *
   * The request body structure is shown on the request body of the example request shown here.
   *
   * The following (see table below) are the mandatory parameters that are required to create a purchase
   * request.
   *
   * ### **Mandatory parameters in the request body:**
   *
   * | **Parameter** | **Notes** |
   * | --- | --- |
   * | client.email | An Identifier for a user |
   * | client.city |  |
   * | client.country | ISO-3166 Country Code. It must be upper case.  <br>This should be "CA" for
   * Interac |
   * | client.stateCode | Example “AL”, “XZ”.. Must be in upper case. |
   * | client.street_address |  |
   * | client.zip_code |  |
   * | client.phone |  |
   * | client.full_name |  |
   * | purchase.currency | ISO 4217 code for currency you want to send the transaction in.  <br>This
   * should be 'CAD' for Interac |
   * | purchase.products.name |  |
   * | purchase.products.price | Price in decimal format.  <br>example 1:  <br>EUR 5 , should be sent as
   * 5.00  <br>  <br>example 2:  <br>USD 10 and 37 cents , should be sent as 10.37 |
   * | brand_id | Obtain from Dashboard section of your merchant account login. |
   * | success_redirect | URL to send the user if the transactions is successful |
   * | failure_redirect | URL to send the user if the transactions is UNSUCCESSFUL |
   *
   * ## Optional Parameters
   *
   * ### expireInMin
   *
   * This parameter, when passed in the PayIn request, sets the time window within which a customer
   * should make the Interac payment through their bank's app. If a customer doesn't complete the payment
   * within the configured time window, the status of the payment will be marked as 'EXPIRED' in
   * Paysecure.
   *
   * However, in certain cases, a payment made outside of this window could still be successful i.e.
   * customer's account may be debited which would result in inconsistencies among Paysecure's,
   * merchant's and customer's status of the transaction. To avoid such cases it is advised to set the
   * expiry time limit appropriately and advise the customers to make payment within this window. However,
   * if there is an inconsistency between the status at Paysecure and at customer's Bank, the merchant
   * and Paysecure will reconcile the amounts during the settlement.
   *
   * ### merchantRef
   *
   * The `merchantRef` parameter, although not mandatory, is strongly advised for merchants to specify.
   * Its inclusion offers two significant advantages for the merchant:
   *
   * 1. **Prevention of Duplicate Requests:** When a `merchantRef` is utilized, it acts as a unique
   * identifier. This means that if a second purchase request is made using the same `merchantRef`
   * (reference number), the system will recognize it and prevent duplicate transactions from occurring.
   * This prevents unintended or duplicate purchases.
   *
   * 2. **Facilitation of Transaction Retrieval:** In situations where the response from the initial
   * purchase request times out or the 'purchaseId' isn't received, having the `merchantRef` allows the
   * merchant to retrieve detailed transaction information. This ensures they can track and access the
   * specific purchase details related to that reference, even if the immediate response was not received.
   *
   *
   * However, if the merchant does not specify the 'merchantRef' parameter, the platform will
   * automatically assign and use an internal 'purchaseId' as a reference for that transaction.
   *
   * ### paymentMethod
   *
   * The `paymentMethod` parameter identifies which payment solution merchant wants to use to perform a
   * transaction. If parameter is provided, than Paysecure will perform direct payment with the selected
   * payment method instead of loading Paysecure URL.
   *
   * ### Possible Error Messages
   *
   * | **Error Messages** | **Description** |
   * | --- | --- |
   * | Invalid format of Date_of_Birth\[allowed format: yyyy-mm-dd\] |  |
   * | Enter Valid Email |  |
   * | Please submit Valid Alpha2 Country Code Ex:(AF,IN) in \\"country\\" parameter |  |
   * | Please pass Valid State Code |  |
   * | Please pass valid street address in \\"street_address\\" parameter |  |
   * | Please pass valid city name in \\"city\\" parameter |  |
   * | Please pass valid postal Code name in \\"zip_code\\" parameter |  |
   * | You are not Allowed for Live Transaction |  |
   * | Minimum amount is not set for this merchant |  |
   * | success_redirect/failure_redirect/brand_id is missing |  |
   * | brand_id cannot be null |  |
   * | success_redirect cannot be null |  |
   * | failure_redirect cannot be null |  |
   * | Invalid failure_redirect: minimum 10 characters |  |
   * | purchase.products.price cannot be null |  |
   * | purchase.products\[0\].name/purchase.products\[0\].price are missing |  |
   * | Your charges setting is incomplete .Plese Contact to Administrator. |  |
   * | Currency "{curr_name}" is Not Allowed |  |
   * | Transaction amount must be equal or greater to minimum trans amount |  |
   * | Allowed Limit for this card for particular time period has been consumed |  |
   *
   * **Note:** For certain use cases, in addition to long format purchase Id, Paysecure also provides a 7
   * digit unique code for each purchase starting with digit 4, eg 4000001
   *
   * _“purchaseIdShortCode”: “4000013"_
   *
   * @param body
   * @return Response from the API call
   */
  async createPurchase(
    body: CreatePurchaseRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success3>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      body: [body, createPurchaseRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsJson(success3Schema, requestOptions);
  }

  /**
   * This API tells you about all the details of a purchase (PayIn), including its history
   *
   * **Note:** With respect to bank transfers, the purchase request is synonymous with the PayIn request.
   *
   * ### Mandatory
   *
   * you need to pass the `PurchaseID` in the API URL
   *
   * ### Possible Value of Status
   *
   * | **Status** | **Notes** |
   * | --- | --- |
   * | paid | Transaction Successful |
   * | payment_in_process | Payment is under Processing |
   * | expired | Purchase has Expired. |
   * | error | Transaction has Failed. |
   *
   * ### Response Examples
   *
   * In the response examples you can see instances of both `Paid` and `Error` Status purchases.
   *
   * ### Error Details
   *
   * If there are any issues on the Purchase you can get more details from the `transaction_data.attempts.
   * error` attribute of the response object
   *
   * ### Errors
   *
   * If there are any errors then it'll be in the format of :
   *
   * ``` json
   * {
   * "message": "descriptive error message",
   * "code": "error_code"
   * }
   *
   * ```
   *
   * Please see the Status Code section for further details.
   *
   * @param purchaseId
   * @return Response from the API call
   */
  async getStatus1(
    purchaseId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success3>> {
    const req = this.createRequest('GET');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ purchaseId: [purchaseId, string()] });
    req.header('Content-Type', 'application/json');
    req.appendTemplatePath`/api/v1/purchases/${mapped.purchaseId}`;
    req.authenticate([]);
    return req.callAsJson(success3Schema, requestOptions);
  }

  /**
   * To Initiate a payment, the very first call to make is `/purchases` with the required data in the
   * request body.
   *
   * To generate a Purchase, you are required to provide the `Brand ID` (in the request body) and `API
   * key` (in the header) Both can be located in the Dashboard section of your merchant account login.
   *
   * The request body structure is shown on the request body of the example request shown here.
   *
   * The following (see table below) are the mandatory parameters that are required to create a purchase
   * request.
   *
   * ### **Mandatory parameters in the request body:**
   *
   * | **Parameter** | **Notes** |
   * | --- | --- |
   * | client.email | An Identifier for a user |
   * | client.city | An Identifier for a user |
   * | client.country | ISO-3166 Country Code. It must be upper case.  <br>This should be "CA" for
   * Interac |
   * | client.stateCode | Example “AL”, “XZ”.. Must be in upper case. |
   * | client.street_address |  |
   * | client.zip_code |  |
   * | client.phone |  |
   * | client.full_name |  |
   * | purchase.currency | ISO 4217 code for currency you want to send the transaction in.  <br>This
   * should be 'CAD' for Interac |
   * | purchase.products.name | name of the product or service |
   * | purchase.products.price | Price in decimal format.  <br>example 1:  <br>EUR 5 , should be sent as
   * 5.00  <br>  <br>example 2:  <br>USD 10 and 37 cents , should be sent as 10.37 |
   * | brand_id | Obtain from Dashboard section of your merchant account login. |
   * | success_redirect | URL to send the user if the transactions is successful |
   * | pending_redirect | URL to send the user if the transactions is in progress |
   * | failure_redirect | URL to send the user if the transactions is UNSUCCESSFUL |
   *
   * ## Optional Parameters
   *
   * ### expireInMin
   *
   * The `purchase.expireInMin`, when passed in the PayIn request, sets the time window within which a
   * customer should make the Interac payment through their bank's app. If a customer doesn't complete
   * the payment within the configured time window, the status of the payment will be marked as 'EXPIRED'
   * in Paysecure.
   *
   * However, in certain cases, a payment made outside of this window could still be successful i.e.
   * customer's account may be debited which would result in inconsistencies among Paysecure's,
   * merchant's and customer's status of the transaction. To avoid such cases it is advised to set the
   * expiry time limit appropriately and advise the customers to make payment within this window. However,
   * if there is an inconsistency between the status at Paysecure and at customer's Bank, the merchant
   * and Paysecure will reconcile the amounts during the settlement.
   *
   * ### merchantRef
   *
   * The `merchantRef` parameter, although not mandatory, is strongly advised for merchants to specify.
   * Its inclusion offers two significant advantages for the merchant:
   *
   * 1. **Prevention of Duplicate Requests:** When a `merchantRef` is utilized, it acts as a unique
   * identifier. This means that if a second purchase request is made using the same `merchantRef`
   * (reference number), the system will recognize it and prevent duplicate transactions from occurring.
   * This prevents unintended or duplicate purchases.
   *
   * 2. **Facilitation of Transaction Retrieval:** In situations where the response from the initial
   * purchase request times out or the 'purchaseId' isn't received, having the `merchantRef` allows the
   * merchant to retrieve detailed transaction information. This ensures they can track and access the
   * specific purchase details related to that reference, even if the immediate response was not received.
   *
   *
   * However, if the merchant does not specify the 'merchantRef' parameter, the platform will
   * automatically assign and use an internal 'purchaseId' as a reference for that transaction.
   *
   * ### paymentMethod
   *
   * The `paymentMethod` parameter identifies which payment solution merchant wants to use to perform a
   * transaction. If parameter is provided, than Paysecure will perform direct payment with the selected
   * payment method instead of loading Paysecure URL.
   *
   * ### Possible Error Messages
   *
   * | **Error Messages** | **Description** |
   * | --- | --- |
   * | Invalid format of Date_of_Birth\[allowed format: yyyy-mm-dd\] |  |
   * | Enter Valid Email |  |
   * | Please submit Valid Alpha2 Country Code Ex:(AF,IN) in \\"country\\" parameter |  |
   * | Please pass Valid State Code |  |
   * | Please pass valid street address in \\"street_address\\" parameter |  |
   * | Please pass valid city name in \\"city\\" parameter |  |
   * | Please pass valid postal Code name in \\"zip_code\\" parameter |  |
   * | You are not Allowed for Live Transaction |  |
   * | Minimum amount is not set for this merchant |  |
   * | success_redirect/failure_redirect/brand_id is missing |  |
   * | brand_id cannot be null |  |
   * | success_redirect cannot be null |  |
   * | failure_redirect cannot be null |  |
   * | Invalid failure_redirect: minimum 10 characters |  |
   * | purchase.products.price cannot be null |  |
   * | purchase.products\[0\].name/purchase.products\[0\].price are missing |  |
   * | Your charges setting is incomplete .Plese Contact to Administrator. |  |
   * | Currency "{curr_name}" is Not Allowed |  |
   * | Transaction amount must be equal or greater to minimum trans amount |  |
   * | Allowed Limit for this card for particular time period has been consumed |  |
   *
   * **Note:** For certain use cases, in addition to long format purchase Id, Paysecure also provides a 7
   * digit unique code for each purchase starting with digit 4, eg 4000001
   *
   * _“purchaseIdShortCode”: “4000013"_
   *
   * @param body
   * @return Response from the API call
   */
  async purchases1(
    body: PurchasesRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PurchaseSuccess1>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ body: [body, purchasesRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsJson(purchaseSuccess1Schema, requestOptions);
  }

  /**
   * To Initiate a payment, the very first call to make is `/purchases` with the required data in the
   * request body.
   *
   * To generate a Purchase, you are required to provide the `Brand ID` (in the request body) and `API
   * key` (in the header) Both can be located in the Dashboard section of your merchant account login.
   *
   * The request body structure is shown on the request body of the example request shown here.
   *
   * The following (see table below) are the mandatory parameters that are required to create a purchase
   * request.
   *
   * ### **Request Body Parameters:**
   *
   * | **Parameter** | **Notes** |
   * | --- | --- |
   * | client.full_name | Conditional.  <br>But Recommended to pass the complete name of the client.
   * Atleast 2 words recommended. |
   * | client.email | Conditional.  <br>But Recommended to pass a correct email id. |
   * | client.tax_number | Mandatory.  <br>Pass the CPF (Brazilian tax identification number of customer),
   * must contain 11 digits. |
   * | paymentMethod | Conditional.  <br>Mandatory if you are not using Paysecure Cashier. Else Non
   * Mandatory.  <br>Value: PIX |
   * | purchase.currency | Mandatory.  <br>ISO 4217 code for currency you want to send the transaction in.
   * This should be 'BRL' for PIX. |
   * | purchase.products.name | Mandatory. |
   * | purchase.products.price | Mandatory.  <br>Price in decimal format upto 2 decimals.  <br>example 1:
   * <br>EUR 5 , should be sent as 5.00  <br>example 2:  <br>USD 10 and 37 cents , should be sent as 10.
   * 37 |
   * | brand_id | Mandatory.  <br>Obtain from Dashboard section of your merchant account login. |
   * | success_redirect | Mandatory.  <br>URL to send the user if the transactions is successful. |
   * | pending_redirect | Mandatory.  <br>URL to send the user if the transactions is in progress state.
   * |
   * | failure_redirect | Mandatory  <br>URL to send the user if the transactions has failed. |
   *
   * **Note:** the object “pix_payload.payload” contains all the necessary fields to create a page
   * containing a QR code and other information on the merchant portal. The field “pix_payload.qr_code”
   * value is in Base64. This can be used to show the QR code image. The field "pix_payload.
   * expiration_date" is in UTC time.
   *
   * ## Essential Optional Parameters
   *
   * ### merchantRef
   *
   * The `merchantRef` parameter, although not mandatory, is strongly advised for merchants to specify.
   * Its inclusion offers two significant advantages for the merchant:
   *
   * 1. **Prevention of Duplicate Requests:** When a `merchantRef` is utilized, it acts as a unique
   * identifier. This means that if a second purchase request is made using the same `merchantRef`
   * (reference number), the system will recognize it and prevent duplicate transactions from occurring.
   * This prevents unintended or duplicate purchases.
   *
   * 2. **Facilitation of Transaction Retrieval:** In situations where the response from the initial
   * purchase request times out or the 'purchaseId' isn't received, having the `merchantRef` allows the
   * merchant to retrieve detailed transaction information. This ensures they can track and access the
   * specific purchase details related to that reference, even if the immediate response was not received.
   *
   *
   * However, if the merchant does not specify the 'merchantRef' parameter, the platform will
   * automatically assign and use an internal 'purchaseId' as a reference for that transaction.
   *
   * ### paymentMethod
   *
   * The `paymentMethod` parameter identifies which payment solution merchant wants to use to perform a
   * transaction. If parameter is provided, than Paysecure will perform direct payment with the selected
   * payment method instead of loading Paysecure URL.
   *
   * ### Possible Error Messages
   *
   * | **Error Messages** | **Description** |
   * | --- | --- |
   * | Allowed Limit for this card for particular time period has been consumed |  |
   * | some Mandatory Parameter are missing |  |
   * | Invalid format of Date_of_Birth\[allowed format: yyyy-mm-dd\] |  |
   * | Invalid Email Format |  |
   * | Please submit Valid Alpha2 Country Code Ex:(AF,IN) in \\"country\\" parameter |  |
   * | Please pass Valid State Code |  |
   * | Please pass valid street address in \\"street_address\\" parameter |  |
   * | Please pass valid city name in \\"city\\" parameter |  |
   * | Please pass valid postal Code name in \\"zip_code\\" parameter |  |
   * | You are not Allowed for Live Transaction |  |
   * | Merchant Limit is not set |  |
   * | Minimum amount is not set for this merchant |  |
   * | Brand not found! |  |
   * | Your charges setting is incomplete .Plese Contact to Administrator. |  |
   * | Only `“{curr_name}"` currency is allowed |  |
   * | Transaction amount must be equal or greater to minimum trans amount |  |
   * | Invalid_Parameter | You'd usually get it when one or more mandatory parameters are not present in
   * the request. |
   *
   * @param body
   * @return Response from the API call
   */
  async purchases2(
    body: PurchasesRequest2,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PurchaseSuccess2>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ body: [body, purchasesRequest2Schema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsJson(purchaseSuccess2Schema, requestOptions);
  }

  /**
   * This API tells you about all the details of a purchase, including its history
   *
   * ### Mandatory
   *
   * you need to pass the `PurchaseID` in the API URL
   *
   * ### Possible Value of Status
   *
   * | **Status** | **Notes** |
   * | --- | --- |
   * | paid | Transaction Successful |
   * | payment_in_process | Payment is under Processing |
   * | expired | The purchase has Expired. |
   * | error | Transaction has Failed. |
   *
   * ### Response Examples
   *
   * In the response examples you can see instances of both `Paid` and `Error` Status purchases.
   *
   * ### Error Details
   *
   * If there are any issues on the Purchase you can get more details from the `transaction_data.attempts.
   * error` attribute of the response object
   *
   * ### Errors
   *
   * If there are any errors then it'll be in the format of :
   *
   * ``` json
   * {
   * "message": "descriptive error message",
   * "code": "error_code"
   * }
   *
   * ```
   *
   * Please see the Status Code section for further details.
   *
   * @param purchaseId
   * @return Response from the API call
   */
  async getStatus2(
    purchaseId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success7>> {
    const req = this.createRequest('GET');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ purchaseId: [purchaseId, string()] });
    req.header('Content-Type', 'application/json');
    req.appendTemplatePath`/api/v1/purchases/${mapped.purchaseId}`;
    req.authenticate([]);
    return req.callAsJson(success7Schema, requestOptions);
  }

  /**
   * To Initiate a payment, the very first call to make is `/purchases` with the required data in the
   * request body.
   *
   * To generate a Purchase, you are required to provide the `Brand ID` (in the request body) and `API
   * key` (in the header) Both can be located in the Dashboard section of your merchant account login.
   *
   * The request body structure is shown on the request body of the example request shown here.
   *
   * The following (see table below) are the mandatory parameters that are required to create a purchase
   * request.
   *
   * ### **Mandatory parameters in the request body:**
   *
   * | **Parameter** | **Notes** |
   * | --- | --- |
   * | client.email | An Identifier for a user |
   * | client.city |  |
   * | client.country | ISO-3166 Country Code. It must be upper case. Example “SG” (Alpha2) |
   * | client.stateCode | Example “AL”, “XZ”.. Must be in upper case. |
   * | client.street_address |  |
   * | client.zip_code |  |
   * | client.phone |  |
   * | client.full_name |  |
   * | purchase.currency | ISO 4217 code for currency you want to send the transaction in.  <br>Please
   * note, the currency has to be enbaled by the account manager for your account. |
   * | purchase.products.name |  |
   * | purchase.products.price | Price in decimal format.  <br>example 1:  <br>EUR 5 , should be sent as
   * 5.00  <br>  <br>example 2:  <br>USD 10 and 37 cents , should be sent as 10.37 |
   * | brand_id | Obtain from Dashboard section of your merchant account login. |
   * | success_redirect | URL to send the user if the transactions is successful |
   * | failure_redirect | URL to send the user if the transactions is UNSUCCESSFUL |
   *
   * ## Optional Parameters
   *
   * ### merchantRef
   *
   * The `merchantRef` parameter, although not mandatory, is strongly advised for merchants to specify.
   * Its inclusion offers two significant advantages for the merchant:
   *
   * 1. **Prevention of Duplicate Requests:** When a `merchantRef` is utilized, it acts as a unique
   * identifier. This means that if a second purchase request is made using the same `merchantRef`
   * (reference number), the system will recognize it and prevent duplicate transactions from occurring.
   * This prevents unintended or duplicate purchases.
   *
   * 2. **Facilitation of Transaction Retrieval:** In situations where the response from the initial
   * purchase request times out or the 'purchaseId' isn't received, having the `merchantRef` allows the
   * merchant to retrieve detailed transaction information. This ensures they can track and access the
   * specific purchase details related to that reference, even if the immediate response was not received.
   *
   *
   * However, if the merchant does not specify the 'merchantRef' parameter, the platform will
   * automatically assign and use an internal 'purchaseId' as a reference for that transaction.
   *
   * ### paymentMethod
   *
   * The `paymentMethod` parameter identifies which payment solution merchant wants to use to perform a
   * transaction. If parameter is provided, than Paysecure will perform direct payment with the selected
   * payment method instead of loading Paysecure URL.
   *
   * ### Possible Error Messages
   *
   * | **Error Messages** | **Description** |
   * | --- | --- |
   * | Invalid format of Date_of_Birth\[allowed format: yyyy-mm-dd\] |  |
   * | Enter Valid Email |  |
   * | Please submit Valid Alpha2 Country Code Ex:(AF,IN) in \\"country\\" parameter |  |
   * | Please pass Valid State Code |  |
   * | Please pass valid street address in \\"street_address\\" parameter |  |
   * | Please pass valid city name in \\"city\\" parameter |  |
   * | Please pass valid postal Code name in \\"zip_code\\" parameter |  |
   * | You are not Allowed for Live Transaction |  |
   * | Minimum amount is not set for this merchant |  |
   * | success_redirect/failure_redirect/brand_id is missing |  |
   * | brand_id cannot be null |  |
   * | success_redirect cannot be null |  |
   * | failure_redirect cannot be null |  |
   * | Invalid failure_redirect: minimum 10 characters |  |
   * | purchase.products.price cannot be null |  |
   * | purchase.products\[0\].name/purchase.products\[0\].price are missing |  |
   * | Your charges setting is incomplete .Plese Contact to Administrator. |  |
   * | Currency "{curr_name}" is Not Allowed |  |
   * | Transaction amount must be equal or greater to minimum trans amount |  |
   * | Allowed Limit for this card for particular time period has been consumed |  |
   *
   * **Note:** For certain use cases, in addition to long format purchase Id, Paysecure also provides a 7
   * digit unique code for each purchase starting with digit 4, eg 4000001
   *
   * _“purchaseIdShortCode”: “4000013"_
   *
   * @param body
   * @return Response from the API call
   */
  async purchases3(
    body: PurchasesRequest3,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PurchaseSuccess3>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ body: [body, purchasesRequest3Schema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsJson(purchaseSuccess3Schema, requestOptions);
  }

  /**
   * This API tells you about all the details of a purchase (PayIn), including its history
   *
   * **Note:** With respect to bank transfers, the purchase request is synonymous with the PayIn request.
   *
   * ### Mandatory
   *
   * you need to pass the `PurchaseID` in the API URL
   *
   * ### Possible Value of Status
   *
   * | **Status** | **Notes** |
   * | --- | --- |
   * | paid | Transaction Successful |
   * | payment_in_process | Payment is under Processing |
   * | expired | Purchase has Expired. |
   * | error | Transaction has Failed. |
   *
   * ### Response Examples
   *
   * In the response examples you can see instances of both `Paid` and `Error` Status purchases.
   *
   * ### Error Details
   *
   * If there are any issues on the Purchase you can get more details from the `transaction_data.attempts.
   * error` attribute of the response object
   *
   * ### Errors
   *
   * If there are any errors then it'll be in the format of :
   *
   * ``` json
   * {
   * "message": "descriptive error message",
   * "code": "error_code"
   * }
   *
   * ```
   *
   * Please see the Status Code section for further details.
   *
   * @param purchaseId
   * @return Response from the API call
   */
  async getStatus3(
    purchaseId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PurchasesSuccess2>> {
    const req = this.createRequest('GET');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ purchaseId: [purchaseId, string()] });
    req.header('Content-Type', 'application/json');
    req.appendTemplatePath`/api/v1/purchases/${mapped.purchaseId}`;
    req.authenticate([]);
    return req.callAsJson(purchasesSuccess2Schema, requestOptions);
  }

  /**
   * To Initiate a payment, the very first call to make is `/purchases` with the required data in the
   * request body.
   *
   * To generate a Purchase, you are required to provide the `Brand ID` (in the request body) and `API
   * key` (in the header) Both can be located in the Dashboard section of your merchant account login.
   *
   * The request body structure is shown on the request body of the example request shown here.
   *
   * The following (see table below) are the mandatory parameters that are required to create a purchase
   * request.
   *
   * ### **Mandatory parameters in the request body:**
   *
   * | **Parameter** | **Notes** |
   * | --- | --- |
   * | client.email | The customer's email. |
   * | client.city | The customer's city. |
   * | client.country | ISO-3166 Country Code. Must be upper case. Example “SG” (Alpha2) |
   * | client.stateCode | Example “AL”, “XZ”. Must be in upper case. |
   * | Client.street_address | The customer's address. |
   * | client.zip_code | The customer's ZIP or postal code. If country=US, zip format must be NNNNN or
   * NNNNN-NNNN. |
   * | purchase.currency | ISO 4217 code for currency you want to send the transaction in.  <br>
   * <br>Please note, the currency has to be enabled by the account manager for your account. |
   * | purchase.products | An object which contains the list of products which the customer is buying. |
   * | purchase.products.name | The name of the product. |
   * | purchase.products.price | Price in decimal format.  <br>example 1:  <br>EUR 5 , should be sent as
   * 5.00  <br>  <br>example 2:  <br>USD 10 and 37 cents , should be sent as 10.37 |
   * | brand_id | Obtain from Dashboard section of your merchant account login. |
   * | success_redirect | URL to send the user if the transactions is successful. |
   * | pending_redirect | URL to send the user if the transactions is in pending. |
   * | failure_redirect | URL to send the user if the transactions is unsuccessful. |
   *
   * ## Optional Parameters
   *
   * ### expireInMin
   *
   * This parameter, when passed in the PayIn request, sets the time window within which a customer
   * should make the Interac payment through their bank's app. If a customer doesn't complete the payment
   * within the configured time window, the status of the payment will be marked as 'EXPIRED' in
   * Paysecure.
   *
   * However, in certain cases, a payment made outside of this window could still be successful i.e.
   * customer's account may be debited which would result in inconsistencies among Paysecure's,
   * merchant's and customer's status of the transaction. To avoid such cases it is advised to set the
   * expiry time limit appropriately and advise the customers to make payment within this window. However,
   * if there is an inconsistency between the status at Paysecure and at customer's Bank, the merchant
   * and Paysecure will reconcile the amounts during the settlement.
   *
   * ### merchantRef
   *
   * The `merchantRef` parameter, although not mandatory, is strongly advised for merchants to specify.
   * Its inclusion offers two significant advantages for the merchant:
   *
   * 1. **Prevention of Duplicate Requests:** When a `merchantRef` is utilized, it acts as a unique
   * identifier. This means that if a second purchase request is made using the same `merchantRef`
   * (reference number), the system will recognize it and prevent duplicate transactions from occurring.
   * This prevents unintended or duplicate purchases.
   *
   * 2. **Facilitation of Transaction Retrieval:** In situations where the response from the initial
   * purchase request times out or the 'purchaseId' isn't received, having the `merchantRef` allows the
   * merchant to retrieve detailed transaction information. This ensures they can track and access the
   * specific purchase details related to that reference, even if the immediate response was not received.
   *
   *
   * However, if the merchant does not specify the 'merchantRef' parameter, the platform will
   * automatically assign and use an internal 'purchaseId' as a reference for that transaction.
   *
   * ### paymentMethod
   *
   * The `paymentMethod` parameter identifies which payment solution merchant wants to use to perform a
   * transaction. If parameter is provided, than Paysecure will perform direct payment with the selected
   * payment method instead of loading Paysecure URL.
   *
   * Possible Payment Methods allowed: UPI-QR and UPI-INTENT
   *
   * ### Possible Error Messages
   *
   * | **Error Messages** |
   * | --- |
   * | Allowed Limit for this payment method for particular time period has been consumed |
   * | some Mandatory Parameter are missing |
   * | Invalid format of Date_of_Birth \[allowed format: yyyy-mm-dd\] |
   * | Invalid Email Format |
   * | Please submit Valid Alpha2 Country Code Ex:(AF,IN) in \\"country\\" parameter |
   * | Please pass Valid State Code |
   * | Please pass valid street address in \\"street_address\\" parameter |
   * | Please pass valid city name in \\"city\\" parameter |
   * | Please pass valid postal Code name in \\"zip_code\\" parameter |
   * | You are not Allowed for Live Transaction |
   * | Merchant Limit is not set |
   * | Minimum amount is not set for this merchant |
   * | Brand not found ! |
   * | Your charges setting is incomplete .Plese Contact to Administrator. |
   * | Only {{currencyCode}} currency is allowed. |
   * | Transaction amount must be equal or greater to minimum trans amount |
   * | Invalid_Parameter  <br>You'd usually get it when one or more mandatory parameters are not present
   * in the request. |
   *
   * @param body
   * @return Response from the API call
   */
  async purchases4(
    body: PurchasesRequest4,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ body: [body, purchasesRequest4Schema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsText(requestOptions);
  }

  /**
   * This API tells you about all the details of a purchase (PayIn), including its history
   *
   * **Note:** With respect to bank transfers, the purchase request is synonymous with the PayIn request.
   *
   * ### Mandatory
   *
   * you need to pass the `PurchaseID` in the API URL
   *
   * ### Possible Value of Status
   *
   * | **Status** | **Notes** |
   * | --- | --- |
   * | paid | Transaction Successful |
   * | payment_in_process | Payment is under Processing |
   * | expired | Purchase has Expired. |
   * | error | Transaction has Failed. |
   *
   * ### Response Examples
   *
   * In the response examples you can see instances of both `Paid` and `Error` Status purchases.
   *
   * ### Error Details
   *
   * If there are any issues on the Purchase you can get more details from the `transaction_data.attempts.
   * error` attribute of the response object
   *
   * ### Errors
   *
   * If there are any errors then it'll be in the format of :
   *
   * ``` json
   * {
   * "message": "descriptive error message",
   * "code": "error_code"
   * }
   *
   * ```
   *
   * Please see the Status Code section for further details.
   *
   * @param purchaseId
   * @return Response from the API call
   */
  async getStatus4(
    purchaseId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success10>> {
    const req = this.createRequest('GET');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ purchaseId: [purchaseId, string()] });
    req.header('Content-Type', 'application/json');
    req.appendTemplatePath`/api/v1/purchases/${mapped.purchaseId}`;
    req.authenticate([]);
    return req.callAsJson(success10Schema, requestOptions);
  }

  /**
   * ### 1\. Request Payload Structure
   *
   * Supply a JSON payload with these top‐level objects:
   *
   * - `client` (customer details)
   *
   * - `purchase` (order details)
   *
   * - `paymentMethod` (string, must be `"SPEI"`)
   *
   * - `extraParam` (optional, leave `{}` if unused)
   *
   * - `status` (set to `"created"`)
   *
   * - `brand_id` (your merchant/brand UUID)
   *
   * - Redirect & callback URLs
   *
   *
   * ---
   *
   * ### 2\. Displaying SPEI Instructions to End User
   *
   * Once you parse `payInDetails` from the response:
   *
   * 1. **Show CLABE, Beneficiary & Amount**
   *
   * 2. **Display Expiration**
   *
   * 3. **Show Redirect Path (Optional)**
   *
   * - If you’re using the hosted `checkout_url`, simply redirect customers to it and let Paysecure
   * handle the UI.
   *
   *
   * ---
   *
   * ### 3\. Webhook Handling & Status Transitions
   *
   * 1. **Configure Webhooks**
   *
   * - In Paysecure’s Dashboard, set your `success_callback` and `failure_callback` URLs (one for
   * each event type).
   *
   * 2. **Listen for These Events**:
   *
   * - `payment.paid` – Banco de México has settled the transfer.
   *
   * - `payment.error` – CLABE/amount mismatch or network error.
   *
   * - `payment.expired` – Customer did not pay before `expireInMin`.
   *
   * 3. **Update Order Status**:
   *
   * - On `payment.paid`: mark as paid, trigger fulfillment, send confirmation.
   *
   * - On `payment.error`: alert customer, allow retry or alternative payment.
   *
   * - On `payment.expired`: cancel order.
   *
   * @param body
   * @return Response from the API call
   */
  async payinApIs(
    body: PayinApIsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success11>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ body: [body, payinApIsRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsJson(success11Schema, requestOptions);
  }

  /**
   * To Initiate a payment, the very first call to make is `/purchases` with the required data in the
   * request body.
   *
   * To generate a Purchase, you are required to provide the `Brand ID` (in the request body) and `API
   * key` (in the header) Both can be located in the Dashboard section of your merchant account login.
   *
   * The request body structure is shown on the request body of the example request shown here.
   *
   * The following (see table below) are the mandatory parameters that are required to create a purchase
   * request.
   *
   * ### **Mandatory parameters in the request body:**
   *
   * | **Parameter** | **Notes** |
   * | --- | --- |
   * | client.email | An Identifier for a user, should be a valid email. |
   * | client.city | City of the user. |
   * | client.country | ISO-3166 Country Code. It must be upper case. |
   * | client.stateCode | ISO-3166-2 State Code. Must be in upper case. |
   * | client.street_address | street address of the user. |
   * | client.zip_code | zip code of the user. |
   * | client.phone | Phone number of the user. Country code is mandatory.  <br>Example: +234999999999 |
   * | client.full_name | Full name of the user. Minimum 2 words with atleast 1 character in each word.
   * |
   * | purchase.currency | ISO 4217 code for currency you want to send the transaction in.  <br>eg. This
   * should be 'TZS' for Tanzania  <br>CDF for Congo. |
   * | purchase.products.name |  |
   * | purchase.products.price | Amount in decimal upto 2 places. |
   * | brand_id | Obtain from Dashboard section of your merchant account login. |
   * | success_redirect | URL to send the user if the transactions is successful |
   * | pending_redirect | URL to send the user if the transactions is in progress |
   * | failure_redirect | URL to send the user if the transactions is UNSUCCESSFUL |
   *
   * ## Optional Parameters
   *
   * ### expireInMin
   *
   * This parameter, when passed in the PayIn request, sets the time window within which a customer
   * should make the Interac payment through their bank's app. If a customer doesn't complete the payment
   * within the configured time window, the status of the payment will be marked as 'EXPIRED' in
   * Paysecure.
   *
   * However, in certain cases, a payment made outside of this window could still be successful i.e.
   * customer's account may be debited which would result in inconsistencies among Paysecure's,
   * merchant's and customer's status of the transaction. To avoid such cases it is advised to set the
   * expiry time limit appropriately and advise the customers to make payment within this window. However,
   * if there is an inconsistency between the status at Paysecure and at customer's Bank, the merchant
   * and Paysecure will reconcile the amounts during the settlement.
   *
   * ### merchantRef
   *
   * The `merchantRef` parameter, although not mandatory, is strongly advised for merchants to specify.
   * Its inclusion offers two significant advantages for the merchant:
   *
   * 1. **Prevention of Duplicate Requests:** When a `merchantRef` is utilized, it acts as a unique
   * identifier. This means that if a second purchase request is made using the same `merchantRef`
   * (reference number), the system will recognize it and prevent duplicate transactions from occurring.
   * This prevents unintended or duplicate purchases.
   *
   * 2. **Facilitation of Transaction Retrieval:** In situations where the response from the initial
   * purchase request times out or the 'purchaseId' isn't received, having the `merchantRef` allows the
   * merchant to retrieve detailed transaction information. This ensures they can track and access the
   * specific purchase details related to that reference, even if the immediate response was not received.
   *
   *
   * However, if the merchant does not specify the 'merchantRef' parameter, the platform will
   * automatically assign and use an internal 'purchaseId' as a reference for that transaction.
   *
   * ### paymentMethod
   *
   * The `paymentMethod` parameter identifies which payment solution merchant wants to use to perform a
   * transaction. If parameter is provided, than Paysecure will perform direct payment with the selected
   * payment method instead of loading Paysecure URL.
   *
   * ### Possible Error Messages
   *
   * | **Error Messages** | **Description** |
   * | --- | --- |
   * | Invalid format of Date_of_Birth\[allowed format: yyyy-mm-dd\] |  |
   * | Enter Valid Email |  |
   * | Please submit Valid Alpha2 Country Code Ex:(AF,IN) in \\"country\\" parameter |  |
   * | Please pass Valid State Code |  |
   * | Please pass valid street address in \\"street_address\\" parameter |  |
   * | Please pass valid city name in \\"city\\" parameter |  |
   * | Please pass valid postal Code name in \\"zip_code\\" parameter |  |
   * | You are not Allowed for Live Transaction |  |
   * | Minimum amount is not set for this merchant |  |
   * | success_redirect/failure_redirect/brand_id is missing |  |
   * | brand_id cannot be null |  |
   * | success_redirect cannot be null |  |
   * | failure_redirect cannot be null |  |
   * | Invalid failure_redirect: minimum 10 characters |  |
   * | purchase.products.price cannot be null |  |
   * | purchase.products\[0\].name/purchase.products\[0\].price are missing |  |
   * | Your charges setting is incomplete .Plese Contact to Administrator. |  |
   * | Currency "{curr_name}" is Not Allowed |  |
   * | Transaction amount must be equal or greater to minimum trans amount |  |
   * | Allowed Limit for this card for particular time period has been consumed |  |
   *
   * **Note:** For certain use cases, in addition to long format purchase Id, Paysecure also provides a 7
   * digit unique code for each purchase starting with digit 4, eg 4000001
   *
   * _“purchaseIdShortCode”: “4000013"_
   *
   * @param body
   * @return Response from the API call
   */
  async purchases5(
    body: PurchasesRequest5,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success13>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ body: [body, purchasesRequest5Schema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsJson(success13Schema, requestOptions);
  }

  /**
   * To Initiate a payment, the very first call to make is `/purchases` with the required data in the
   * request body.
   *
   * To generate a Purchase, you are required to provide the `Brand ID` (in the request body) and `API
   * key` (in the header) Both can be located in the Dashboard section of your merchant account login.
   *
   * The request body structure is shown on the request body of the example request shown here.
   *
   * The following (see table below) are the mandatory parameters that are required to create a purchase
   * request.
   *
   * ### **Mandatory parameters in the request body:**
   *
   * | **Parameter** | **Notes** |
   * | --- | --- |
   * | client.email | An Identifier for a user |
   * | client.city | An Identifier for a user |
   * | client.country | ISO-3166 Country Code. It must be upper case.  <br>This should be "CA" for
   * Interac |
   * | client.stateCode | Example “AL”, “XZ”.. Must be in upper case. |
   * | client.street_address |  |
   * | client.zip_code |  |
   * | client.phone |  |
   * | client.full_name |  |
   * | purchase.currency | ISO 4217 code for currency you want to send the transaction in.  <br>This
   * should be 'CAD' for Interac |
   * | purchase.products.name | name of the product or service |
   * | purchase.products.price | Price in decimal format.  <br>example 1:  <br>EUR 5 , should be sent as
   * 5.00  <br>  <br>example 2:  <br>USD 10 and 37 cents , should be sent as 10.37 |
   * | brand_id | Obtain from Dashboard section of your merchant account login. |
   * | extraParam.IsCryptoPurchase | for paymint, send "Yes" |
   * | success_redirect | URL to send the user if the transactions is successful |
   * | pending_redirect | URL to send the user if the transactions is in progress |
   * | failure_redirect | URL to send the user if the transactions is UNSUCCESSFUL |
   *
   * ## Optional Parameters
   *
   * ### expireInMin
   *
   * The `purchase.expireInMin`, when passed in the PayIn request, sets the time window within which a
   * customer should make the Interac payment through their bank's app. If a customer doesn't complete
   * the payment within the configured time window, the status of the payment will be marked as 'EXPIRED'
   * in Paysecure.
   *
   * However, in certain cases, a payment made outside of this window could still be successful i.e.
   * customer's account may be debited which would result in inconsistencies among Paysecure's,
   * merchant's and customer's status of the transaction. To avoid such cases it is advised to set the
   * expiry time limit appropriately and advise the customers to make payment within this window. However,
   * if there is an inconsistency between the status at Paysecure and at customer's Bank, the merchant
   * and Paysecure will reconcile the amounts during the settlement.
   *
   * ### merchantRef
   *
   * The `merchantRef` parameter, although not mandatory, is strongly advised for merchants to specify.
   * Its inclusion offers two significant advantages for the merchant:
   *
   * 1. **Prevention of Duplicate Requests:** When a `merchantRef` is utilized, it acts as a unique
   * identifier. This means that if a second purchase request is made using the same `merchantRef`
   * (reference number), the system will recognize it and prevent duplicate transactions from occurring.
   * This prevents unintended or duplicate purchases.
   *
   * 2. **Facilitation of Transaction Retrieval:** In situations where the response from the initial
   * purchase request times out or the 'purchaseId' isn't received, having the `merchantRef` allows the
   * merchant to retrieve detailed transaction information. This ensures they can track and access the
   * specific purchase details related to that reference, even if the immediate response was not received.
   *
   *
   * However, if the merchant does not specify the 'merchantRef' parameter, the platform will
   * automatically assign and use an internal 'purchaseId' as a reference for that transaction.
   *
   * ### paymentMethod
   *
   * The `paymentMethod` parameter identifies which payment solution merchant wants to use to perform a
   * transaction. If parameter is provided, than Paysecure will perform direct payment with the selected
   * payment method instead of loading Paysecure URL.
   *
   * ### Possible Error Messages
   *
   * | **Error Messages** | **Description** |
   * | --- | --- |
   * | Invalid format of Date_of_Birth\[allowed format: yyyy-mm-dd\] |  |
   * | Enter Valid Email |  |
   * | Please submit Valid Alpha2 Country Code Ex:(AF,IN) in \\"country\\" parameter |  |
   * | Please pass Valid State Code |  |
   * | Please pass valid street address in \\"street_address\\" parameter |  |
   * | Please pass valid city name in \\"city\\" parameter |  |
   * | Please pass valid postal Code name in \\"zip_code\\" parameter |  |
   * | You are not Allowed for Live Transaction |  |
   * | Minimum amount is not set for this merchant |  |
   * | success_redirect/failure_redirect/brand_id is missing |  |
   * | brand_id cannot be null |  |
   * | success_redirect cannot be null |  |
   * | failure_redirect cannot be null |  |
   * | Invalid failure_redirect: minimum 10 characters |  |
   * | purchase.products.price cannot be null |  |
   * | purchase.products\[0\].name/purchase.products\[0\].price are missing |  |
   * | Your charges setting is incomplete .Plese Contact to Administrator. |  |
   * | Currency "{curr_name}" is Not Allowed |  |
   * | Transaction amount must be equal or greater to minimum trans amount |  |
   * | Allowed Limit for this card for particular time period has been consumed |  |
   *
   * **Note:** For certain use cases, in addition to long format purchase Id, Paysecure also provides a 7
   * digit unique code for each purchase starting with digit 4, eg 4000001
   *
   * _“purchaseIdShortCode”: “4000013"_
   *
   * @param body
   * @return Response from the API call
   */
  async purchases6(
    body: PurchasesRequest8,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PurchaseSuccess>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ body: [body, purchasesRequest8Schema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsJson(purchaseSuccessSchema, requestOptions);
  }

  /**
   * This API tells you about all the details of a purchase (PayIn), including its history
   *
   * **Note:** With respect to bank transfers, the purchase request is synonymous with the PayIn request.
   *
   * ### Mandatory
   *
   * you need to pass the `PurchaseID` in the API URL
   *
   * ### Possible Value of Status
   *
   * | **Status** | **Notes** |
   * | --- | --- |
   * | paid | Transaction Successful |
   * | payment_in_process | Payment is under Processing |
   * | expired | Purchase has Expired. |
   * | error | Transaction has Failed. |
   *
   * ### Response Examples
   *
   * In the response examples you can see instances of both `Paid` and `Error` Status purchases.
   *
   * ### Error Details
   *
   * If there are any issues on the Purchase you can get more details from the `transaction_data.attempts.
   * error` attribute of the response object
   *
   * ### Errors
   *
   * If there are any errors then it'll be in the format of :
   *
   * ``` json
   * {
   * "message": "descriptive error message",
   * "code": "error_code"
   * }
   *
   * ```
   *
   * Please see the Status Code section for further details.
   *
   * @param purchaseId
   * @return Response from the API call
   */
  async getStatus5(
    purchaseId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PurchasesSuccess1>> {
    const req = this.createRequest('GET');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ purchaseId: [purchaseId, string()] });
    req.header('Content-Type', 'application/json');
    req.appendTemplatePath`/api/v1/purchases/${mapped.purchaseId}`;
    req.authenticate([]);
    return req.callAsJson(purchasesSuccess1Schema, requestOptions);
  }

  /**
   * The API endpoint [/v1/purchases](https://api.paysecure.net/api/v1/purchases) is a POST request used
   * to create a new purchase. The request body should contain the client information including email,
   * address, and phone, the purchase details such as currency and products, the payment method, and
   * various callback and redirect URLs.
   *
   * **Final Steps for Payin APIs Integration**
   *
   * 1. **Set Up Authentication & Headers**
   *
   * - **Endpoint:** POST >
   *
   * - **Headers (mandatory):**
   *
   * - Authorization: Bearer {LIVE_API_KEY}
   *
   * - Content-Type: application/json
   *
   * 2. **Construct the Request Payload**
   *
   * - Build a JSON body with:
   *
   * - client object (KYC/AML fields):
   *
   * - email
   *
   * - country (ISO-2 code)
   *
   * - city
   *
   * - stateCode
   *
   * - street_address
   *
   * - zip_code
   *
   * - phone
   *
   * - purchase object:
   *
   * - currency
   *
   * - products array (≥1 item with name and price)
   *
   * - **Top-level fields:**
   *
   * - paymentMethod (e.g., "NEOSURF")
   *
   * - brand_id (your Brand UUID)
   *
   * - success_redirect (HTTPS URL after success)
   *
   * - failure_redirect (HTTPS URL after failure)
   *
   * 3. **Invoke the Payin APIs**
   *
   * - Send the JSON payload to [https://api.paysecure.net/v1/purchases](https://api.paysecure.
   * net/v1/purchases)
   *
   * - Expect 200 OK with a response containing:
   *
   * - purchaseId
   *
   * - status = PENDING
   *
   * - checkout_url
   *
   * 4. **Extract Key References**
   *
   * - purchaseId (e.g., 68394314d3c4ef68d6cbb58c): for tracking/reconciliation.
   *
   * - checkout_url (e.g., [https://api.paysecure.net/payments/68394314d3c4ef68d6cbb58c/](https://api.
   * paysecure.net/payments/68394314d3c4ef68d6cbb58c/)): redirect here so the customer can complete
   * voucher entry.
   *
   * - Redirect Customer `window.location.href = response.checkout_url;` Customer enters their 10-
   * digit Neosurf voucher on redirected page.
   *
   * 5. **Listen for Webhook Notifications**
   *
   * - Ensure your endpoint handles:
   *
   * - purchase.paid
   *
   * - purchase.error
   *
   * - purchase.cancelled
   *
   * - Each payload will include purchaseId, status, amount, currency, etc.
   *
   *
   * ### Mandatory Parameters
   *
   * | Field | Type | Description |
   * | --- | --- | --- |
   * | **Authorization** | string | `Bearer {API_KEY}` (replace with your live or staging API key). |
   * | **Content-Type** | string | Must be `application/json`. |
   * | **client.email** | string | Customer’s email (e.g., `example22@paysecure.net`). |
   * | **client.country** | string | ISO‐3166 Alpha-2 code (e.g., `IN`). |
   * | **client.city** | string | City name or code (e.g., `123`). |
   * | **client.stateCode** | string | State or province code (two letters where possible, e.g., `ca`).
   * |
   * | **client.street_address** | string | Street address line (e.g., `test test`). |
   * | **client.zip_code** | string | Postal/ZIP code (e.g., `234567`). |
   * | **client.phone** | string | Customer’s phone number (E.164 recommended, e.g., `9999999999`). |
   * | **purchase.currency** | string | Currency code (e.g., `AUD`). |
   * | **purchase.products** | array | Must contain at least one object with `name` and `price`. |
   * | └─ **products.name** | string | Product name or SKU (e.g., `dk`). |
   * | └─ **products.price** | string | Unit price in major currency units (e.g., `"1"` = 1.00 AUD). |
   * | **paymentMethod** | string | Payment rail code (e.g., `NEOSURF`). |
   * | **brand_id** | string | Live or staging Brand UUID (e.g., `c4003b2c-22d4-4dc1-ad0c-c6b54f8c9636`).
   * |
   * | **success_redirect** | string | HTTPS URL to redirect after successful payment (e.g., `https:
   * //your.success.redirect.com`). |
   * | **failure_redirect** | string | HTTPS URL to redirect after failed payment (e.g., `https://your.
   * failure.redirect.com`). |
   *
   * @param body
   * @return Response from the API call
   */
  async purchases7(
    body: PurchasesRequest9,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success16>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ body: [body, purchasesRequest9Schema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsJson(success16Schema, requestOptions);
  }

  /**
   * ### Purchase API Endpoint
   *
   * This endpoint allows you to create a new purchase transaction. It processes the purchase details,
   * including client information, product details, and payment method, and returns the result of the
   * transaction.
   *
   * #### Request Format
   *
   * - **Method**: POST
   *
   * - **URL**: `https://api.paysecure.net/api/v1/purchases`
   *
   * - **Request Body**: The request should be in JSON format and must include the following structure:
   *
   *
   * #### Response Structure
   *
   * The response will contain the result of the purchase transaction. The structure of the response may
   * include:
   *
   * - **status**: Indicates the success or failure of the transaction.
   *
   * - **message**: A descriptive message regarding the transaction status.
   *
   * - **transaction_id**: Unique identifier for the transaction (if successful).
   *
   * - **redirect_url**: URL to redirect the user based on the transaction result.
   *
   *
   * Make sure to handle the response appropriately based on the status returned.
   *
   * @param body
   * @return Response from the API call
   */
  async purchases9(
    body: PurchasesRequest3,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success17>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ body: [body, purchasesRequest3Schema] });
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsJson(success17Schema, requestOptions);
  }

  /**
   * To Initiate a payment, the very first call to make is `/purchases` with the required data in the
   * request body.
   *
   * To generate a Purchase, you are required to provide the `Brand ID` (in the request body) and `API
   * key` (in the header) Both can be located in the Dashboard section of your merchant account login.
   *
   * The request body structure is shown on the request body of the example request shown here.
   *
   * ### 💡 Key Fields Explained
   *
   * | Field | Description |
   * | --- | --- |
   * | `paymentMethod` | Always use `"CRYPTO-BRIDGE"` to trigger this payment method |
   * | `currency` | The fiat currency for the order (e.g., USD, EUR). You will be paid in crypto but this
   * defines how much the customer will pay |
   * | `products` | One or more items being sold, with name and price |
   * | `extraParam.clientFee` | Optional: A custom fee you (the merchant) want to charge — shown to the
   * user at checkout |
   * | `extraParam.toAddress` | Optional.  <br>Merchant can provide the list of wallet addresses, where
   * they want to collect the deposit from the user. Can pass multiple addresses. |
   * | `extraParam.toAddress.symbol` | The symbol of the digital asset.  <br>Example: ETH, USDC etc.
   * <br>  <br>Possible Values:  <br>AAVE, ADA, APE, APT, ARB, AVAX, BLAST, BLUR, BNB, BTC, BUSD, CAKE,
   * CASH, CRO, DAI, DEXE, DEVNETSOL, DOGE, ENA, ETH, EURC, FARTCOIN, FDUSD, FORM, FTM, GRT, HYPE, IMX,
   * INJ, LDO, LEO, LINK, LTC, MANA, MATIC, MKR, MNT, MON, OP, PAXG, PENGU, POL, PYUSD, QNT, RLUSD, RNDR,
   * S, SAND, SEPOLIAETH, SHIB, SNX, SOL, SUI, TON, TRUMP, TRX, TUSD, UNI, USD1, USD₮0, USDC, USDD, USDG,
   * USDH, USDP, USDT, VIRTUAL, WAVAX, WBNB, WBTC, WETH, WHYPE, WIF, WMATIC, WMON, XLM, XRP |
   * | `extraParam.toAddress.networkName` | The network of the token.  <br>Example: ETHEREUM, POLYGON etc.
   * <br>  <br>Possible values:  <br>ETHEREUM, POLYGON, BSC, ARBITRUM, OPTIMISM, BASE, AVALANCHEC,
   * BLAST, HYPEREVM, SOLANA, BITCOIN, TRON, LITECOIN, DOGECOIN, RIPPLE, APTOS, CARDANO, STELLAR, SUI,
   * TON, SONIC, INJECTIVE, AVALANCHEX |
   * | `extraParam.toAddress.address` | The address to send the asset to. |
   * | `success_redirect` / `success_redirect` / `failure_redirect` | Where the user should land after
   * completing or canceling the payment or if the transaction is in pending state. |
   * | `success_callback` / `failure_callback` | Your backend URL to receive transaction status via
   * webhook. |
   * | `client` | Customer billing info |
   *
   * @param body
   * @return Response from the API call
   */
  async purchases8(
    body: PurchasesRequest11,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Purchases1>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ body: [body, purchasesRequest11Schema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsJson(purchases1Schema, requestOptions);
  }

  /**
   * To Initiate a payment, the very first call to make is `/purchases` with the required data in the
   * request body.
   *
   * To generate a Purchase, you are required to provide the `Brand ID` (in the request body) and `API
   * key` (in the header) Both can be located in the Dashboard section of your merchant account login.
   *
   * The request body structure is shown on the request body of the example request shown here.
   *
   * The following (see table below) are the mandatory parameters that are required to create a purchase
   * request.
   *
   * ### **Mandatory parameters in the request body:**
   *
   * | Fields | **Notes** |
   * | --- | --- |
   * | client.email | The customer's email. |
   * | client.city | The customer's city. |
   * | client.country | ISO-3166 Country Code. Must be upper case. Example “SG” (Alpha2) |
   * | client.stateCode | Example “AL”, “XZ”. Must be in upper case. |
   * | Client.street_address | The customer's address. |
   * | client.zip_code | The customer's ZIP or postal code. If country=US, zip format must be NNNNN or
   * NNNNN-NNNN. |
   * | purchase.currency | ISO 4217 code for currency you want to send the transaction in.  <br>
   * <br>Please note, the currency has to be enabled by the account manager for your account. |
   * | purchase.products | An object which contains the list of products which the customer is buying. |
   * | purchase.products.name | The name of the product. |
   * | purchase.products.price | Price in decimal format.  <br>example 1:  <br>EUR 5 , should be sent as
   * 5.00  <br>  <br>example 2:  <br>USD 10 and 37 cents , should be sent as 10.37 |
   * | brand_id | Obtain from Dashboard section of your merchant account login. |
   * | success_redirect | URL to send the user if the transactions is successful. |
   * | pending_redirect | URL to send the user if the transactions is in pending. |
   * | failure_redirect | URL to send the user if the transactions is unsuccessful. |
   *
   * ## Optional Parameters
   *
   * ### merchantRef
   *
   * The `merchantRef` parameter, although not mandatory, is strongly advised for merchants to specify.
   * Its inclusion offers two significant advantages for the merchant:
   *
   * 1. **Prevention of Duplicate Requests:** When a `merchantRef` is utilized, it acts as a unique
   * identifier. This means that if a second purchase request is made using the same `merchantRef`
   * (reference number), the system will recognize it and prevent duplicate transactions from occurring.
   * This prevents unintended or duplicate purchases.
   *
   * 2. **Facilitation of Transaction Retrieval:** In situations where the response from the initial
   * purchase request times out or the 'purchaseId' isn't received, having the `merchantRef` allows the
   * merchant to retrieve detailed transaction information. This ensures they can track and access the
   * specific purchase details related to that reference, even if the immediate response was not received.
   *
   *
   * However, if the merchant does not specify the 'merchantRef' parameter, the platform will
   * automatically assign and use an internal 'purchaseId' as a reference for that transaction.
   *
   * ### Digital Signature (Optional Parameter) :
   *
   * To ensure authenticity and non-repudiation of the the pay in request, there is an option to
   * digitally sign the pay in request by using the merchant's public key.
   *
   * **Public key generation :-**
   *
   * <img src="https://content.pstmn.io/1e198415-45ef-49d9-9dbf-8270bb853dab/aW1hZ2UucG5n" width="1570"
   * height="743">
   *
   * **Signature generation :-**
   *
   * This digitial signature is generated by encrypting the following elements of the pay in request:
   * Plaintext= Client.email+purchase.currency+ purchase.products.price+brand_id
   *
   * **Example of encrypt plaintext with public key in java:-**
   *
   * ``` java
   * private String encryptData(String plaintext, PublicKey publicKey) throws Exception {
   * Cipher cipher = Cipher.getInstance("RSA");
   * cipher.init(Cipher.ENCRYPT_MODE, publicKey);
   * byte[] encryptedbytes = cipher.doFinal(message.getBytes());
   * return new String(Base64.getEncoder * ().encode(encryptedbytes));
   * }
   *
   * ```
   *
   * ### paymentMethod
   *
   * The `paymentMethod` parameter identifies which payment solution merchant wants to use to perform a
   * transaction. If parameter is provided, than Paysecure will perform direct payment with the selected
   * payment method instead of loading Paysecure URL.
   *
   * ### Possible Error Messages
   *
   * | **Error Messages** | **Description** |
   * | --- | --- |
   * | Invalid format of Date_of_Birth\[allowed format: yyyy-mm-dd\] |  |
   * | Enter Valid Email |  |
   * | Please submit Valid Alpha2 Country Code Ex:(AF,IN) in \\"country\\" parameter |  |
   * | Please pass Valid State Code |  |
   * | Please pass valid street address in \\"street_address\\" parameter |  |
   * | Please pass valid city name in \\"city\\" parameter |  |
   * | Please pass valid postal Code name in \\"zip_code\\" parameter |  |
   * | You are not Allowed for Live Transaction |  |
   * | Minimum amount is not set for this merchant |  |
   * | success_redirect/failure_redirect/brand_id is missing |  |
   * | brand_id cannot be null |  |
   * | success_redirect cannot be null |  |
   * | failure_redirect cannot be null |  |
   * | Invalid failure_redirect: minimum 10 characters |  |
   * | purchase.products.price cannot be null |  |
   * | purchase.products\[0\].name/purchase.products\[0\].price are missing |  |
   * | Your charges setting is incomplete .Plese Contact to Administrator. |  |
   * | Currency "{curr_name}" is Not Allowed |  |
   * | Transaction amount must be equal or greater to minimum trans amount |  |
   * | Allowed Limit for this card for particular time period has been consumed |  |
   *
   * **Note:** For certain use cases, in addition to long format purchase Id, Paysecure also provides a 7
   * digit unique code for each purchase starting with digit 4, eg 4000001
   *
   * _“purchaseIdShortCode”: “4000013"_
   *
   * @param body
   * @return Response from the API call
   */
  async createPurchase1(
    body: CreatePurchaseRequest2,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      body: [body, createPurchaseRequest2Schema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsText(requestOptions);
  }

  /**
   * This API tells you about all the details of a purchase (PayIn), including its history
   *
   * **Note:** With respect to bank transfers, the purchase request is synonymous with the PayIn request.
   *
   * ### Mandatory
   *
   * you need to pass the `PurchaseID` in the API URL
   *
   * ### Possible Value of Status
   *
   * | **Status** | **Notes** |
   * | --- | --- |
   * | paid | Transaction Successful |
   * | payment_in_process | Payment is under Processing |
   * | expired | Purchase has Expired. |
   * | error | Transaction has Failed. |
   *
   * ### Response Examples
   *
   * In the response examples you can see instances of both `Paid` and `Error` Status purchases.
   *
   * ### Error Details
   *
   * If there are any issues on the Purchase you can get more details from the `transaction_data.attempts.
   * error` attribute of the response object
   *
   * ### Errors
   *
   * If there are any errors then it'll be in the format of :
   *
   * ``` json
   * {
   * "message": "descriptive error message",
   * "code": "error_code"
   * }
   *
   * ```
   *
   * Please see the Status Code section for further details.
   *
   * @param purchaseId
   * @return Response from the API call
   */
  async getStatus6(
    purchaseId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Success22>> {
    const req = this.createRequest('GET');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ purchaseId: [purchaseId, string()] });
    req.header('Content-Type', 'application/json');
    req.appendTemplatePath`/api/v1/purchases/${mapped.purchaseId}`;
    req.authenticate([]);
    return req.callAsJson(success22Schema, requestOptions);
  }
}
