/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreatePurchaseRequest1,
  createPurchaseRequest1Schema,
} from '../models/createPurchaseRequest1.js';
import {
  PurchasesSuccess5,
  purchasesSuccess5Schema,
} from '../models/purchasesSuccess5.js';
import {
  PurchaseSucess,
  purchaseSucessSchema,
} from '../models/purchaseSucess.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class PayinApi extends BaseApi {
  /**
   * ### **Payin API**
   *
   * <img src="https://content.pstmn.io/e448df41-3cb5-4b2a-9dc5-f961d9048bff/dW5uYW1lZC0yLnBuZw==" alt=""
   * height="301" width="800">
   *
   * **Integration Steps:** To integrate Virtual Account payments with Paysecure, follow these steps:
   *
   * 1. **Enable Virtual Account in Paysecure**: Sign up with Paysecure and ensure the Virtual Account
   * payment method is enabled for your merchant account. Get your API keys for authentication (test and
   * live).
   *
   * 2. **Configure Webhooks**: Set up Paysecure webhooks (e.g. transaction.paid, transaction.failed) so
   * your system is notified of payment status changes.
   *
   * 3. **Implement PayIn** (Customer Payments): In your checkout flow, allow the customer to choose
   * Virtual Account and then call Paysecure’s PayIn API (e.g. POST /purchases ) with parameters such as
   * amount, currency and paymentMethod=VIRTUAL-ACCOUNT. To generate a Purchase, you are required to
   * provide the Brand ID (in the request body) and API key (in the header). Both can be located in the
   * Dashboard section of your merchant account login.
   *
   * @param body
   * @return Response from the API call
   */
  async createPurchase(
    body: CreatePurchaseRequest1,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PurchaseSucess>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      body: [body, createPurchaseRequest1Schema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.callAsJson(purchaseSucessSchema, requestOptions);
  }

  /**
   * This API tells you about all the details of a purchase (PayIn), including its history
   *
   * **Note:** With respect to bank transfers, the purchase request is synonymous with the PayIn request.
   *
   * ### Mandatory
   *
   * you need to pass the `PurchaseID` in the API URL
   *
   * ### Possible Value of Status
   *
   * | **Status** | **Notes** |
   * | --- | --- |
   * | paid | Transaction Successful |
   * | payment_in_process | Payment is under Processing |
   * | expired | Purchase has Expired. |
   * | error | Transaction has Failed. |
   *
   * ### Response Examples
   *
   * In the response examples you can see instances of both `Paid` and `Error` Status purchases.
   *
   * ### Error Details
   *
   * If there are any issues on the Purchase you can get more details from the `transaction_data.attempts.
   * error` attribute of the response object
   *
   * ### Errors
   *
   * If there are any errors then it'll be in the format of :
   *
   * ``` json
   * {
   * "message": "descriptive error message",
   * "code": "error_code"
   * }
   *
   * ```
   *
   * Please see the Status Code section for further details.
   *
   * @param purchaseId
   * @return Response from the API call
   */
  async getStatus(
    purchaseId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string>> {
    const req = this.createRequest('GET');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ purchaseId: [purchaseId, string()] });
    req.header('Content-Type', 'application/json');
    req.appendTemplatePath`/api/v1/purchases/${mapped.purchaseId}`;
    req.authenticate([]);
    return req.callAsText(requestOptions);
  }

  /**
   * To Initiate a payment, the very first call to make is `/purchases` with the required data in the
   * request body.
   *
   * To generate a Purchase, you are required to provide the `Brand ID` (in the request body) and `API
   * key` (in the header) Both can be located in the Dashboard section of your merchant account login.
   *
   * The request body structure is shown on the request body of the example request shown here.
   *
   * The following (see table below) are the mandatory parameters that are required to create a purchase
   * request.
   *
   * ### **Mandatory parameters in the request body:**
   *
   * | **Parameter** | **Notes** |
   * | --- | --- |
   * | client.email | An Identifier for a user |
   * | client.city |  |
   * | client.country | ISO-3166 Country Code. It must be upper case.  <br>This should be "IN" for India
   * |
   * | client.stateCode | Example “AL”, “XZ”.. Must be in upper case. |
   * | client.street_address |  |
   * | client.zip_code |  |
   * | client.full_name |  |
   * | purchase.currency | ISO 4217 code for currency you want to send the transaction in. |
   * | purchase.products.name |  |
   * | purchase.products.price | Price in decimal format.  <br>example 1:  <br>INR 5 , should be sent as
   * 10.00 |
   * | brand_id | Obtain from Dashboard section of your merchant account login. |
   * | success_redirect | URL to send the user if the transactions is successful |
   * | failure_redirect | URL to send the user if the transactions is UNSUCCESSFUL |
   *
   * ## Optional Parameters
   *
   * ### expireInMin
   *
   * This parameter, when passed in the PayIn request, sets the time window within which a customer
   * should make the Interac payment through their bank's app. If a customer doesn't complete the payment
   * within the configured time window, the status of the payment will be marked as 'EXPIRED' in
   * Paysecure.
   *
   * However, in certain cases, a payment made outside of this window could still be successful i.e.
   * customer's account may be debited which would result in inconsistencies among Paysecure's,
   * merchant's and customer's status of the transaction. To avoid such cases it is advised to set the
   * expiry time limit appropriately and advise the customers to make payment within this window. However,
   * if there is an inconsistency between the status at Paysecure and at customer's Bank, the merchant
   * and Paysecure will reconcile the amounts during the settlement.
   *
   * ### merchantRef
   *
   * The `merchantRef` parameter, although not mandatory, is strongly advised for merchants to specify.
   * Its inclusion offers two significant advantages for the merchant:
   *
   * 1. **Prevention of Duplicate Requests:** When a `merchantRef` is utilized, it acts as a unique
   * identifier. This means that if a second purchase request is made using the same `merchantRef`
   * (reference number), the system will recognize it and prevent duplicate transactions from occurring.
   * This prevents unintended or duplicate purchases.
   *
   * 2. **Facilitation of Transaction Retrieval:** In situations where the response from the initial
   * purchase request times out or the 'purchaseId' isn't received, having the `merchantRef` allows the
   * merchant to retrieve detailed transaction information. This ensures they can track and access the
   * specific purchase details related to that reference, even if the immediate response was not received.
   *
   *
   * However, if the merchant does not specify the 'merchantRef' parameter, the platform will
   * automatically assign and use an internal 'purchaseId' as a reference for that transaction.
   *
   * ### paymentMethod
   *
   * The `paymentMethod` parameter identifies which payment solution merchant wants to use to perform a
   * transaction. If parameter is provided, than Paysecure will perform direct payment with the selected
   * payment method instead of loading Paysecure URL.
   *
   * ### Possible Error Messages
   *
   * | **Error Messages** | **Description** |
   * | --- | --- |
   * | Invalid format of Date_of_Birth\[allowed format: yyyy-mm-dd\] |  |
   * | Enter Valid Email |  |
   * | Please submit Valid Alpha2 Country Code Ex:(AF,IN) in \\"country\\" parameter |  |
   * | Please pass Valid State Code |  |
   * | Please pass valid street address in \\"street_address\\" parameter |  |
   * | Please pass valid city name in \\"city\\" parameter |  |
   * | Please pass valid postal Code name in \\"zip_code\\" parameter |  |
   * | You are not Allowed for Live Transaction |  |
   * | Minimum amount is not set for this merchant |  |
   * | success_redirect/failure_redirect/brand_id is missing |  |
   * | brand_id cannot be null |  |
   * | success_redirect cannot be null |  |
   * | failure_redirect cannot be null |  |
   * | Invalid failure_redirect: minimum 10 characters |  |
   * | purchase.products.price cannot be null |  |
   * | purchase.products\[0\].name/purchase.products\[0\].price are missing |  |
   * | Your charges setting is incomplete .Plese Contact to Administrator. |  |
   * | Currency "{curr_name}" is Not Allowed |  |
   * | Transaction amount must be equal or greater to minimum trans amount |  |
   * | Allowed Limit for this card for particular time period has been consumed |  |
   *
   * **Note:** For certain use cases, in addition to long format purchase Id, Paysecure also provides a 7
   * digit unique code for each purchase starting with digit 4, eg 4000001
   *
   * _“purchaseIdShortCode”: “4000013"_
   *
   * @param body
   * @return Response from the API call
   */
  async createPurchase1(
    body: CreatePurchaseRequest1,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/api/v1/purchases');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      body: [body, createPurchaseRequest1Schema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.authenticate([]);
    return req.call(requestOptions);
  }

  /**
   * This API tells you about all the details of a purchase (PayIn), including its history
   *
   * **Note:** With respect to bank transfers, the purchase request is synonymous with the PayIn request.
   *
   * ### Mandatory
   *
   * you need to pass the `PurchaseID` in the API URL
   *
   * ### Possible Value of Status
   *
   * | **Status** | **Notes** |
   * | --- | --- |
   * | paid | Transaction Successful |
   * | payment_in_process | Payment is under Processing |
   * | expired | Purchase has Expired. |
   * | error | Transaction has Failed. |
   *
   * ### Response Examples
   *
   * In the response examples you can see instances of both `Paid` and `Error` Status purchases.
   *
   * ### Error Details
   *
   * If there are any issues on the Purchase you can get more details from the `transaction_data.attempts.
   * error` attribute of the response object
   *
   * ### Errors
   *
   * If there are any errors then it'll be in the format of :
   *
   * ``` json
   * {
   * "message": "descriptive error message",
   * "code": "error_code"
   * }
   *
   * ```
   *
   * Please see the Status Code section for further details.
   *
   * @param purchaseId
   * @return Response from the API call
   */
  async getStatus1(
    purchaseId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PurchasesSuccess5>> {
    const req = this.createRequest('GET');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({ purchaseId: [purchaseId, string()] });
    req.header('Content-Type', 'application/json');
    req.appendTemplatePath`/api/v1/purchases/${mapped.purchaseId}`;
    req.authenticate([]);
    return req.callAsJson(purchasesSuccess5Schema, requestOptions);
  }
}
