/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ApprovePayoutWithRemarksRequest,
  approvePayoutWithRemarksRequestSchema,
} from '../models/approvePayoutWithRemarksRequest.js';
import {
  RejectPayoutWithRemarksRequest,
  rejectPayoutWithRemarksRequestSchema,
} from '../models/rejectPayoutWithRemarksRequest.js';
import { number, optional, string, unknown } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class PayoutManualReviewApi extends BaseApi {
  /**
   * @param pageNo
   * @param pageSize
   * @param status
   * @param timezone
   * @param startDate
   * @param endDate
   * @param paymentMethod
   * @param email
   * @param customerSegment
   * @return Response from the API call
   */
  async listPayouts(
    pageNo: number,
    pageSize: number,
    status: string,
    timezone: string,
    startDate: string,
    endDate: string,
    paymentMethod: string,
    email: string,
    customerSegment: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest(
      'GET',
      '/api/v1/external/transactions/payout/list'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      pageNo: [pageNo, number()],
      pageSize: [pageSize, number()],
      status: [status, string()],
      timezone: [timezone, string()],
      startDate: [startDate, string()],
      endDate: [endDate, string()],
      paymentMethod: [paymentMethod, string()],
      email: [email, string()],
      customerSegment: [customerSegment, string()],
    });
    req.query('page_no', mapped.pageNo);
    req.query('page_size', mapped.pageSize);
    req.query('status', mapped.status);
    req.query('timezone', mapped.timezone);
    req.query('start_date', mapped.startDate);
    req.query('end_date', mapped.endDate);
    req.query('payment_method', mapped.paymentMethod);
    req.query('email', mapped.email);
    req.query('customer_segment', mapped.customerSegment);
    req.authenticate([]);
    return req.call(requestOptions);
  }

  /**
   * @param action
   * @param body
   * @param payoutId
   * @return Response from the API call
   */
  async approvePayout(
    action: string,
    body: unknown,
    payoutId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      action: [action, string()],
      body: [body, optional(unknown())],
      payoutId: [payoutId, string()],
    });
    req.header('Content-Type', 'application/json');
    req.query('action', mapped.action);
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/payouts/${mapped.payoutId}/action`;
    req.authenticate([]);
    return req.call(requestOptions);
  }

  /**
   * @param action
   * @param body
   * @param payoutId
   * @return Response from the API call
   */
  async approvePayoutWithRemarks(
    action: string,
    body: ApprovePayoutWithRemarksRequest,
    payoutId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      action: [action, string()],
      body: [body, approvePayoutWithRemarksRequestSchema],
      payoutId: [payoutId, string()],
    });
    req.header('Content-Type', 'application/json');
    req.query('action', mapped.action);
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/payouts/${mapped.payoutId}/action`;
    req.authenticate([]);
    return req.call(requestOptions);
  }

  /**
   * @param action
   * @param body
   * @param payoutId
   * @return Response from the API call
   */
  async rejectPayout(
    action: string,
    body: unknown,
    payoutId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      action: [action, string()],
      body: [body, optional(unknown())],
      payoutId: [payoutId, string()],
    });
    req.header('Content-Type', 'application/json');
    req.query('action', mapped.action);
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/payouts/${mapped.payoutId}/action`;
    req.authenticate([]);
    return req.call(requestOptions);
  }

  /**
   * @param action
   * @param body
   * @param payoutId
   * @return Response from the API call
   */
  async rejectPayoutWithRemarks(
    action: string,
    body: RejectPayoutWithRemarksRequest,
    payoutId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      action: [action, string()],
      body: [body, rejectPayoutWithRemarksRequestSchema],
      payoutId: [payoutId, string()],
    });
    req.header('Content-Type', 'application/json');
    req.query('action', mapped.action);
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/payouts/${mapped.payoutId}/action`;
    req.authenticate([]);
    return req.call(requestOptions);
  }
}
