/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  RefundPending1,
  refundPending1Schema,
} from '../models/refundPending1.js';
import { BaseApi } from './baseApi.js';
import { RefundError } from '../errors/refundError.js';

export class RefundApi extends BaseApi {
  /**
   * This API is used to initate refund of the purchases that have status as `PAID`
   *
   * Once the refund has been initiated, the status of the purchase would become `REFUND_IN_PROCESS` and
   * once the refund has been approved by the bank, the status woud become `REFUNDED`
   *
   * Purchase ID is **mandatory** for this API.
   *
   * If due to some reason, the refund has failed, the status would again become `PAID`
   *
   * ### Response Examples
   *
   * In the response examples you can see instances of both `successful` and `unsuccessful` in refund of
   * purchases.
   *
   * @return Response from the API call
   */
  async refund(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RefundPending1>> {
    const req = this.createRequest(
      'GET',
      '/api/v1/purchases/657af976c3fceb7beb30eeb4/refund'
    );
    req.baseUrl('Server 3');
    req.header('Content-Type', 'application/json');
    req.throwOn(400, RefundError, 'Bad Request');
    req.authenticate([]);
    return req.callAsJson(refundPending1Schema, requestOptions);
  }
}
