/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { boolean, number, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { Success42Error } from '../errors/success42Error.js';
import { Success44Error } from '../errors/success44Error.js';

export class TransactionReportingApi extends BaseApi {
  /**
   * Fetches a paginated list of transactions. This endpoint is optimized for high-volume retrieval and
   * returns a summary view of each transaction (ID and Status).
   *
   * #### **Important Path Params to consider:**
   *
   * | **Fields** | **Description** |
   * | --- | --- |
   * | page_no | The index number of the page to retrieve.  <br>Zero-based indexing: The first page is 0,
   * the second is 1, etc.  <br>Example: To get the third page of results, send page_no=2 |
   * | page_size | The number of records to return per page.  <br>Minimum: 1  <br>Maximum: 100 (or
   * whatever your API limit is).  <br>Usage: A larger page_size reduces the number of API calls but
   * increases payload size. |
   * | transaction_id | If you want to filter with a specific transaction id. Multiple ids are not
   * supported.  <br>If a transaction id is passed, it has the highest priority. All the below mentioned
   * filters are ommitted. |
   * | start_date | If you want to filter between 2 dates.  <br>Format: 2026-01-07 16:12:00 +05:30
   * <br>Base timezone is in UTC. |
   * | end_date | If you want to filter between 2 dates  <br>Format: 2026-01-07 16:12:00 +05:30  <br>Base
   * timezone is in UTC. |
   * | last_updated_start | If you want to filter with the last updated date of a transaction.
   * <br>Format: 2026-01-07 16:12:00 +05:30  <br>Base timezone is in UTC. |
   * | last_updated_end | If you want to filter with the last updated date of a transaction.  <br>Format:
   * 2026-01-07 16:12:00 +05:30  <br>Base timezone is in UTC. |
   * | customer_id | If you want to filter with a specific customer id. Multiple ids are not supported.
   * |
   * | status | If you want to filter with the status. |
   * | currency | If you want to filter with the currency. |
   *
   * @param pageNo
   * @param pageSize
   * @param transactionId
   * @param startDate
   * @param endDate
   * @param lastUpdatedStart
   * @param lastUpdatedEnd
   * @param customerId
   * @param status
   * @param currency
   * @param isSandbox
   * @param brandId
   * @return Response from the API call
   */
  async listTransactions(
    pageNo: number,
    pageSize: number,
    transactionId: string,
    startDate: string,
    endDate: string,
    lastUpdatedStart: string,
    lastUpdatedEnd: string,
    customerId: string,
    status: string,
    currency: string,
    isSandbox: boolean,
    brandId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/api/v1/external/transactions/list');
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      pageNo: [pageNo, number()],
      pageSize: [pageSize, number()],
      transactionId: [transactionId, string()],
      startDate: [startDate, string()],
      endDate: [endDate, string()],
      lastUpdatedStart: [lastUpdatedStart, string()],
      lastUpdatedEnd: [lastUpdatedEnd, string()],
      customerId: [customerId, string()],
      status: [status, string()],
      currency: [currency, string()],
      isSandbox: [isSandbox, boolean()],
      brandId: [brandId, string()],
    });
    req.header('BrandId', mapped.brandId);
    req.query('page_no', mapped.pageNo);
    req.query('page_size', mapped.pageSize);
    req.query('transaction_id', mapped.transactionId);
    req.query('start_date', mapped.startDate);
    req.query('end_date', mapped.endDate);
    req.query('last_updated_start', mapped.lastUpdatedStart);
    req.query('last_updated_end', mapped.lastUpdatedEnd);
    req.query('customer_id', mapped.customerId);
    req.query('status', mapped.status);
    req.query('currency', mapped.currency);
    req.query('is_sandbox', mapped.isSandbox);
    req.throwOn(400, Success42Error, 'Bad Request');
    req.authenticate([]);
    return req.call(requestOptions);
  }

  /**
   * Retrieves the complete details for a specific transaction. This includes customer info, payment
   * method details, bank response codes, and hierarchy metadata (parent/child transactions).
   *
   * ### Additional query **parameters for this usecase:**
   *
   * | **Parameter** | **Notes** |
   * | --- | --- |
   * | include_subtransactions | Mandatory.  <br>Possible Values: true/false  <br>  <br>If true, includes
   * child transactions (e.g., recurring payments). |
   *
   * @param pageNo
   * @param pageSize
   * @param includeSubtransactions
   * @param brandId
   * @return Response from the API call
   */
  async getDetailedTransactionDetails(
    pageNo: number,
    pageSize: number,
    includeSubtransactions: boolean,
    brandId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest(
      'GET',
      '/api/v1/external/transactions/data/69e20fd928bea6ca2e31b17c'
    );
    req.baseUrl('Server 3');
    const mapped = req.prepareArgs({
      pageNo: [pageNo, number()],
      pageSize: [pageSize, number()],
      includeSubtransactions: [includeSubtransactions, boolean()],
      brandId: [brandId, string()],
    });
    req.header('BrandId', mapped.brandId);
    req.query('page_no', mapped.pageNo);
    req.query('page_size', mapped.pageSize);
    req.query('include_subtransactions', mapped.includeSubtransactions);
    req.throwOn(400, Success44Error, 'Bad Request');
    req.authenticate([]);
    return req.call(requestOptions);
  }
}
