/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Header, headerSchema } from './header.js';

export interface ApplepayToken {
  version: string;
  data: string;
  signature: string;
  header: Header;
  additionalProperties?: Record<string, unknown>;
}

export const applepayTokenSchema: Schema<ApplepayToken> = lazy(() =>
  typedExpandoObject(
    {
      version: ['version', string()],
      data: ['data', string()],
      signature: ['signature', string()],
      header: ['header', headerSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
