/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ApplepayDecryptedPayload,
  applepayDecryptedPayloadSchema,
} from './applepayDecryptedPayload.js';

export interface ApplepayParam1 {
  applepayDecryptedPayload: ApplepayDecryptedPayload;
  additionalProperties?: Record<string, unknown>;
}

export const applepayParam1Schema: Schema<ApplepayParam1> = lazy(() =>
  typedExpandoObject(
    {
      applepayDecryptedPayload: [
        'applepay_decrypted_payload',
        applepayDecryptedPayloadSchema,
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
