/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PaymentData, paymentDataSchema } from './paymentData.js';

export interface ApplepayDecryptedPayload {
  applicationPrimaryAccountNumber: string;
  applicationExpirationDate: string;
  currencyCode: string;
  transactionAmount: number;
  deviceManufacturerIdentifier: string;
  paymentDataType: string;
  paymentData: PaymentData;
  additionalProperties?: Record<string, unknown>;
}

export const applepayDecryptedPayloadSchema: Schema<ApplepayDecryptedPayload> = lazy(
  () =>
    typedExpandoObject(
      {
        applicationPrimaryAccountNumber: [
          'applicationPrimaryAccountNumber',
          string(),
        ],
        applicationExpirationDate: ['applicationExpirationDate', string()],
        currencyCode: ['currencyCode', string()],
        transactionAmount: ['transactionAmount', number()],
        deviceManufacturerIdentifier: [
          'deviceManufacturerIdentifier',
          string(),
        ],
        paymentDataType: ['paymentDataType', string()],
        paymentData: ['paymentData', paymentDataSchema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
