/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ApprovePayoutWithRemarksRequest {
  remarks: string;
  additionalProperties?: Record<string, unknown>;
}

export const approvePayoutWithRemarksRequestSchema: Schema<ApprovePayoutWithRemarksRequest> = typedExpandoObject(
  { remarks: ['remarks', string()] },
  'additionalProperties',
  optional(unknown())
);
