/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Extra52, extra52Schema } from './extra52.js';

export interface Attempt27 {
  clientIp: string;
  type: string;
  paymentMethod: string;
  flow: string;
  successful: boolean;
  country: string;
  processingTime: number;
  extra: Extra52;
  additionalProperties?: Record<string, unknown>;
}

export const attempt27Schema: Schema<Attempt27> = lazy(() =>
  typedExpandoObject(
    {
      clientIp: ['client_ip', string()],
      type: ['type', string()],
      paymentMethod: ['payment_method', string()],
      flow: ['flow', string()],
      successful: ['successful', boolean()],
      country: ['country', string()],
      processingTime: ['processing_time', number()],
      extra: ['extra', extra52Schema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
