/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Extra5, extra5Schema } from './extra5.js';

export interface Attempt2 {
  clientIp: string;
  type: string;
  paymentMethod?: string;
  flow?: string;
  successful: boolean;
  country?: string;
  processingTime: number;
  extra: Extra5;
  additionalProperties?: Record<string, unknown>;
}

export const attempt2Schema: Schema<Attempt2> = lazy(() =>
  typedExpandoObject(
    {
      clientIp: ['client_ip', string()],
      type: ['type', string()],
      paymentMethod: ['payment_method', optional(string())],
      flow: ['flow', optional(string())],
      successful: ['successful', boolean()],
      country: ['country', optional(string())],
      processingTime: ['processing_time', number()],
      extra: ['extra', extra5Schema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
