/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Balance1 {
  currency?: string;
  balance?: number;
  additionalProperties?: Record<string, unknown>;
}

export const balance1Schema: Schema<Balance1> = typedExpandoObject(
  {
    currency: ['currency', optional(string())],
    balance: ['balance', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
