/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Balance {
  currency: string;
  balance: number;
  additionalProperties?: Record<string, unknown>;
}

export const balanceSchema: Schema<Balance> = typedExpandoObject(
  { currency: ['currency', string()], balance: ['balance', number()] },
  'additionalProperties',
  optional(unknown())
);
