/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BankAccount {
  bankAccount: string;
  bankCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const bankAccountSchema: Schema<BankAccount> = typedExpandoObject(
  {
    bankAccount: ['bank_account', string()],
    bankCode: ['bank_code', string()],
  },
  'additionalProperties',
  optional(unknown())
);
