/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BeneficiaryDetail5 {
  upi: string;
  additionalProperties?: Record<string, unknown>;
}

export const beneficiaryDetail5Schema: Schema<BeneficiaryDetail5> = typedExpandoObject(
  { upi: ['upi', string()] },
  'additionalProperties',
  optional(unknown())
);
