/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BeneficiaryDetail6 {
  upi: string;
  transferType: string;
  additionalProperties?: Record<string, unknown>;
}

export const beneficiaryDetail6Schema: Schema<BeneficiaryDetail6> = typedExpandoObject(
  { upi: ['upi', string()], transferType: ['transferType', string()] },
  'additionalProperties',
  optional(unknown())
);
