/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { RoutingParam, routingParamSchema } from './routingParam.js';

export interface BeneficiaryDetail4 {
  bankName: string;
  bankAccountName: string;
  bankAccountCurrency: string;
  bankAccountNumber: string;
  bankCountryCode: string;
  swiftCode: string;
  routingParam: RoutingParam;
  additionalProperties?: Record<string, unknown>;
}

export const beneficiaryDetail4Schema: Schema<BeneficiaryDetail4> = lazy(() =>
  typedExpandoObject(
    {
      bankName: ['bankName', string()],
      bankAccountName: ['bankAccountName', string()],
      bankAccountCurrency: ['bankAccountCurrency', string()],
      bankAccountNumber: ['bankAccountNumber', string()],
      bankCountryCode: ['bankCountryCode', string()],
      swiftCode: ['swiftCode', string()],
      routingParam: ['routing_param', routingParamSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
