/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BeneficiaryDetail1 {
  bankAccountName: string;
  bankAccountNumber: string;
  ifscCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const beneficiaryDetail1Schema: Schema<BeneficiaryDetail1> = typedExpandoObject(
  {
    bankAccountName: ['bankAccountName', string()],
    bankAccountNumber: ['bankAccountNumber', string()],
    ifscCode: ['ifscCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
