/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data18, data18Schema } from './data18.js';

export interface BulkUpdateInvoiceNo {
  status: string;
  data: Data18;
  message: string;
  reqId: string;
  additionalProperties?: Record<string, unknown>;
}

export const bulkUpdateInvoiceNoSchema: Schema<BulkUpdateInvoiceNo> = lazy(() =>
  typedExpandoObject(
    {
      status: ['status', string()],
      data: ['data', data18Schema],
      message: ['message', string()],
      reqId: ['reqId', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
