/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BulkUpdateInvoiceNoRequest {
  transactionId: string;
  invoiceNo: string;
  additionalProperties?: Record<string, unknown>;
}

export const bulkUpdateInvoiceNoRequestSchema: Schema<BulkUpdateInvoiceNoRequest> = typedExpandoObject(
  {
    transactionId: ['transactionId', string()],
    invoiceNo: ['invoiceNo', string()],
  },
  'additionalProperties',
  optional(unknown())
);
