/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AggregatedBalance,
  aggregatedBalanceSchema,
} from './aggregatedBalance.js';
import { Gateway, gatewaySchema } from './gateway.js';

export interface CheckingBalancePayoutSuccess2 {
  paymentMethod: string;
  status: string;
  gateways: Gateway[];
  aggregatedBalances: AggregatedBalance[];
  additionalProperties?: Record<string, unknown>;
}

export const checkingBalancePayoutSuccess2Schema: Schema<CheckingBalancePayoutSuccess2> = lazy(
  () =>
    typedExpandoObject(
      {
        paymentMethod: ['paymentMethod', string()],
        status: ['status', string()],
        gateways: ['gateways', array(gatewaySchema)],
        aggregatedBalances: [
          'aggregatedBalances',
          array(aggregatedBalanceSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
