/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Datum, datumSchema } from './datum.js';

export interface CheckingBalancePayoutSuccess {
  paymentMethod: string;
  status: string;
  data: Datum[];
  additionalProperties?: Record<string, unknown>;
}

export const checkingBalancePayoutSuccessSchema: Schema<CheckingBalancePayoutSuccess> = lazy(
  () =>
    typedExpandoObject(
      {
        paymentMethod: ['paymentMethod', string()],
        status: ['status', string()],
        data: ['data', array(datumSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
