/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CheckingBalanceRequest {
  paymentMethod: string;
  additionalProperties?: Record<string, unknown>;
}

export const checkingBalanceRequestSchema: Schema<CheckingBalanceRequest> = typedExpandoObject(
  { paymentMethod: ['paymentMethod', string()] },
  'additionalProperties',
  optional(unknown())
);
