/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Gateway2, gateway2Schema } from './gateway2.js';

export interface CheckingBalancePayoutError2 {
  paymentMethod: string;
  status: string;
  gateways: Gateway2[];
  aggregatedBalances: string[];
  additionalProperties?: Record<string, unknown>;
}

export const checkingBalancePayoutError2Schema: Schema<CheckingBalancePayoutError2> = lazy(
  () =>
    typedExpandoObject(
      {
        paymentMethod: ['paymentMethod', string()],
        status: ['status', string()],
        gateways: ['gateways', array(gateway2Schema)],
        aggregatedBalances: ['aggregatedBalances', array(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
