/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AggregatedBalance,
  aggregatedBalanceSchema,
} from './aggregatedBalance.js';
import { Gateway1, gateway1Schema } from './gateway1.js';

export interface CheckingBalancePartialSuccess {
  paymentMethod: string;
  status: string;
  gateways: Gateway1[];
  aggregatedBalances: AggregatedBalance[];
  additionalProperties?: Record<string, unknown>;
}

export const checkingBalancePartialSuccessSchema: Schema<CheckingBalancePartialSuccess> = lazy(
  () =>
    typedExpandoObject(
      {
        paymentMethod: ['paymentMethod', string()],
        status: ['status', string()],
        gateways: ['gateways', array(gateway1Schema)],
        aggregatedBalances: [
          'aggregatedBalances',
          array(aggregatedBalanceSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
