/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Client65 {
  email: string;
  country: string;
  city: string;
  stateCode: string;
  streetAddress: string;
  zipCode: string;
  phone: string;
  additionalProperties?: Record<string, unknown>;
}

export const client65Schema: Schema<Client65> = typedExpandoObject(
  {
    email: ['email', string()],
    country: ['country', string()],
    city: ['city', string()],
    stateCode: ['stateCode', string()],
    streetAddress: ['street_address', string()],
    zipCode: ['zip_code', string()],
    phone: ['phone', string()],
  },
  'additionalProperties',
  optional(unknown())
);
