/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Client12 {
  type: string;
  customerId: string;
  email: string;
  phone: string;
  fullName: string;
  dateOfBirth: string | null;
  streetAddress: string;
  country: string;
  city: string;
  zipCode: string;
  documentId: string | null;
  documentType: string | null;
  speiClabe: string | null;
  speiDebitCard: string | null;
  speiMobileNo: string | null;
  stateCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const client12Schema: Schema<Client12> = typedExpandoObject(
  {
    type: ['_type', string()],
    customerId: ['customerId', string()],
    email: ['email', string()],
    phone: ['phone', string()],
    fullName: ['full_name', string()],
    dateOfBirth: ['date_of_birth', nullable(string())],
    streetAddress: ['street_address', string()],
    country: ['country', string()],
    city: ['city', string()],
    zipCode: ['zip_code', string()],
    documentId: ['documentId', nullable(string())],
    documentType: ['documentType', nullable(string())],
    speiClabe: ['spei_clabe', nullable(string())],
    speiDebitCard: ['spei_debitCard', nullable(string())],
    speiMobileNo: ['spei_mobileNo', nullable(string())],
    stateCode: ['stateCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
