/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Client17 {
  email: string;
  country: string;
  phone: string;
  fullName: string;
  additionalProperties?: Record<string, unknown>;
}

export const client17Schema: Schema<Client17> = typedExpandoObject(
  {
    email: ['email', string()],
    country: ['country', string()],
    phone: ['phone', string()],
    fullName: ['full_name', string()],
  },
  'additionalProperties',
  optional(unknown())
);
