/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Client9 {
  customerId: string;
  email: string;
  phone: string;
  fullName: string;
  dateOfBirth: string;
  streetAddress: string;
  country: string;
  city: string;
  zipCode: string;
  cc: string[];
  bcc: string[];
  gender: string;
  avatarUrl: string;
  stateCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const client9Schema: Schema<Client9> = typedExpandoObject(
  {
    customerId: ['customerId', string()],
    email: ['email', string()],
    phone: ['phone', string()],
    fullName: ['full_name', string()],
    dateOfBirth: ['date_of_birth', string()],
    streetAddress: ['street_address', string()],
    country: ['country', string()],
    city: ['city', string()],
    zipCode: ['zip_code', string()],
    cc: ['cc', array(string())],
    bcc: ['bcc', array(string())],
    gender: ['gender', string()],
    avatarUrl: ['avatarUrl', string()],
    stateCode: ['stateCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
