/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Client26 {
  email: string;
  fullName: string;
  taxNumber: string;
  additionalProperties?: Record<string, unknown>;
}

export const client26Schema: Schema<Client26> = typedExpandoObject(
  {
    email: ['email', string()],
    fullName: ['full_name', string()],
    taxNumber: ['tax_number', string()],
  },
  'additionalProperties',
  optional(unknown())
);
