/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Client66 {
  customerId: string;
  email: string;
  phone: string;
  dateOfBirth: string;
  streetAddress: string;
  country: string;
  city: string;
  zipCode: string;
  cc: string[];
  bcc: string[];
  stateCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const client66Schema: Schema<Client66> = typedExpandoObject(
  {
    customerId: ['customerId', string()],
    email: ['email', string()],
    phone: ['phone', string()],
    dateOfBirth: ['date_of_birth', string()],
    streetAddress: ['street_address', string()],
    country: ['country', string()],
    city: ['city', string()],
    zipCode: ['zip_code', string()],
    cc: ['cc', array(string())],
    bcc: ['bcc', array(string())],
    stateCode: ['stateCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
