/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Client57 {
  email: string;
  additionalProperties?: Record<string, unknown>;
}

export const client57Schema: Schema<Client57> = typedExpandoObject(
  { email: ['email', string()] },
  'additionalProperties',
  optional(unknown())
);
