/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Client86 {
  email: string;
  fullName: string;
  streetAddress: string;
  country: string;
  city: string;
  zipCode: string;
  stateCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const client86Schema: Schema<Client86> = typedExpandoObject(
  {
    email: ['email', string()],
    fullName: ['full_name', string()],
    streetAddress: ['street_address', string()],
    country: ['country', string()],
    city: ['city', string()],
    zipCode: ['zip_code', string()],
    stateCode: ['stateCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
