/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Client2 {
  bankAccount: string;
  bankCode: string;
  email: string;
  phone: string;
  fullName: string;
  dateOfBirth: string;
  personalCode: string;
  streetAddress: string;
  country: string;
  city: string;
  zipCode: string;
  shippingStreetAddress: string;
  shippingCountry: string;
  shippingCity: string;
  shippingZipCode: string;
  cc: string[];
  bcc: string[];
  legalName: string;
  brandName: string;
  registrationNumber: string;
  taxNumber: string;
  stateCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const client2Schema: Schema<Client2> = typedExpandoObject(
  {
    bankAccount: ['bank_account', string()],
    bankCode: ['bank_code', string()],
    email: ['email', string()],
    phone: ['phone', string()],
    fullName: ['full_name', string()],
    dateOfBirth: ['date_of_birth', string()],
    personalCode: ['personal_code', string()],
    streetAddress: ['street_address', string()],
    country: ['country', string()],
    city: ['city', string()],
    zipCode: ['zip_code', string()],
    shippingStreetAddress: ['shipping_street_address', string()],
    shippingCountry: ['shipping_country', string()],
    shippingCity: ['shipping_city', string()],
    shippingZipCode: ['shipping_zip_code', string()],
    cc: ['cc', array(string())],
    bcc: ['bcc', array(string())],
    legalName: ['legal_name', string()],
    brandName: ['brand_name', string()],
    registrationNumber: ['registration_number', string()],
    taxNumber: ['tax_number', string()],
    stateCode: ['stateCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
