/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Content {
  transactionId: string;
  status: string;
  additionalProperties?: Record<string, unknown>;
}

export const contentSchema: Schema<Content> = typedExpandoObject(
  { transactionId: ['transaction_id', string()], status: ['status', string()] },
  'additionalProperties',
  optional(unknown())
);
