/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client29, client29Schema } from './client29.js';

export interface CreatePayOutRequest3 {
  client: Client29;
  purpose: string;
  payoutMethod: string;
  brandId: string;
  amount: number;
  currency: string;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const createPayOutRequest3Schema: Schema<CreatePayOutRequest3> = lazy(
  () =>
    typedExpandoObject(
      {
        client: ['client', client29Schema],
        purpose: ['purpose', string()],
        payoutMethod: ['payoutMethod', string()],
        brandId: ['brand_id', string()],
        amount: ['amount', number()],
        currency: ['currency', string()],
        successRedirect: ['success_redirect', string()],
        pendingRedirect: ['pending_redirect', string()],
        failureRedirect: ['failure_redirect', string()],
        successCallback: ['success_callback', string()],
        failureCallback: ['failure_callback', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
