/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client80, client80Schema } from './client80.js';
import { Purchase10, purchase10Schema } from './purchase10.js';

export interface CreatePurchaseMitRequest {
  client: Client80;
  purchase: Purchase10;
  merchantRef: string;
  brandId: string;
  paymentType: string;
  mandateId: string;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const createPurchaseMitRequestSchema: Schema<CreatePurchaseMitRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        client: ['client', client80Schema],
        purchase: ['purchase', purchase10Schema],
        merchantRef: ['merchantRef', string()],
        brandId: ['brand_id', string()],
        paymentType: ['payment_type', string()],
        mandateId: ['mandate_id', string()],
        successRedirect: ['success_redirect', string()],
        pendingRedirect: ['pending_redirect', string()],
        failureRedirect: ['failure_redirect', string()],
        successCallback: ['success_callback', string()],
        failureCallback: ['failure_callback', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
