/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data5, data5Schema } from './data5.js';

export interface CreateMerchantApi {
  status: string;
  data: Data5;
  message: string;
  reqId: string;
  additionalProperties?: Record<string, unknown>;
}

export const createMerchantApiSchema: Schema<CreateMerchantApi> = lazy(() =>
  typedExpandoObject(
    {
      status: ['status', string()],
      data: ['data', data5Schema],
      message: ['message', string()],
      reqId: ['reqId', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
