/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client8, client8Schema } from './client8.js';

export interface CreatePayOutRequest {
  client: Client8;
  payoutMethod: string;
  purpose: string;
  currency: string;
  amount: number;
  successRedirect: string;
  failureRedirect: string;
  pendingRedirect: string;
  additionalProperties?: Record<string, unknown>;
}

export const createPayOutRequestSchema: Schema<CreatePayOutRequest> = lazy(() =>
  typedExpandoObject(
    {
      client: ['client', client8Schema],
      payoutMethod: ['payoutMethod', string()],
      purpose: ['purpose', string()],
      currency: ['currency', string()],
      amount: ['amount', number()],
      successRedirect: ['success_redirect', string()],
      failureRedirect: ['failure_redirect', string()],
      pendingRedirect: ['pending_redirect', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
