/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client17, client17Schema } from './client17.js';

export interface CreatePayOutRequest1 {
  client: Client17;
  purpose: string;
  currency: string;
  payoutMethod: string;
  amount: number;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const createPayOutRequest1Schema: Schema<CreatePayOutRequest1> = lazy(
  () =>
    typedExpandoObject(
      {
        client: ['client', client17Schema],
        purpose: ['purpose', string()],
        currency: ['currency', string()],
        payoutMethod: ['payoutMethod', string()],
        amount: ['amount', number()],
        successCallback: ['success_callback', string()],
        failureCallback: ['failure_callback', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
