/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  BeneficiaryDetail2,
  beneficiaryDetail2Schema,
} from './beneficiaryDetail2.js';
import { Client7, client7Schema } from './client7.js';

export interface CreatePayOutRequest6 {
  client: Client7;
  beneficiaryDetail: BeneficiaryDetail2;
  purpose: string;
  currency: string;
  payoutMethod: string;
  amount: number;
  brandId: string;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const createPayOutRequest6Schema: Schema<CreatePayOutRequest6> = lazy(
  () =>
    typedExpandoObject(
      {
        client: ['client', client7Schema],
        beneficiaryDetail: ['beneficiaryDetail', beneficiaryDetail2Schema],
        purpose: ['purpose', string()],
        currency: ['currency', string()],
        payoutMethod: ['payoutMethod', string()],
        amount: ['amount', number()],
        brandId: ['brandId', string()],
        successRedirect: ['success_redirect', string()],
        pendingRedirect: ['pending_redirect', string()],
        failureRedirect: ['failure_redirect', string()],
        successCallback: ['success_callback', string()],
        failureCallback: ['failure_callback', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
