/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ExtraParam10, extraParam10Schema } from './extraParam10.js';

export interface CreateCustomerRequest1 {
  fullName: string;
  emailId: string;
  dateOfBirth: string;
  phoneNo: string;
  city: string;
  stateCode: string;
  zipCode: string;
  address: string;
  country: string;
  merchantCustomerId: string;
  custRegDate: string;
  successTxn: string;
  extraParam: ExtraParam10;
  additionalProperties?: Record<string, unknown>;
}

export const createCustomerRequest1Schema: Schema<CreateCustomerRequest1> = lazy(
  () =>
    typedExpandoObject(
      {
        fullName: ['fullName', string()],
        emailId: ['emailId', string()],
        dateOfBirth: ['dateOfBirth', string()],
        phoneNo: ['phoneNo', string()],
        city: ['city', string()],
        stateCode: ['stateCode', string()],
        zipCode: ['zipCode', string()],
        address: ['address', string()],
        country: ['country', string()],
        merchantCustomerId: ['merchantCustomerId', string()],
        custRegDate: ['CustRegDate', string()],
        successTxn: ['SuccessTxn', string()],
        extraParam: ['extraParam', extraParam10Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
