/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CreateMerchantApiRequest {
  username: string;
  mcc: number;
  iecNo: string;
  allowGlobalCollection: boolean;
  legalName: string;
  name: string;
  regNo: string;
  emailId: string;
  websiteUrl: string;
  tradingStartDate: string;
  dateOfIncorporation: string;
  tradingAddress: string;
  tradingCountry: string;
  tradingState: string;
  tradingPostal: string;
  corporateAddress: string;
  corporateCountry: string;
  corporateState: string;
  corporatePostal: string;
  businessPhone: string;
  contactPhone: string;
  contactName: string;
  officerTitle: string;
  officerName: string;
  defaultCurrency: string;
  defaultTimezone: string;
  allowedPaymentMethods: string[];
  allowedCurrencies: string[];
  isLiveTransactionAllowed: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const createMerchantApiRequestSchema: Schema<CreateMerchantApiRequest> = typedExpandoObject(
  {
    username: ['username', string()],
    mcc: ['mcc', number()],
    iecNo: ['iecNo', string()],
    allowGlobalCollection: ['allowGlobalCollection', boolean()],
    legalName: ['legalName', string()],
    name: ['name', string()],
    regNo: ['regNo', string()],
    emailId: ['emailId', string()],
    websiteUrl: ['websiteUrl', string()],
    tradingStartDate: ['tradingStartDate', string()],
    dateOfIncorporation: ['dateOfIncorporation', string()],
    tradingAddress: ['tradingAddress', string()],
    tradingCountry: ['tradingCountry', string()],
    tradingState: ['tradingState', string()],
    tradingPostal: ['tradingPostal', string()],
    corporateAddress: ['corporateAddress', string()],
    corporateCountry: ['corporateCountry', string()],
    corporateState: ['corporateState', string()],
    corporatePostal: ['corporatePostal', string()],
    businessPhone: ['businessPhone', string()],
    contactPhone: ['contactPhone', string()],
    contactName: ['contactName', string()],
    officerTitle: ['officerTitle', string()],
    officerName: ['officerName', string()],
    defaultCurrency: ['defaultCurrency', string()],
    defaultTimezone: ['defaultTimezone', string()],
    allowedPaymentMethods: ['allowedPaymentMethods', array(string())],
    allowedCurrencies: ['allowedCurrencies', array(string())],
    isLiveTransactionAllowed: ['isLiveTransactionAllowed', boolean()],
  },
  'additionalProperties',
  optional(unknown())
);
