/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client13, client13Schema } from './client13.js';
import { StatusHistory, statusHistorySchema } from './statusHistory.js';

export interface CreatePayoutSuccess1 {
  payoutId: string;
  client: Client13;
  updatedOn: number;
  payoutMethod: string;
  amountUnit: string;
  amount: number;
  errorMsg: string;
  purpose: string;
  createdOn: number;
  merchantRef: string;
  merchantName: string;
  status: string;
  statusHistory: StatusHistory[];
  viewedOn: number;
  currency: string;
  paymentOn: number;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const createPayoutSuccess1Schema: Schema<CreatePayoutSuccess1> = lazy(
  () =>
    typedExpandoObject(
      {
        payoutId: ['payoutId', string()],
        client: ['client', client13Schema],
        updatedOn: ['updated_on', number()],
        payoutMethod: ['payoutMethod', string()],
        amountUnit: ['amountUnit', string()],
        amount: ['amount', number()],
        errorMsg: ['errorMsg', string()],
        purpose: ['purpose', string()],
        createdOn: ['created_on', number()],
        merchantRef: ['merchantRef', string()],
        merchantName: ['merchantName', string()],
        status: ['status', string()],
        statusHistory: ['status_history', array(statusHistorySchema)],
        viewedOn: ['viewedOn', number()],
        currency: ['currency', string()],
        paymentOn: ['paymentOn', number()],
        successCallback: ['success_callback', string()],
        failureCallback: ['failure_callback', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
