/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client37, client37Schema } from './client37.js';

export interface CreatePayOutRequest4 {
  client: Client37;
  purpose: string;
  currency: string;
  payoutMethod: string;
  amount: number;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const createPayOutRequest4Schema: Schema<CreatePayOutRequest4> = lazy(
  () =>
    typedExpandoObject(
      {
        client: ['client', client37Schema],
        purpose: ['purpose', string()],
        currency: ['currency', string()],
        payoutMethod: ['payoutMethod', string()],
        amount: ['amount', number()],
        successCallback: ['success_callback', string()],
        failureCallback: ['failure_callback', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
