/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Mandate, mandateSchema } from './mandate.js';
import { Product, productSchema } from './product.js';

export interface CreateSessionCitRequest {
  customerId: string;
  currency: string;
  products: Product[];
  totalAmount: string;
  paymentMethod: string;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  successCallback: string;
  failureCallback: string;
  paymentType: string;
  mandate: Mandate;
  additionalProperties?: Record<string, unknown>;
}

export const createSessionCitRequestSchema: Schema<CreateSessionCitRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        customerId: ['customerId', string()],
        currency: ['currency', string()],
        products: ['products', array(productSchema)],
        totalAmount: ['totalAmount', string()],
        paymentMethod: ['paymentMethod', string()],
        successRedirect: ['success_redirect', string()],
        pendingRedirect: ['pending_redirect', string()],
        failureRedirect: ['failure_redirect', string()],
        successCallback: ['success_callback', string()],
        failureCallback: ['failure_callback', string()],
        paymentType: ['payment_type', string()],
        mandate: ['mandate', mandateSchema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
