/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client8, client8Schema } from './client8.js';
import { Mandate, mandateSchema } from './mandate.js';
import { Purchase, purchaseSchema } from './purchase.js';

export interface CreatePurchaseCitRequest {
  client: Client8;
  purchase: Purchase;
  merchantRef: string;
  paymentMethod: string;
  brandId: string;
  paymentType: string;
  mandate: Mandate;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const createPurchaseCitRequestSchema: Schema<CreatePurchaseCitRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        client: ['client', client8Schema],
        purchase: ['purchase', purchaseSchema],
        merchantRef: ['merchantRef', string()],
        paymentMethod: ['paymentMethod', string()],
        brandId: ['brand_id', string()],
        paymentType: ['payment_type', string()],
        mandate: ['mandate', mandateSchema],
        successRedirect: ['success_redirect', string()],
        pendingRedirect: ['pending_redirect', string()],
        failureRedirect: ['failure_redirect', string()],
        successCallback: ['success_callback', string()],
        failureCallback: ['failure_callback', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
