/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ActionStatus, actionStatusSchema } from './actionStatus.js';
import { Client12, client12Schema } from './client12.js';
import { StatusHistory8, statusHistory8Schema } from './statusHistory8.js';

export interface CreatePayoutSuccess {
  type: string;
  payoutId: string;
  client: Client12;
  updatedOn: number;
  payoutMethod: string;
  beneficiaryDetail: string | null;
  amountUnit: string;
  amount: number;
  errorMsg: string;
  issued: string;
  responseMsg: string | null;
  purpose: string;
  createdOn: number;
  custUniqueId: string;
  amountInUsd: number;
  merchantRef: string;
  instruction: string | null;
  merchantId: string | null;
  usePrivateKey: string | null;
  merchantName: string | null;
  agentId: number;
  parentId: number;
  whiteId: number;
  year: string | null;
  month: string | null;
  day: string | null;
  hour: number;
  bankid: string | null;
  setCurr: string;
  pspReference: string | null;
  bankmid: string | null;
  bankname: string | null;
  status: string;
  statusHistory: StatusHistory8[];
  viewedOn: string | null;
  currency: string;
  actionStatus: ActionStatus;
  fxCurrency: string | null;
  fxAmount: string | null;
  referer: string | null;
  clientIp: string;
  merchantIp: string;
  transFees: string | null;
  mdr: string | null;
  ruleName: string;
  cascadeNum: string | null;
  conversionRiskFactorApplied: string | null;
  feesDeducted: number;
  signature: string | null;
  puId: string;
  uId: number;
  authKey: string;
  currencyConversion: string | null;
  successCallback: string;
  failureCallback: string;
  successRedirect: string;
  failureRedirect: string;
  pendingRedirect: string;
  additionalProperties?: Record<string, unknown>;
}

export const createPayoutSuccessSchema: Schema<CreatePayoutSuccess> = lazy(() =>
  typedExpandoObject(
    {
      type: ['_type', string()],
      payoutId: ['payoutId', string()],
      client: ['client', client12Schema],
      updatedOn: ['updated_on', number()],
      payoutMethod: ['payoutMethod', string()],
      beneficiaryDetail: ['beneficiaryDetail', nullable(string())],
      amountUnit: ['amountUnit', string()],
      amount: ['amount', number()],
      errorMsg: ['errorMsg', string()],
      issued: ['issued', string()],
      responseMsg: ['responseMsg', nullable(string())],
      purpose: ['purpose', string()],
      createdOn: ['created_on', number()],
      custUniqueId: ['custUniqueId', string()],
      amountInUsd: ['amount_in_usd', number()],
      merchantRef: ['merchantRef', string()],
      instruction: ['instruction', nullable(string())],
      merchantId: ['merchant_id', nullable(string())],
      usePrivateKey: ['usePrivateKey', nullable(string())],
      merchantName: ['merchantName', nullable(string())],
      agentId: ['agentId', number()],
      parentId: ['parentId', number()],
      whiteId: ['whiteId', number()],
      year: ['year', nullable(string())],
      month: ['month', nullable(string())],
      day: ['day', nullable(string())],
      hour: ['hour', number()],
      bankid: ['bankid', nullable(string())],
      setCurr: ['setCurr', string()],
      pspReference: ['pspReference', nullable(string())],
      bankmid: ['bankmid', nullable(string())],
      bankname: ['bankname', nullable(string())],
      status: ['status', string()],
      statusHistory: ['status_history', array(statusHistory8Schema)],
      viewedOn: ['viewedOn', nullable(string())],
      currency: ['currency', string()],
      actionStatus: ['actionStatus', actionStatusSchema],
      fxCurrency: ['fx_Currency', nullable(string())],
      fxAmount: ['fx_Amount', nullable(string())],
      referer: ['referer', nullable(string())],
      clientIp: ['clientIp', string()],
      merchantIp: ['merchantIp', string()],
      transFees: ['transFees', nullable(string())],
      mdr: ['MDR', nullable(string())],
      ruleName: ['ruleName', string()],
      cascadeNum: ['cascade_Num', nullable(string())],
      conversionRiskFactorApplied: [
        'conversionRiskFactorApplied',
        nullable(string()),
      ],
      feesDeducted: ['feesDeducted', number()],
      signature: ['signature', nullable(string())],
      puId: ['puId', string()],
      uId: ['uId', number()],
      authKey: ['authKey', string()],
      currencyConversion: ['currency_conversion', nullable(string())],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
      successRedirect: ['success_redirect', string()],
      failureRedirect: ['failure_redirect', string()],
      pendingRedirect: ['pending_redirect', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
