/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CreateMerchantApiTokenRequest {
  apiLabel: string;
  isSandbox: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const createMerchantApiTokenRequestSchema: Schema<CreateMerchantApiTokenRequest> = typedExpandoObject(
  { apiLabel: ['apiLabel', string()], isSandbox: ['isSandbox', boolean()] },
  'additionalProperties',
  optional(unknown())
);
