/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data8, data8Schema } from './data8.js';

export interface CreateMerchantApiToken {
  status: string;
  data: Data8;
  message: string;
  reqId: string;
  additionalProperties?: Record<string, unknown>;
}

export const createMerchantApiTokenSchema: Schema<CreateMerchantApiToken> = lazy(
  () =>
    typedExpandoObject(
      {
        status: ['status', string()],
        data: ['data', data8Schema],
        message: ['message', string()],
        reqId: ['reqId', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
