/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CustomerRequest1 {
  fullName: string;
  emailId: string;
  dateOfBirth: string;
  phoneNo: string;
  city: string;
  stateCode: string;
  zipCode: string;
  address: string;
  country: string;
  custRegDate: string;
  successTxn: string;
  additionalProperties?: Record<string, unknown>;
}

export const customerRequest1Schema: Schema<CustomerRequest1> = typedExpandoObject(
  {
    fullName: ['fullName', string()],
    emailId: ['emailId', string()],
    dateOfBirth: ['dateOfBirth', string()],
    phoneNo: ['phoneNo', string()],
    city: ['city', string()],
    stateCode: ['stateCode', string()],
    zipCode: ['zipCode', string()],
    address: ['address', string()],
    country: ['country', string()],
    custRegDate: ['CustRegDate', string()],
    successTxn: ['SuccessTxn', string()],
  },
  'additionalProperties',
  optional(unknown())
);
