/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Data7 {
  merchantId: number;
  additionalProperties?: Record<string, unknown>;
}

export const data7Schema: Schema<Data7> = typedExpandoObject(
  { merchantId: ['merchantId', number()] },
  'additionalProperties',
  optional(unknown())
);
