/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Pagination, paginationSchema } from './pagination.js';
import { Transaction, transactionSchema } from './transaction.js';

export interface Data11 {
  transactions: Transaction[];
  pagination: Pagination;
  additionalProperties?: Record<string, unknown>;
}

export const data11Schema: Schema<Data11> = lazy(() =>
  typedExpandoObject(
    {
      transactions: ['transactions', array(transactionSchema)],
      pagination: ['pagination', paginationSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
