/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Merchant, merchantSchema } from './merchant.js';
import { Pagination, paginationSchema } from './pagination.js';

export interface Data4 {
  merchant: Merchant[];
  pagination: Pagination;
  additionalProperties?: Record<string, unknown>;
}

export const data4Schema: Schema<Data4> = lazy(() =>
  typedExpandoObject(
    {
      merchant: ['merchant', array(merchantSchema)],
      pagination: ['pagination', paginationSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
