/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Data18 {
  updatedCount: number;
  skippedTransactionIds: string[];
  additionalProperties?: Record<string, unknown>;
}

export const data18Schema: Schema<Data18> = typedExpandoObject(
  {
    updatedCount: ['updatedCount', number()],
    skippedTransactionIds: ['skippedTransactionIds', array(string())],
  },
  'additionalProperties',
  optional(unknown())
);
