/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Content, contentSchema } from './content.js';

export interface Data {
  content: Content[];
  currentPage: number;
  pageSize: number;
  totalElements: number;
  totalPages: number;
  first: boolean;
  last: boolean;
  hasNext: boolean;
  hasPrevious: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const dataSchema: Schema<Data> = lazy(() =>
  typedExpandoObject(
    {
      content: ['content', array(contentSchema)],
      currentPage: ['currentPage', number()],
      pageSize: ['pageSize', number()],
      totalElements: ['totalElements', number()],
      totalPages: ['totalPages', number()],
      first: ['first', boolean()],
      last: ['last', boolean()],
      hasNext: ['hasNext', boolean()],
      hasPrevious: ['hasPrevious', boolean()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
