/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Data13 {
  merchantId: number;
  username: string;
  email: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const data13Schema: Schema<Data13> = typedExpandoObject(
  {
    merchantId: ['merchantId', number()],
    username: ['username', string()],
    email: ['email', nullable(string())],
  },
  'additionalProperties',
  optional(unknown())
);
