/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Data16 {
  country: string;
  currency: string;
  status: string;
  accountNo: string;
  createdOn: number;
  additionalProperties?: Record<string, unknown>;
}

export const data16Schema: Schema<Data16> = typedExpandoObject(
  {
    country: ['country', string()],
    currency: ['currency', string()],
    status: ['status', string()],
    accountNo: ['accountNo', string()],
    createdOn: ['createdOn', number()],
  },
  'additionalProperties',
  optional(unknown())
);
