/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Fee, feeSchema } from './fee.js';
import { Metadata, metadataSchema } from './metadata.js';

export interface Data2 {
  transactionId: string;
  merchantReference: string;
  customerId: string;
  amount: number;
  currency: string;
  status: string;
  sessionId: string;
  email: string;
  merchantName: string;
  paymentMethod: string;
  paymentFlow: string;
  issuingBank: string;
  createdAt: string;
  errorReason: string;
  lastUpdatedAt: string;
  transactionType: string;
  fees: Fee[];
  metadata: Metadata;
  additionalProperties?: Record<string, unknown>;
}

export const data2Schema: Schema<Data2> = lazy(() =>
  typedExpandoObject(
    {
      transactionId: ['transaction_id', string()],
      merchantReference: ['merchant_reference', string()],
      customerId: ['customer_id', string()],
      amount: ['amount', number()],
      currency: ['currency', string()],
      status: ['status', string()],
      sessionId: ['session_id', string()],
      email: ['email', string()],
      merchantName: ['merchant_name', string()],
      paymentMethod: ['payment_method', string()],
      paymentFlow: ['payment_flow', string()],
      issuingBank: ['issuing_bank', string()],
      createdAt: ['created_at', string()],
      errorReason: ['error_reason', string()],
      lastUpdatedAt: ['last_updated_at', string()],
      transactionType: ['transaction_type', string()],
      fees: ['fees', array(feeSchema)],
      metadata: ['metadata', metadataSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
