/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Data14 {
  id: number;
  name: string;
  brandId: string;
  merchantId: number;
  additionalProperties?: Record<string, unknown>;
}

export const data14Schema: Schema<Data14> = typedExpandoObject(
  {
    id: ['id', number()],
    name: ['name', string()],
    brandId: ['brandId', string()],
    merchantId: ['merchantId', number()],
  },
  'additionalProperties',
  optional(unknown())
);
