/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data14, data14Schema } from './data14.js';

export interface DeleteBrandId {
  status: string;
  data: Data14;
  message: string;
  reqId: string;
  additionalProperties?: Record<string, unknown>;
}

export const deleteBrandIdSchema: Schema<DeleteBrandId> = lazy(() =>
  typedExpandoObject(
    {
      status: ['status', string()],
      data: ['data', data14Schema],
      message: ['message', string()],
      reqId: ['reqId', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
