/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data13, data13Schema } from './data13.js';

export interface DeleteMerchantToken {
  status: string;
  data: Data13;
  message: string;
  reqId: string;
  additionalProperties?: Record<string, unknown>;
}

export const deleteMerchantTokenSchema: Schema<DeleteMerchantToken> = lazy(() =>
  typedExpandoObject(
    {
      status: ['status', string()],
      data: ['data', data13Schema],
      message: ['message', string()],
      reqId: ['reqId', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
