/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Error7 {
  code?: string;
  message?: string;
  additionalProperties?: Record<string, unknown>;
}

export const error7Schema: Schema<Error7> = typedExpandoObject(
  {
    code: ['code', optional(string())],
    message: ['message', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
