/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Extra5 {
  expiryMonth?: string;
  amount: number;
  cardIssuer?: string;
  maskedPan?: string;
  cardBrand?: string;
  cardIssuerCountry?: string;
  cardholderName?: string;
  expiryYear?: string;
  additionalProperties?: Record<string, unknown>;
}

export const extra5Schema: Schema<Extra5> = typedExpandoObject(
  {
    expiryMonth: ['expiry_month', optional(string())],
    amount: ['amount', number()],
    cardIssuer: ['card_issuer', optional(string())],
    maskedPan: ['masked_pan', optional(string())],
    cardBrand: ['card_brand', optional(string())],
    cardIssuerCountry: ['card_issuer_country', optional(string())],
    cardholderName: ['cardholder_name', optional(string())],
    expiryYear: ['expiry_year', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
