/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ExtraParam7 {
  payId: string;
  bankName: string;
  accountName: string;
  additionalProperties?: Record<string, unknown>;
}

export const extraParam7Schema: Schema<ExtraParam7> = typedExpandoObject(
  {
    payId: ['payId', string()],
    bankName: ['bankName', string()],
    accountName: ['accountName', string()],
  },
  'additionalProperties',
  optional(unknown())
);
