/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ExtraParam21 {
  showCryptoConversion: string;
  cryptoCurrencies: string;
  additionalProperties?: Record<string, unknown>;
}

export const extraParam21Schema: Schema<ExtraParam21> = typedExpandoObject(
  {
    showCryptoConversion: ['showCryptoConversion', string()],
    cryptoCurrencies: ['cryptoCurrencies', string()],
  },
  'additionalProperties',
  optional(unknown())
);
