/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ExtraParam6 {
  isCryptoPurchase: string;
  additionalProperties?: Record<string, unknown>;
}

export const extraParam6Schema: Schema<ExtraParam6> = typedExpandoObject(
  { isCryptoPurchase: ['IsCryptoPurchase', string()] },
  'additionalProperties',
  optional(unknown())
);
