/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ApplepayParam1, applepayParam1Schema } from './applepayParam1.js';

export interface ExtraParam5 {
  applepayParam: ApplepayParam1;
  additionalProperties?: Record<string, unknown>;
}

export const extraParam5Schema: Schema<ExtraParam5> = lazy(() =>
  typedExpandoObject(
    { applepayParam: ['applepay_param', applepayParam1Schema] },
    'additionalProperties',
    optional(unknown())
  )
);
