/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { GooglepayParam, googlepayParamSchema } from './googlepayParam.js';

export interface ExtraParam2 {
  googlepayParam: GooglepayParam;
  additionalProperties?: Record<string, unknown>;
}

export const extraParam2Schema: Schema<ExtraParam2> = lazy(() =>
  typedExpandoObject(
    { googlepayParam: ['googlepay_param', googlepayParamSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
