/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ApplepayParam, applepayParamSchema } from './applepayParam.js';

export interface ExtraParam4 {
  applepayParam: ApplepayParam;
  additionalProperties?: Record<string, unknown>;
}

export const extraParam4Schema: Schema<ExtraParam4> = lazy(() =>
  typedExpandoObject(
    { applepayParam: ['applepay_param', applepayParamSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
