/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Extra10 {
  amount: number;
  maskedPan: string;
  additionalProperties?: Record<string, unknown>;
}

export const extra10Schema: Schema<Extra10> = typedExpandoObject(
  { amount: ['amount', number()], maskedPan: ['masked_pan', string()] },
  'additionalProperties',
  optional(unknown())
);
