/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Aft, aftSchema } from './aft.js';

export interface ExtraParam26 {
  aft: Aft;
  additionalProperties?: Record<string, unknown>;
}

export const extraParam26Schema: Schema<ExtraParam26> = lazy(() =>
  typedExpandoObject(
    { aft: ['aft', aftSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
