/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ExtraParam25 {
  tokenReference: string;
  additionalProperties?: Record<string, unknown>;
}

export const extraParam25Schema: Schema<ExtraParam25> = typedExpandoObject(
  { tokenReference: ['token_reference', string()] },
  'additionalProperties',
  optional(unknown())
);
