/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ToAddress1, toAddress1Schema } from './toAddress1.js';

export interface ExtraParam9 {
  clientFee: number;
  toAddress: ToAddress1[];
  additionalProperties?: Record<string, unknown>;
}

export const extraParam9Schema: Schema<ExtraParam9> = lazy(() =>
  typedExpandoObject(
    {
      clientFee: ['clientFee', number()],
      toAddress: ['toAddress', array(toAddress1Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
