/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Extra57 {
  amount: number;
  maskedPan: string;
  cardBrand: string;
  cardIssuerCountry: string;
  cardholderName: string;
  expiryMonth?: string;
  cardIssuer?: string;
  cardType?: string;
  expiryYear?: string;
  additionalProperties?: Record<string, unknown>;
}

export const extra57Schema: Schema<Extra57> = typedExpandoObject(
  {
    amount: ['amount', number()],
    maskedPan: ['masked_pan', string()],
    cardBrand: ['card_brand', string()],
    cardIssuerCountry: ['card_issuer_country', string()],
    cardholderName: ['cardholder_name', string()],
    expiryMonth: ['expiry_month', optional(string())],
    cardIssuer: ['card_issuer', optional(string())],
    cardType: ['card_type', optional(string())],
    expiryYear: ['expiry_year', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
