/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ExtraParam13 {
  productType: string;
  additionalProperties?: Record<string, unknown>;
}

export const extraParam13Schema: Schema<ExtraParam13> = typedExpandoObject(
  { productType: ['productType', string()] },
  'additionalProperties',
  optional(unknown())
);
