/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { GooglepayParam1, googlepayParam1Schema } from './googlepayParam1.js';

export interface ExtraParam3 {
  googlepayParam: GooglepayParam1;
  additionalProperties?: Record<string, unknown>;
}

export const extraParam3Schema: Schema<ExtraParam3> = lazy(() =>
  typedExpandoObject(
    { googlepayParam: ['googlepay_param', googlepayParam1Schema] },
    'additionalProperties',
    optional(unknown())
  )
);
