/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ToAddress, toAddressSchema } from './toAddress.js';

export interface ExtraParam8 {
  clientFee: number;
  toAddress: ToAddress[];
  additionalProperties?: Record<string, unknown>;
}

export const extraParam8Schema: Schema<ExtraParam8> = lazy(() =>
  typedExpandoObject(
    {
      clientFee: ['clientFee', number()],
      toAddress: ['toAddress', array(toAddressSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
