/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ExtraParam20 {
  param1: string;
  showCryptoConversion: string;
  cryptoCurrencies: string;
  param3: string;
  param4: string;
  additionalProperties?: Record<string, unknown>;
}

export const extraParam20Schema: Schema<ExtraParam20> = typedExpandoObject(
  {
    param1: ['param1', string()],
    showCryptoConversion: ['showCryptoConversion', string()],
    cryptoCurrencies: ['cryptoCurrencies', string()],
    param3: ['param3', string()],
    param4: ['param4', string()],
  },
  'additionalProperties',
  optional(unknown())
);
