/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { FeeAmount, feeAmountSchema } from './containers/feeAmount.js';

export interface Fee {
  type: string;
  amount: FeeAmount;
  currency: string;
  additionalProperties?: Record<string, unknown>;
}

export const feeSchema: Schema<Fee> = lazy(() =>
  typedExpandoObject(
    {
      type: ['type', string()],
      amount: ['amount', feeAmountSchema],
      currency: ['currency', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
