/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Balance, balanceSchema } from './balance.js';

export interface Gateway {
  gatewayName: string;
  status: string;
  error: string | null;
  balances: Balance[];
  additionalProperties?: Record<string, unknown>;
}

export const gatewaySchema: Schema<Gateway> = lazy(() =>
  typedExpandoObject(
    {
      gatewayName: ['gatewayName', string()],
      status: ['status', string()],
      error: ['error', nullable(string())],
      balances: ['balances', array(balanceSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
