/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Error, errorSchema } from './error.js';

export interface Gateway2 {
  gatewayName: string;
  status: string;
  error: Error;
  balances: string[];
  additionalProperties?: Record<string, unknown>;
}

export const gateway2Schema: Schema<Gateway2> = lazy(() =>
  typedExpandoObject(
    {
      gatewayName: ['gatewayName', string()],
      status: ['status', string()],
      error: ['error', errorSchema],
      balances: ['balances', array(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
