/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data16, data16Schema } from './data16.js';

export interface GetGlobalAccounts {
  status: string;
  data: Data16[];
  message: string;
  reqId: string;
  additionalProperties?: Record<string, unknown>;
}

export const getGlobalAccountsSchema: Schema<GetGlobalAccounts> = lazy(() =>
  typedExpandoObject(
    {
      status: ['status', string()],
      data: ['data', array(data16Schema)],
      message: ['message', string()],
      reqId: ['reqId', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
