/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data4, data4Schema } from './data4.js';

export interface GetMerchants {
  status: string;
  data: Data4;
  message: string;
  reqId: string;
  additionalProperties?: Record<string, unknown>;
}

export const getMerchantsSchema: Schema<GetMerchants> = lazy(() =>
  typedExpandoObject(
    {
      status: ['status', string()],
      data: ['data', data4Schema],
      message: ['message', string()],
      reqId: ['reqId', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
