/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data11, data11Schema } from './data11.js';

export interface GetMissingInvoiceTransactions {
  status: string;
  data: Data11;
  message: string;
  reqId: string;
  additionalProperties?: Record<string, unknown>;
}

export const getMissingInvoiceTransactionsSchema: Schema<GetMissingInvoiceTransactions> = lazy(
  () =>
    typedExpandoObject(
      {
        status: ['status', string()],
        data: ['data', data11Schema],
        message: ['message', string()],
        reqId: ['reqId', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
