/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data12, data12Schema } from './data12.js';

export interface GetSettlementData {
  status: string;
  data: Data12;
  reqId: string;
  additionalProperties?: Record<string, unknown>;
}

export const getSettlementDataSchema: Schema<GetSettlementData> = lazy(() =>
  typedExpandoObject(
    {
      status: ['status', string()],
      data: ['data', data12Schema],
      reqId: ['reqId', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
