/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  BeneficiaryDetail4,
  beneficiaryDetail4Schema,
} from './beneficiaryDetail4.js';
import { Client86, client86Schema } from './client86.js';
import { StatusHistory, statusHistorySchema } from './statusHistory.js';

export interface GetStatus {
  payoutId: string;
  client: Client86;
  updatedOn: number;
  payoutMethod: string;
  beneficiaryDetail: BeneficiaryDetail4;
  amountUnit: string;
  amount: number;
  errorMsg: string;
  purpose: string;
  createdOn: number;
  merchantRef: string;
  status: string;
  statusHistory: StatusHistory[];
  currency: string;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const getStatusSchema: Schema<GetStatus> = lazy(() =>
  typedExpandoObject(
    {
      payoutId: ['payoutId', string()],
      client: ['client', client86Schema],
      updatedOn: ['updated_on', number()],
      payoutMethod: ['payoutMethod', string()],
      beneficiaryDetail: ['beneficiaryDetail', beneficiaryDetail4Schema],
      amountUnit: ['amountUnit', string()],
      amount: ['amount', number()],
      errorMsg: ['errorMsg', string()],
      purpose: ['purpose', string()],
      createdOn: ['created_on', number()],
      merchantRef: ['merchantRef', string()],
      status: ['status', string()],
      statusHistory: ['status_history', array(statusHistorySchema)],
      currency: ['currency', string()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
