/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data9, data9Schema } from './data9.js';

export interface GetSingleMerchant {
  status: string;
  data: Data9;
  message: string;
  reqId: string;
  additionalProperties?: Record<string, unknown>;
}

export const getSingleMerchantSchema: Schema<GetSingleMerchant> = lazy(() =>
  typedExpandoObject(
    {
      status: ['status', string()],
      data: ['data', data9Schema],
      message: ['message', string()],
      reqId: ['reqId', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
