/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  BeneficiaryDetail,
  beneficiaryDetailSchema,
} from './beneficiaryDetail.js';
import { Client37, client37Schema } from './client37.js';
import { StatusHistory, statusHistorySchema } from './statusHistory.js';

export interface GetSuccessStatus2 {
  payoutId: string;
  client: Client37;
  updatedOn: number;
  payoutMethod: string;
  beneficiaryDetail: BeneficiaryDetail;
  amountUnit: string;
  amount: number;
  errorMsg: string;
  purpose: string;
  createdOn: number;
  merchantRef: string;
  merchantName: string;
  status: string;
  statusHistory: StatusHistory[];
  viewedOn: number;
  currency: string;
  paymentOn: number;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const getSuccessStatus2Schema: Schema<GetSuccessStatus2> = lazy(() =>
  typedExpandoObject(
    {
      payoutId: ['payoutId', string()],
      client: ['client', client37Schema],
      updatedOn: ['updated_on', number()],
      payoutMethod: ['payoutMethod', string()],
      beneficiaryDetail: ['beneficiaryDetail', beneficiaryDetailSchema],
      amountUnit: ['amountUnit', string()],
      amount: ['amount', number()],
      errorMsg: ['errorMsg', string()],
      purpose: ['purpose', string()],
      createdOn: ['created_on', number()],
      merchantRef: ['merchantRef', string()],
      merchantName: ['merchantName', string()],
      status: ['status', string()],
      statusHistory: ['status_history', array(statusHistorySchema)],
      viewedOn: ['viewedOn', number()],
      currency: ['currency', string()],
      paymentOn: ['paymentOn', number()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
