/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  GooglepayDecryptedPayload,
  googlepayDecryptedPayloadSchema,
} from './googlepayDecryptedPayload.js';

export interface GooglepayParam1 {
  googleMerchantId: string;
  googlepayDecryptedPayload: GooglepayDecryptedPayload;
  additionalProperties?: Record<string, unknown>;
}

export const googlepayParam1Schema: Schema<GooglepayParam1> = lazy(() =>
  typedExpandoObject(
    {
      googleMerchantId: ['google_merchant_id', string()],
      googlepayDecryptedPayload: [
        'googlepay_decrypted_payload',
        googlepayDecryptedPayloadSchema,
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
