/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface GooglepayParam {
  googleMerchantId: string;
  googlepayEncryptedPayload: string;
  additionalProperties?: Record<string, unknown>;
}

export const googlepayParamSchema: Schema<GooglepayParam> = typedExpandoObject(
  {
    googleMerchantId: ['google_merchant_id', string()],
    googlepayEncryptedPayload: ['googlepay_encrypted_payload', string()],
  },
  'additionalProperties',
  optional(unknown())
);
