/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentMethodDetails,
  paymentMethodDetailsSchema,
} from './paymentMethodDetails.js';

export interface GooglepayDecryptedPayload {
  messageExpiration: string;
  messageId: string;
  paymentMethod: string;
  paymentMethodDetails: PaymentMethodDetails;
  gatewayMerchantId: string;
  additionalProperties?: Record<string, unknown>;
}

export const googlepayDecryptedPayloadSchema: Schema<GooglepayDecryptedPayload> = lazy(
  () =>
    typedExpandoObject(
      {
        messageExpiration: ['messageExpiration', string()],
        messageId: ['messageId', string()],
        paymentMethod: ['paymentMethod', string()],
        paymentMethodDetails: [
          'paymentMethodDetails',
          paymentMethodDetailsSchema,
        ],
        gatewayMerchantId: ['gatewayMerchantId', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
