/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Header {
  ephemeralPublicKey: string;
  publicKeyHash: string;
  transactionId: string;
  additionalProperties?: Record<string, unknown>;
}

export const headerSchema: Schema<Header> = typedExpandoObject(
  {
    ephemeralPublicKey: ['ephemeralPublicKey', string()],
    publicKeyHash: ['publicKeyHash', string()],
    transactionId: ['transactionId', string()],
  },
  'additionalProperties',
  optional(unknown())
);
