/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BankAccount, bankAccountSchema } from './bankAccount.js';

export interface IssuerDetails11 {
  bankAccounts: BankAccount[];
  legalName: string;
  brandName: string;
  additionalProperties?: Record<string, unknown>;
}

export const issuerDetails11Schema: Schema<IssuerDetails11> = lazy(() =>
  typedExpandoObject(
    {
      bankAccounts: ['bank_accounts', array(bankAccountSchema)],
      legalName: ['legal_name', string()],
      brandName: ['brand_name', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
