/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface IssuerDetails {
  website: string;
  legalStreetAddress: string;
  legalCountry: string;
  legalCity: string;
  legalZipCode: string;
  bankAccounts: unknown[];
  legalName: string;
  brandName: string;
  registrationNumber: string;
  taxNumber: string;
  additionalProperties?: Record<string, unknown>;
}

export const issuerDetailsSchema: Schema<IssuerDetails> = typedExpandoObject(
  {
    website: ['website', string()],
    legalStreetAddress: ['legal_street_address', string()],
    legalCountry: ['legal_country', string()],
    legalCity: ['legal_city', string()],
    legalZipCode: ['legal_zip_code', string()],
    bankAccounts: ['bank_accounts', array(unknown())],
    legalName: ['legal_name', string()],
    brandName: ['brand_name', string()],
    registrationNumber: ['registration_number', string()],
    taxNumber: ['tax_number', string()],
  },
  'additionalProperties',
  optional(unknown())
);
