/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Mandate2 {
  frequency: string;
  rule: string;
  value: string | null;
  mandateMaxAmount: string | null;
  amountVariability: string;
  endDate: string | null;
  mandateStatus: string;
  mandateId: string;
  additionalProperties?: Record<string, unknown>;
}

export const mandate2Schema: Schema<Mandate2> = typedExpandoObject(
  {
    frequency: ['frequency', string()],
    rule: ['rule', string()],
    value: ['value', nullable(string())],
    mandateMaxAmount: ['mandate_max_amount', nullable(string())],
    amountVariability: ['amount_variability', string()],
    endDate: ['end_date', nullable(string())],
    mandateStatus: ['mandate_status', string()],
    mandateId: ['mandate_id', string()],
  },
  'additionalProperties',
  optional(unknown())
);
