/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Mandate {
  mandateMaxAmount: string;
  amountVariability: string;
  startDate: string;
  endDate: string;
  frequency: string;
  rule: string;
  value: number;
  additionalProperties?: Record<string, unknown>;
}

export const mandateSchema: Schema<Mandate> = typedExpandoObject(
  {
    mandateMaxAmount: ['mandate_max_amount', string()],
    amountVariability: ['amount_variability', string()],
    startDate: ['start_date', string()],
    endDate: ['end_date', string()],
    frequency: ['frequency', string()],
    rule: ['rule', string()],
    value: ['value', number()],
  },
  'additionalProperties',
  optional(unknown())
);
