/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Metadata {
  hasSubtransactions: boolean;
  totalSubtransactions: number;
  transactionHierarchyLevel: string;
  additionalProperties?: Record<string, unknown>;
}

export const metadataSchema: Schema<Metadata> = typedExpandoObject(
  {
    hasSubtransactions: ['has_subtransactions', boolean()],
    totalSubtransactions: ['total_subtransactions', number()],
    transactionHierarchyLevel: ['transaction_hierarchy_level', string()],
  },
  'additionalProperties',
  optional(unknown())
);
