/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Names {
  netbanking: string;
  amex: string;
  master: string;
  cryptoBridge: string;
  payid: string;
  spei: string;
  discover: string;
  jcb: string;
  visa: string;
  neosurf: string;
  interacETransfer: string;
  thirdpartyUpi: string;
  virtualIban: string;
  banktransfer: string;
  diners: string;
  interacRequestMoney: string;
  upiCollect: string;
  upiQr: string;
  mobilemoney: string;
  fawryPay: string;
  virtualAccount: string;
  pix: string;
  additionalProperties?: Record<string, unknown>;
}

export const namesSchema: Schema<Names> = typedExpandoObject(
  {
    netbanking: ['NETBANKING', string()],
    amex: ['AMEX', string()],
    master: ['MASTER', string()],
    cryptoBridge: ['CRYPTO-BRIDGE', string()],
    payid: ['PAYID', string()],
    spei: ['SPEI', string()],
    discover: ['DISCOVER', string()],
    jcb: ['JCB', string()],
    visa: ['VISA', string()],
    neosurf: ['NEOSURF', string()],
    interacETransfer: ['INTERAC-E-TRANSFER', string()],
    thirdpartyUpi: ['THIRDPARTY-UPI', string()],
    virtualIban: ['VIRTUAL-IBAN', string()],
    banktransfer: ['BANKTRANSFER', string()],
    diners: ['DINERS', string()],
    interacRequestMoney: ['INTERAC-REQUEST-MONEY', string()],
    upiCollect: ['UPI-COLLECT', string()],
    upiQr: ['UPI-QR', string()],
    mobilemoney: ['MOBILEMONEY', string()],
    fawryPay: ['FawryPay', string()],
    virtualAccount: ['VIRTUAL-ACCOUNT', string()],
    pix: ['PIX', string()],
  },
  'additionalProperties',
  optional(unknown())
);
