/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client17, client17Schema } from './client17.js';
import { ExtraParam7, extraParam7Schema } from './extraParam7.js';

export interface NewRequestRequest {
  client: Client17;
  purpose: string;
  currency: string;
  payoutMethod: string;
  amount: number;
  extraParam: ExtraParam7;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const newRequestRequestSchema: Schema<NewRequestRequest> = lazy(() =>
  typedExpandoObject(
    {
      client: ['client', client17Schema],
      purpose: ['purpose', string()],
      currency: ['currency', string()],
      payoutMethod: ['payoutMethod', string()],
      amount: ['amount', number()],
      extraParam: ['extraParam', extraParam7Schema],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
