/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client68, client68Schema } from './client68.js';
import { StatusHistory, statusHistorySchema } from './statusHistory.js';

export interface NewRequest {
  payoutId: string;
  client: Client68;
  updatedOn: number;
  payoutMethod: string;
  amountUnit: string;
  amount: number;
  errorMsg: string;
  purpose: string;
  createdOn: number;
  merchantRef: string;
  status: string;
  statusHistory: StatusHistory[];
  currency: string;
  paymentOn: number;
  taxAmount: number;
  taxPercent: number;
  redirectType: string;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const newRequestSchema: Schema<NewRequest> = lazy(() =>
  typedExpandoObject(
    {
      payoutId: ['payoutId', string()],
      client: ['client', client68Schema],
      updatedOn: ['updated_on', number()],
      payoutMethod: ['payoutMethod', string()],
      amountUnit: ['amountUnit', string()],
      amount: ['amount', number()],
      errorMsg: ['errorMsg', string()],
      purpose: ['purpose', string()],
      createdOn: ['created_on', number()],
      merchantRef: ['merchantRef', string()],
      status: ['status', string()],
      statusHistory: ['status_history', array(statusHistorySchema)],
      currency: ['currency', string()],
      paymentOn: ['paymentOn', number()],
      taxAmount: ['taxAmount', number()],
      taxPercent: ['taxPercent', number()],
      redirectType: ['redirectType', string()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
