/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Pagination {
  currentPage: number;
  pageSize: number;
  totalElements: number;
  totalPages: number;
  first: boolean;
  last: boolean;
  hasNext: boolean;
  hasPrevious: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const paginationSchema: Schema<Pagination> = typedExpandoObject(
  {
    currentPage: ['currentPage', number()],
    pageSize: ['pageSize', number()],
    totalElements: ['totalElements', number()],
    totalPages: ['totalPages', number()],
    first: ['first', boolean()],
    last: ['last', boolean()],
    hasNext: ['hasNext', boolean()],
    hasPrevious: ['hasPrevious', boolean()],
  },
  'additionalProperties',
  optional(unknown())
);
