/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PartialRefundApiRequest {
  amount: string;
  reason: string;
  additionalProperties?: Record<string, unknown>;
}

export const partialRefundApiRequestSchema: Schema<PartialRefundApiRequest> = typedExpandoObject(
  { amount: ['amount', string()], reason: ['reason', string()] },
  'additionalProperties',
  optional(unknown())
);
