/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PauseMandateRequest {
  mandateId: string;
  command: string;
  pauseStartDate: string;
  pauseEndDate: string;
  additionalProperties?: Record<string, unknown>;
}

export const pauseMandateRequestSchema: Schema<PauseMandateRequest> = typedExpandoObject(
  {
    mandateId: ['mandate_id', string()],
    command: ['command', string()],
    pauseStartDate: ['pause_start_date', string()],
    pauseEndDate: ['pause_end_date', string()],
  },
  'additionalProperties',
  optional(unknown())
);
