/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PayInDetails2 {
  type: string;
  name: string;
  emailAddress: string;
  secretQa: string;
  secretAnswer: string;
  referenceNumber: string | null;
  paymentMethod: string | null;
  transactionExpiry: string | null;
  qrCode: string | null;
  gpayUri: string | null;
  phonepeUri: string | null;
  paytmUri: string | null;
  intentUri: string | null;
  generatedLink: string | null;
  instruction: string | null;
  paymentUrl: string | null;
  script: string | null;
  clabe: string | null;
  beneficiary: string | null;
  amount: string | null;
  linkExpiresOn: string | null;
  cardExpiresOn: string | null;
  subStatus: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const payInDetails2Schema: Schema<PayInDetails2> = typedExpandoObject(
  {
    type: ['_type', string()],
    name: ['name', string()],
    emailAddress: ['emailAddress', string()],
    secretQa: ['secretQA', string()],
    secretAnswer: ['secretAnswer', string()],
    referenceNumber: ['reference_number', nullable(string())],
    paymentMethod: ['payment_method', nullable(string())],
    transactionExpiry: ['transaction_expiry', nullable(string())],
    qrCode: ['qrCode', nullable(string())],
    gpayUri: ['gpayUri', nullable(string())],
    phonepeUri: ['phonepeUri', nullable(string())],
    paytmUri: ['paytmUri', nullable(string())],
    intentUri: ['intentUri', nullable(string())],
    generatedLink: ['generatedLink', nullable(string())],
    instruction: ['instruction', nullable(string())],
    paymentUrl: ['paymentUrl', nullable(string())],
    script: ['script', nullable(string())],
    clabe: ['clabe', nullable(string())],
    beneficiary: ['beneficiary', nullable(string())],
    amount: ['amount', nullable(string())],
    linkExpiresOn: ['linkExpiresOn', nullable(string())],
    cardExpiresOn: ['cardExpiresOn', nullable(string())],
    subStatus: ['subStatus', nullable(string())],
  },
  'additionalProperties',
  optional(unknown())
);
