/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PayInDetails {
  name: string;
  emailAddress: string;
  secretQa: string;
  secretAnswer: string;
  additionalProperties?: Record<string, unknown>;
}

export const payInDetailsSchema: Schema<PayInDetails> = typedExpandoObject(
  {
    name: ['name', string()],
    emailAddress: ['emailAddress', string()],
    secretQa: ['secretQA', string()],
    secretAnswer: ['secretAnswer', string()],
  },
  'additionalProperties',
  optional(unknown())
);
