/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PayInDetails3 {
  name: string;
  emailAddress: string;
  referenceNumber: string;
  additionalProperties?: Record<string, unknown>;
}

export const payInDetails3Schema: Schema<PayInDetails3> = typedExpandoObject(
  {
    name: ['name', string()],
    emailAddress: ['emailAddress', string()],
    referenceNumber: ['reference_number', string()],
  },
  'additionalProperties',
  optional(unknown())
);
