/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PayInDetails6 {
  expirationDate: string;
  qrCode: string;
  additionalProperties?: Record<string, unknown>;
}

export const payInDetails6Schema: Schema<PayInDetails6> = typedExpandoObject(
  {
    expirationDate: ['expiration_date', string()],
    qrCode: ['qrCode', string()],
  },
  'additionalProperties',
  optional(unknown())
);
