/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PayInDetails10 {
  qrCode: string;
  gpayUri: string;
  phonepeUri: string;
  paytmUri: string;
  generatedLink: string;
  additionalProperties?: Record<string, unknown>;
}

export const payInDetails10Schema: Schema<PayInDetails10> = typedExpandoObject(
  {
    qrCode: ['qrCode', string()],
    gpayUri: ['gpayUri', string()],
    phonepeUri: ['phonepeUri', string()],
    paytmUri: ['paytmUri', string()],
    generatedLink: ['generatedLink', string()],
  },
  'additionalProperties',
  optional(unknown())
);
