/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PayInDetails7 {
  clabe: string;
  beneficiary: string;
  amount: string;
  additionalProperties?: Record<string, unknown>;
}

export const payInDetails7Schema: Schema<PayInDetails7> = typedExpandoObject(
  {
    clabe: ['clabe', string()],
    beneficiary: ['beneficiary', string()],
    amount: ['amount', string()],
  },
  'additionalProperties',
  optional(unknown())
);
