/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ByCountry, byCountrySchema } from './byCountry.js';
import { CountryNames, countryNamesSchema } from './countryNames.js';
import { Names, namesSchema } from './names.js';

export interface PaymentMethodSuccess {
  availablePaymentMethods: string[];
  byCountry: ByCountry;
  countryNames: CountryNames;
  names: Names;
  cardMethods: string[];
  additionalProperties?: Record<string, unknown>;
}

export const paymentMethodSuccessSchema: Schema<PaymentMethodSuccess> = lazy(
  () =>
    typedExpandoObject(
      {
        availablePaymentMethods: ['available_payment_methods', array(string())],
        byCountry: ['by_country', byCountrySchema],
        countryNames: ['country_names', countryNamesSchema],
        names: ['names', namesSchema],
        cardMethods: ['card_methods', array(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
