/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Payment {
  isOutgoing: boolean;
  paymentType: string;
  amount: number;
  currency: string;
  netAmount: number;
  feeAmount: number;
  pendingAmount: number;
  pendingUnfreezeOn: string | null;
  description: string;
  paidOn: number;
  remotePaidOn: number;
  additionalProperties?: Record<string, unknown>;
}

export const paymentSchema: Schema<Payment> = typedExpandoObject(
  {
    isOutgoing: ['is_outgoing', boolean()],
    paymentType: ['payment_type', string()],
    amount: ['amount', number()],
    currency: ['currency', string()],
    netAmount: ['net_amount', number()],
    feeAmount: ['fee_amount', number()],
    pendingAmount: ['pending_amount', number()],
    pendingUnfreezeOn: ['pending_unfreeze_on', nullable(string())],
    description: ['description', string()],
    paidOn: ['paid_on', number()],
    remotePaidOn: ['remote_paid_on', number()],
  },
  'additionalProperties',
  optional(unknown())
);
