/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client45, client45Schema } from './client45.js';

export interface PayoutApiRequest {
  client: Client45;
  purpose: string;
  currency: string;
  payoutMethod: string;
  brandId: string;
  amount: number;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const payoutApiRequestSchema: Schema<PayoutApiRequest> = lazy(() =>
  typedExpandoObject(
    {
      client: ['client', client45Schema],
      purpose: ['purpose', string()],
      currency: ['currency', string()],
      payoutMethod: ['payoutMethod', string()],
      brandId: ['brand_id', string()],
      amount: ['amount', number()],
      successRedirect: ['success_redirect', string()],
      pendingRedirect: ['pending_redirect', string()],
      failureRedirect: ['failure_redirect', string()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
