/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PayOutDetails3 {
  instruction: string;
  additionalProperties?: Record<string, unknown>;
}

export const payOutDetails3Schema: Schema<PayOutDetails3> = typedExpandoObject(
  { instruction: ['instruction', string()] },
  'additionalProperties',
  optional(unknown())
);
