/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client67, client67Schema } from './client67.js';

export interface PayoutApiRequest1 {
  client: Client67;
  purpose: string;
  currency: string;
  payoutMethod: string;
  amount: number;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const payoutApiRequest1Schema: Schema<PayoutApiRequest1> = lazy(() =>
  typedExpandoObject(
    {
      client: ['client', client67Schema],
      purpose: ['purpose', string()],
      currency: ['currency', string()],
      payoutMethod: ['payoutMethod', string()],
      amount: ['amount', number()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
