/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PayoutSession {
  sessionUrl: string;
  brandId: string;
  customerId: string;
  sessionId: string;
  expiryOn: number;
  createdOn: number;
  additionalProperties?: Record<string, unknown>;
}

export const payoutSessionSchema: Schema<PayoutSession> = typedExpandoObject(
  {
    sessionUrl: ['sessionUrl', string()],
    brandId: ['brandId', string()],
    customerId: ['customerId', string()],
    sessionId: ['sessionId', string()],
    expiryOn: ['expiryOn', number()],
    createdOn: ['createdOn', number()],
  },
  'additionalProperties',
  optional(unknown())
);
