/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ExtraParam21, extraParam21Schema } from './extraParam21.js';
import { Product, productSchema } from './product.js';

export interface PayoutSessionRequest {
  customerId: string;
  currency: string;
  products: Product[];
  totalAmount: string;
  taxAmount: string;
  taxPercent: string;
  type: string;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  successCallback: string;
  failureCallback: string;
  extraParam: ExtraParam21;
  additionalProperties?: Record<string, unknown>;
}

export const payoutSessionRequestSchema: Schema<PayoutSessionRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        customerId: ['customerId', string()],
        currency: ['currency', string()],
        products: ['products', array(productSchema)],
        totalAmount: ['totalAmount', string()],
        taxAmount: ['tax_amount', string()],
        taxPercent: ['tax_percent', string()],
        type: ['type', string()],
        successRedirect: ['success_redirect', string()],
        pendingRedirect: ['pending_redirect', string()],
        failureRedirect: ['failure_redirect', string()],
        successCallback: ['success_callback', string()],
        failureCallback: ['failure_callback', string()],
        extraParam: ['extraParam', extraParam21Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
