/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PixPayload {
  payload: string;
  qrCode: string;
  expirationDate: string;
  additionalProperties?: Record<string, unknown>;
}

export const pixPayloadSchema: Schema<PixPayload> = typedExpandoObject(
  {
    payload: ['payload', string()],
    qrCode: ['qr_code', string()],
    expirationDate: ['expiration_date', string()],
  },
  'additionalProperties',
  optional(unknown())
);
