/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Product49 {
  name: string;
  quantity: number;
  price: number;
  discount: number;
  taxPercent: string;
  additionalProperties?: Record<string, unknown>;
}

export const product49Schema: Schema<Product49> = typedExpandoObject(
  {
    name: ['name', string()],
    quantity: ['quantity', number()],
    price: ['price', number()],
    discount: ['discount', number()],
    taxPercent: ['tax_percent', string()],
  },
  'additionalProperties',
  optional(unknown())
);
