/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Product48 {
  name: string;
  price: number;
  additionalProperties?: Record<string, unknown>;
}

export const product48Schema: Schema<Product48> = typedExpandoObject(
  { name: ['name', string()], price: ['price', number()] },
  'additionalProperties',
  optional(unknown())
);
