/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Product17 {
  price: number;
  additionalProperties?: Record<string, unknown>;
}

export const product17Schema: Schema<Product17> = typedExpandoObject(
  { price: ['price', number()] },
  'additionalProperties',
  optional(unknown())
);
