/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Product {
  name: string;
  price: string;
  additionalProperties?: Record<string, unknown>;
}

export const productSchema: Schema<Product> = typedExpandoObject(
  { name: ['name', string()], price: ['price', string()] },
  'additionalProperties',
  optional(unknown())
);
