/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client65, client65Schema } from './client65.js';
import { Purchase52, purchase52Schema } from './purchase52.js';

export interface PurchaseRequest4 {
  client: Client65;
  purchase: Purchase52;
  status: string;
  brandId: string;
  skipCapture: boolean;
  merchantRef: string;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const purchaseRequest4Schema: Schema<PurchaseRequest4> = lazy(() =>
  typedExpandoObject(
    {
      client: ['client', client65Schema],
      purchase: ['purchase', purchase52Schema],
      status: ['status', string()],
      brandId: ['brand_id', string()],
      skipCapture: ['skip_capture', boolean()],
      merchantRef: ['merchantRef', string()],
      successRedirect: ['success_redirect', string()],
      pendingRedirect: ['pending_redirect', string()],
      failureRedirect: ['failure_redirect', string()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
