/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client7, client7Schema } from './client7.js';
import { Purchase55, purchase55Schema } from './purchase55.js';

export interface PurchaseRequest2 {
  client: Client7;
  purchase: Purchase55;
  paymentMethod: string;
  brandId: string;
  merchantRef: string;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const purchaseRequest2Schema: Schema<PurchaseRequest2> = lazy(() =>
  typedExpandoObject(
    {
      client: ['client', client7Schema],
      purchase: ['purchase', purchase55Schema],
      paymentMethod: ['paymentMethod', string()],
      brandId: ['brand_id', string()],
      merchantRef: ['merchantRef', string()],
      successRedirect: ['success_redirect', string()],
      pendingRedirect: ['pending_redirect', string()],
      failureRedirect: ['failure_redirect', string()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
