/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client24, client24Schema } from './client24.js';
import { IssuerDetails11, issuerDetails11Schema } from './issuerDetails11.js';
import { PixPayload, pixPayloadSchema } from './pixPayload.js';
import { Purchase16, purchase16Schema } from './purchase16.js';
import { StatusHistory, statusHistorySchema } from './statusHistory.js';

export interface PurchaseSuccess2 {
  purchaseId: string;
  client: Client24;
  updatedOn: number;
  type: string;
  paymentMethod: string;
  amountUnit: string;
  errorMsg: string;
  redirectType: string;
  forceRecurring: boolean;
  createdOn: number;
  merchantRef: string;
  merchantName: string;
  purchase: Purchase16;
  issuerDetails: IssuerDetails11;
  transactionData?: unknown;
  status: string;
  statusHistory: StatusHistory[];
  pixPayload: PixPayload;
  isTest: boolean;
  brandId: string;
  sendReceipt: boolean;
  isRecurringToken: boolean;
  skipCapture: boolean;
  referenceGenerated: string;
  issued: string;
  due: number;
  refundUpto: number;
  ccDescriptor: string;
  fraudScore: string;
  trustScore: string;
  refundAvailability: string;
  refundableAmount: number;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  successCallback: string;
  failureCallback: string;
  platform: string;
  createdFromIp: string;
  checkoutUrl: string;
  payoutProcess: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const purchaseSuccess2Schema: Schema<PurchaseSuccess2> = lazy(() =>
  typedExpandoObject(
    {
      purchaseId: ['purchaseId', string()],
      client: ['client', client24Schema],
      updatedOn: ['updated_on', number()],
      type: ['type', string()],
      paymentMethod: ['paymentMethod', string()],
      amountUnit: ['amountUnit', string()],
      errorMsg: ['errorMsg', string()],
      redirectType: ['redirectType', string()],
      forceRecurring: ['force_recurring', boolean()],
      createdOn: ['created_on', number()],
      merchantRef: ['merchantRef', string()],
      merchantName: ['merchantName', string()],
      purchase: ['purchase', purchase16Schema],
      issuerDetails: ['issuer_details', issuerDetails11Schema],
      transactionData: ['transaction_data', optional(unknown())],
      status: ['status', string()],
      statusHistory: ['status_history', array(statusHistorySchema)],
      pixPayload: ['pix_payload', pixPayloadSchema],
      isTest: ['is_test', boolean()],
      brandId: ['brand_id', string()],
      sendReceipt: ['send_receipt', boolean()],
      isRecurringToken: ['is_recurring_token', boolean()],
      skipCapture: ['skip_capture', boolean()],
      referenceGenerated: ['reference_generated', string()],
      issued: ['issued', string()],
      due: ['due', number()],
      refundUpto: ['refund_upto', number()],
      ccDescriptor: ['cc_descriptor', string()],
      fraudScore: ['fraudScore', string()],
      trustScore: ['trustScore', string()],
      refundAvailability: ['refund_availability', string()],
      refundableAmount: ['refundable_amount', number()],
      successRedirect: ['success_redirect', string()],
      pendingRedirect: ['pending_redirect', string()],
      failureRedirect: ['failure_redirect', string()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
      platform: ['platform', string()],
      createdFromIp: ['created_from_ip', string()],
      checkoutUrl: ['checkout_url', string()],
      payoutProcess: ['payoutProcess', boolean()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
