/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client8, client8Schema } from './client8.js';
import { ExtraParam6, extraParam6Schema } from './extraParam6.js';
import { Purchase7, purchase7Schema } from './purchase7.js';

export interface PurchasesRequest8 {
  client: Client8;
  purchase: Purchase7;
  extraParam: ExtraParam6;
  paymentMethod: string;
  brandId: string;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const purchasesRequest8Schema: Schema<PurchasesRequest8> = lazy(() =>
  typedExpandoObject(
    {
      client: ['client', client8Schema],
      purchase: ['purchase', purchase7Schema],
      extraParam: ['extraParam', extraParam6Schema],
      paymentMethod: ['paymentMethod', string()],
      brandId: ['brand_id', string()],
      successRedirect: ['success_redirect', string()],
      pendingRedirect: ['pending_redirect', string()],
      failureRedirect: ['failure_redirect', string()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
