/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client65, client65Schema } from './client65.js';
import { Purchase, purchaseSchema } from './purchase.js';

export interface PurchasesRequest9 {
  client: Client65;
  purchase: Purchase;
  paymentMethod: string;
  brandId: string;
  sendReceipt: string;
  skipCapture: string;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const purchasesRequest9Schema: Schema<PurchasesRequest9> = lazy(() =>
  typedExpandoObject(
    {
      client: ['client', client65Schema],
      purchase: ['purchase', purchaseSchema],
      paymentMethod: ['paymentMethod', string()],
      brandId: ['brand_id', string()],
      sendReceipt: ['send_receipt', string()],
      skipCapture: ['skip_capture', string()],
      successRedirect: ['success_redirect', string()],
      pendingRedirect: ['pending_redirect', string()],
      failureRedirect: ['failure_redirect', string()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
