/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Product48, product48Schema } from './product48.js';

export interface Purchase48 {
  currency: string;
  products: Product48[];
  additionalProperties?: Record<string, unknown>;
}

export const purchase48Schema: Schema<Purchase48> = lazy(() =>
  typedExpandoObject(
    {
      currency: ['currency', string()],
      products: ['products', array(product48Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
