/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client8, client8Schema } from './client8.js';
import { ExtraParam8, extraParam8Schema } from './extraParam8.js';
import { Purchase48, purchase48Schema } from './purchase48.js';

export interface PurchasesRequest11 {
  client: Client8;
  purchase: Purchase48;
  paymentMethod: string;
  brandId: string;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  successCallback: string;
  failureCallback: string;
  extraParam: ExtraParam8;
  additionalProperties?: Record<string, unknown>;
}

export const purchasesRequest11Schema: Schema<PurchasesRequest11> = lazy(() =>
  typedExpandoObject(
    {
      client: ['client', client8Schema],
      purchase: ['purchase', purchase48Schema],
      paymentMethod: ['paymentMethod', string()],
      brandId: ['brand_id', string()],
      successRedirect: ['success_redirect', string()],
      pendingRedirect: ['pending_redirect', string()],
      failureRedirect: ['failure_redirect', string()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
      extraParam: ['extraParam', extraParam8Schema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
