/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ExtraParam20, extraParam20Schema } from './extraParam20.js';
import { Product, productSchema } from './product.js';

export interface PurchaseSessionRequest {
  customerId: string;
  merchantRef: string;
  currency: string;
  products: Product[];
  totalAmount: string;
  paymentMethod: string;
  successRedirect: string;
  failureRedirect: string;
  pendingRedirect: string;
  successCallback: string;
  failureCallback: string;
  extraParam: ExtraParam20;
  additionalProperties?: Record<string, unknown>;
}

export const purchaseSessionRequestSchema: Schema<PurchaseSessionRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        customerId: ['customerId', string()],
        merchantRef: ['merchantRef', string()],
        currency: ['currency', string()],
        products: ['products', array(productSchema)],
        totalAmount: ['totalAmount', string()],
        paymentMethod: ['paymentMethod', string()],
        successRedirect: ['success_redirect', string()],
        failureRedirect: ['failure_redirect', string()],
        pendingRedirect: ['pending_redirect', string()],
        successCallback: ['success_callback', string()],
        failureCallback: ['failure_callback', string()],
        extraParam: ['extraParam', extraParam20Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
