/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Product2, product2Schema } from './product2.js';

export interface Purchase47 {
  currency: string;
  products: Product2[];
  total: number;
  language: string;
  notes: string;
  debt: number;
  totalFormatted: number;
  taxAmount: number;
  taxPercent: number;
  requestClientDetails: string[];
  timezone: string;
  emailMessage: string;
  additionalProperties?: Record<string, unknown>;
}

export const purchase47Schema: Schema<Purchase47> = lazy(() =>
  typedExpandoObject(
    {
      currency: ['currency', string()],
      products: ['products', array(product2Schema)],
      total: ['total', number()],
      language: ['language', string()],
      notes: ['notes', string()],
      debt: ['debt', number()],
      totalFormatted: ['total_formatted', number()],
      taxAmount: ['taxAmount', number()],
      taxPercent: ['taxPercent', number()],
      requestClientDetails: ['request_client_details', array(string())],
      timezone: ['timezone', string()],
      emailMessage: ['email_message', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
