/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Product17, product17Schema } from './product17.js';

export interface Purchase17 {
  currency: string;
  products: Product17[];
  total: number;
  language: string;
  totalFormatted: number;
  timezone: string;
  additionalProperties?: Record<string, unknown>;
}

export const purchase17Schema: Schema<Purchase17> = lazy(() =>
  typedExpandoObject(
    {
      currency: ['currency', string()],
      products: ['products', array(product17Schema)],
      total: ['total', number()],
      language: ['language', string()],
      totalFormatted: ['total_formatted', number()],
      timezone: ['timezone', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
