/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Product7, product7Schema } from './product7.js';

export interface Purchase10 {
  currency: string;
  products: Product7[];
  additionalProperties?: Record<string, unknown>;
}

export const purchase10Schema: Schema<Purchase10> = lazy(() =>
  typedExpandoObject(
    {
      currency: ['currency', string()],
      products: ['products', array(product7Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
