/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Product, productSchema } from './product.js';

export interface Purchase {
  currency: string;
  products: Product[];
  additionalProperties?: Record<string, unknown>;
}

export const purchaseSchema: Schema<Purchase> = lazy(() =>
  typedExpandoObject(
    {
      currency: ['currency', string()],
      products: ['products', array(productSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
