/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client70, client70Schema } from './client70.js';
import { IssuerDetails, issuerDetailsSchema } from './issuerDetails.js';
import { Purchase47, purchase47Schema } from './purchase47.js';
import { StatusHistory, statusHistorySchema } from './statusHistory.js';
import { TransactionData, transactionDataSchema } from './transactionData.js';

export interface PurchaseSucess {
  purchaseId: string;
  client: Client70;
  updatedOn: number;
  type: string;
  paymentMethod: string;
  amountUnit: string;
  errorMsg: string;
  redirectType: string;
  forceRecurring: boolean;
  createdOn: number;
  merchantRef: string;
  merchantName: string;
  purchase: Purchase47;
  issuerDetails: IssuerDetails;
  transactionData: TransactionData;
  status: string;
  statusHistory: StatusHistory[];
  isTest: boolean;
  brandId: string;
  sendReceipt: boolean;
  isRecurringToken: boolean;
  skipCapture: boolean;
  referenceGenerated: string;
  issued: string;
  due: number;
  refundUpto: number;
  ccDescriptor: string;
  fraudScore: string;
  trustScore: string;
  paidOn: number;
  refundAvailability: string;
  refundableAmount: number;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  cancelRedirect: string;
  successCallback: string;
  failureCallback: string;
  platform: string;
  createdFromIp: string;
  checkoutUrl: string;
  payoutProcess: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const purchaseSucessSchema: Schema<PurchaseSucess> = lazy(() =>
  typedExpandoObject(
    {
      purchaseId: ['purchaseId', string()],
      client: ['client', client70Schema],
      updatedOn: ['updated_on', number()],
      type: ['type', string()],
      paymentMethod: ['paymentMethod', string()],
      amountUnit: ['amountUnit', string()],
      errorMsg: ['errorMsg', string()],
      redirectType: ['redirectType', string()],
      forceRecurring: ['force_recurring', boolean()],
      createdOn: ['created_on', number()],
      merchantRef: ['merchantRef', string()],
      merchantName: ['merchantName', string()],
      purchase: ['purchase', purchase47Schema],
      issuerDetails: ['issuer_details', issuerDetailsSchema],
      transactionData: ['transaction_data', transactionDataSchema],
      status: ['status', string()],
      statusHistory: ['status_history', array(statusHistorySchema)],
      isTest: ['is_test', boolean()],
      brandId: ['brand_id', string()],
      sendReceipt: ['send_receipt', boolean()],
      isRecurringToken: ['is_recurring_token', boolean()],
      skipCapture: ['skip_capture', boolean()],
      referenceGenerated: ['reference_generated', string()],
      issued: ['issued', string()],
      due: ['due', number()],
      refundUpto: ['refund_upto', number()],
      ccDescriptor: ['cc_descriptor', string()],
      fraudScore: ['fraudScore', string()],
      trustScore: ['trustScore', string()],
      paidOn: ['paidOn', number()],
      refundAvailability: ['refund_availability', string()],
      refundableAmount: ['refundable_amount', number()],
      successRedirect: ['success_redirect', string()],
      pendingRedirect: ['pending_redirect', string()],
      failureRedirect: ['failure_redirect', string()],
      cancelRedirect: ['cancel_redirect', string()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
      platform: ['platform', string()],
      createdFromIp: ['created_from_ip', string()],
      checkoutUrl: ['checkout_url', string()],
      payoutProcess: ['payoutProcess', boolean()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
