/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client4, client4Schema } from './client4.js';
import { ExtraParam1, extraParam1Schema } from './extraParam1.js';
import { IssuerDetails, issuerDetailsSchema } from './issuerDetails.js';
import { PayInDetails3, payInDetails3Schema } from './payInDetails3.js';
import { Payment3, payment3Schema } from './payment3.js';
import { Purchase8, purchase8Schema } from './purchase8.js';
import { StatusHistory, statusHistorySchema } from './statusHistory.js';
import {
  TransactionData6,
  transactionData6Schema,
} from './transactionData6.js';

export interface PurchaseSuccess1 {
  purchaseId: string;
  client: Client4;
  updatedOn: number;
  type: string;
  paymentMethod: string;
  amountUnit: string;
  errorMsg: string;
  redirectType: string;
  forceRecurring: boolean;
  createdOn: number;
  extraParam: ExtraParam1;
  merchantRef: string;
  merchantName: string;
  purchase: Purchase8;
  payment: Payment3;
  issuerDetails: IssuerDetails;
  transactionData: TransactionData6;
  status: string;
  statusHistory: StatusHistory[];
  isTest: boolean;
  brandId: string;
  isRecurringToken: boolean;
  referenceGenerated: string;
  issued: string;
  due: number;
  refundUpto: number;
  ccDescriptor: string;
  fraudScore: string;
  trustScore: string;
  payInDetails: PayInDetails3;
  paidOn: number;
  receivedAmt: number;
  refundAvailability: string;
  refundableAmount: number;
  successRedirect: string;
  failureRedirect: string;
  cancelRedirect: string;
  successCallback: string;
  failureCallback: string;
  platform: string;
  createdFromIp: string;
  checkoutUrl: string;
  payoutProcess: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const purchaseSuccess1Schema: Schema<PurchaseSuccess1> = lazy(() =>
  typedExpandoObject(
    {
      purchaseId: ['purchaseId', string()],
      client: ['client', client4Schema],
      updatedOn: ['updated_on', number()],
      type: ['type', string()],
      paymentMethod: ['paymentMethod', string()],
      amountUnit: ['amountUnit', string()],
      errorMsg: ['errorMsg', string()],
      redirectType: ['redirectType', string()],
      forceRecurring: ['force_recurring', boolean()],
      createdOn: ['created_on', number()],
      extraParam: ['extraParam', extraParam1Schema],
      merchantRef: ['merchantRef', string()],
      merchantName: ['merchantName', string()],
      purchase: ['purchase', purchase8Schema],
      payment: ['payment', payment3Schema],
      issuerDetails: ['issuer_details', issuerDetailsSchema],
      transactionData: ['transaction_data', transactionData6Schema],
      status: ['status', string()],
      statusHistory: ['status_history', array(statusHistorySchema)],
      isTest: ['is_test', boolean()],
      brandId: ['brand_id', string()],
      isRecurringToken: ['is_recurring_token', boolean()],
      referenceGenerated: ['reference_generated', string()],
      issued: ['issued', string()],
      due: ['due', number()],
      refundUpto: ['refund_upto', number()],
      ccDescriptor: ['cc_descriptor', string()],
      fraudScore: ['fraudScore', string()],
      trustScore: ['trustScore', string()],
      payInDetails: ['payInDetails', payInDetails3Schema],
      paidOn: ['paidOn', number()],
      receivedAmt: ['receivedAmt', number()],
      refundAvailability: ['refund_availability', string()],
      refundableAmount: ['refundable_amount', number()],
      successRedirect: ['success_redirect', string()],
      failureRedirect: ['failure_redirect', string()],
      cancelRedirect: ['cancel_redirect', string()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
      platform: ['platform', string()],
      createdFromIp: ['created_from_ip', string()],
      checkoutUrl: ['checkout_url', string()],
      payoutProcess: ['payoutProcess', boolean()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
