/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client57, client57Schema } from './client57.js';
import { ExtraParam5, extraParam5Schema } from './extraParam5.js';
import { Purchase, purchaseSchema } from './purchase.js';

export interface PurchasesDecryptedFlowRequest1 {
  client: Client57;
  purchase: Purchase;
  paymentMethod: string;
  brandId: string;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  extraParam: ExtraParam5;
  additionalProperties?: Record<string, unknown>;
}

export const purchasesDecryptedFlowRequest1Schema: Schema<PurchasesDecryptedFlowRequest1> = lazy(
  () =>
    typedExpandoObject(
      {
        client: ['client', client57Schema],
        purchase: ['purchase', purchaseSchema],
        paymentMethod: ['paymentMethod', string()],
        brandId: ['brand_id', string()],
        successRedirect: ['success_redirect', string()],
        pendingRedirect: ['pending_redirect', string()],
        failureRedirect: ['failure_redirect', string()],
        extraParam: ['extraParam', extraParam5Schema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
