/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client24, client24Schema } from './client24.js';
import { Purchase10, purchase10Schema } from './purchase10.js';

export interface PurchasesRequest2 {
  client: Client24;
  purchase: Purchase10;
  paymentMethod: string;
  merchantRef: string;
  brandId: string;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  successCallback: string;
  failureCallback: string;
  additionalProperties?: Record<string, unknown>;
}

export const purchasesRequest2Schema: Schema<PurchasesRequest2> = lazy(() =>
  typedExpandoObject(
    {
      client: ['client', client24Schema],
      purchase: ['purchase', purchase10Schema],
      paymentMethod: ['paymentMethod', string()],
      merchantRef: ['merchantRef', string()],
      brandId: ['brand_id', string()],
      successRedirect: ['success_redirect', string()],
      pendingRedirect: ['pending_redirect', string()],
      failureRedirect: ['failure_redirect', string()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
