/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface RefundExceedsRemainingBalanceAfterAPartialRefund1 {
  message: string;
  code: string;
  additionalProperties?: Record<string, unknown>;
}

export const refundExceedsRemainingBalanceAfterAPartialRefund1Schema: Schema<RefundExceedsRemainingBalanceAfterAPartialRefund1> = typedExpandoObject(
  { message: ['message', string()], code: ['code', string()] },
  'additionalProperties',
  optional(unknown())
);
