/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface RejectPayoutWithRemarksRequest {
  remarks: string;
  additionalProperties?: Record<string, unknown>;
}

export const rejectPayoutWithRemarksRequestSchema: Schema<RejectPayoutWithRemarksRequest> = typedExpandoObject(
  { remarks: ['remarks', string()] },
  'additionalProperties',
  optional(unknown())
);
