/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface RequestGlobalAccountRequest {
  country: string;
  currency: string;
  additionalProperties?: Record<string, unknown>;
}

export const requestGlobalAccountRequestSchema: Schema<RequestGlobalAccountRequest> = typedExpandoObject(
  { country: ['country', string()], currency: ['currency', string()] },
  'additionalProperties',
  optional(unknown())
);
