/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Requiredinput {
  ip: string;
  email: string;
  url: string;
  additionalProperties?: Record<string, unknown>;
}

export const requiredinputSchema: Schema<Requiredinput> = typedExpandoObject(
  { ip: ['ip', string()], email: ['email', string()], url: ['url', string()] },
  'additionalProperties',
  optional(unknown())
);
