/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface S2Srequest {
  cardholderName: string;
  cardNumber: string;
  expires: string;
  cvc: string;
  rememberCard: string;
  remoteIp: string;
  userAgent: string;
  acceptHeader: string;
  language: string;
  javaEnabled: boolean;
  javascriptEnabled: boolean;
  colorDepth: number;
  utcOffset: number;
  screenWidth: number;
  screenHeight: number;
  additionalProperties?: Record<string, unknown>;
}

export const s2SrequestSchema: Schema<S2Srequest> = typedExpandoObject(
  {
    cardholderName: ['cardholder_name', string()],
    cardNumber: ['card_number', string()],
    expires: ['expires', string()],
    cvc: ['cvc', string()],
    rememberCard: ['remember_card', string()],
    remoteIp: ['remote_ip', string()],
    userAgent: ['user_agent', string()],
    acceptHeader: ['accept_header', string()],
    language: ['language', string()],
    javaEnabled: ['java_enabled', boolean()],
    javascriptEnabled: ['javascript_enabled', boolean()],
    colorDepth: ['color_depth', number()],
    utcOffset: ['utc_offset', number()],
    screenWidth: ['screen_width', number()],
    screenHeight: ['screen_height', number()],
  },
  'additionalProperties',
  optional(unknown())
);
