/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Settlement {
  settlementId: string;
  amount: number;
  currency: string;
  status: string;
  settledOn: number;
  additionalProperties?: Record<string, unknown>;
}

export const settlementSchema: Schema<Settlement> = typedExpandoObject(
  {
    settlementId: ['settlementId', string()],
    amount: ['amount', number()],
    currency: ['currency', string()],
    status: ['status', string()],
    settledOn: ['settledOn', number()],
  },
  'additionalProperties',
  optional(unknown())
);
