/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface StatusHistory8 {
  type: string;
  status: string;
  timestamp: number;
  updatedBy: string | null;
  paidReason: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const statusHistory8Schema: Schema<StatusHistory8> = typedExpandoObject(
  {
    type: ['_type', string()],
    status: ['status', string()],
    timestamp: ['timestamp', number()],
    updatedBy: ['updatedBy', nullable(string())],
    paidReason: ['paidReason', nullable(string())],
  },
  'additionalProperties',
  optional(unknown())
);
