/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Success39 {
  mandateId: string;
  message: string;
  revokeDate: number;
  status: string;
  additionalProperties?: Record<string, unknown>;
}

export const success39Schema: Schema<Success39> = typedExpandoObject(
  {
    mandateId: ['mandateId', string()],
    message: ['message', string()],
    revokeDate: ['revokeDate', number()],
    status: ['status', string()],
  },
  'additionalProperties',
  optional(unknown())
);
