/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client6, client6Schema } from './client6.js';
import { IssuerDetails1, issuerDetails1Schema } from './issuerDetails1.js';
import { Purchase2, purchase2Schema } from './purchase2.js';
import { StatusHistory, statusHistorySchema } from './statusHistory.js';
import { TransactionData, transactionDataSchema } from './transactionData.js';

export interface Success2 {
  purchaseId: string;
  client: Client6;
  updatedOn: number;
  type: string;
  forceRecurring: boolean;
  createdOn: number;
  purchase: Purchase2;
  issuerDetails: IssuerDetails1;
  transactionData: TransactionData;
  status: string;
  statusHistory: StatusHistory[];
  isTest: boolean;
  brandId: string;
  sendReceipt: boolean;
  isRecurringToken: boolean;
  skipCapture: boolean;
  referenceGenerated: string;
  issued: string;
  due: number;
  refundUpto: number;
  ccDescriptor: string;
  refundAvailability: string;
  refundableAmount: number;
  successRedirect: string;
  failureRedirect: string;
  cancelRedirect: string;
  successCallback: string;
  platform: string;
  createdFromIp: string;
  checkoutUrl: string;
  directPostUrl: string;
  additionalProperties?: Record<string, unknown>;
}

export const success2Schema: Schema<Success2> = lazy(() =>
  typedExpandoObject(
    {
      purchaseId: ['purchaseId', string()],
      client: ['client', client6Schema],
      updatedOn: ['updated_on', number()],
      type: ['type', string()],
      forceRecurring: ['force_recurring', boolean()],
      createdOn: ['created_on', number()],
      purchase: ['purchase', purchase2Schema],
      issuerDetails: ['issuer_details', issuerDetails1Schema],
      transactionData: ['transaction_data', transactionDataSchema],
      status: ['status', string()],
      statusHistory: ['status_history', array(statusHistorySchema)],
      isTest: ['is_test', boolean()],
      brandId: ['brand_id', string()],
      sendReceipt: ['send_receipt', boolean()],
      isRecurringToken: ['is_recurring_token', boolean()],
      skipCapture: ['skip_capture', boolean()],
      referenceGenerated: ['reference_generated', string()],
      issued: ['issued', string()],
      due: ['due', number()],
      refundUpto: ['refund_upto', number()],
      ccDescriptor: ['cc_descriptor', string()],
      refundAvailability: ['refund_availability', string()],
      refundableAmount: ['refundable_amount', number()],
      successRedirect: ['success_redirect', string()],
      failureRedirect: ['failure_redirect', string()],
      cancelRedirect: ['cancel_redirect', string()],
      successCallback: ['success_callback', string()],
      platform: ['platform', string()],
      createdFromIp: ['created_from_ip', string()],
      checkoutUrl: ['checkout_url', string()],
      directPostUrl: ['direct_post_url', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
