/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Success46 {
  cardLastFour: string;
  tokenReference: string;
  additionalProperties?: Record<string, unknown>;
}

export const success46Schema: Schema<Success46> = typedExpandoObject(
  {
    cardLastFour: ['card_last_four', string()],
    tokenReference: ['token_reference', string()],
  },
  'additionalProperties',
  optional(unknown())
);
