/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Mandate4, mandate4Schema } from './mandate4.js';

export interface Success40 {
  mandates: Mandate4[];
  additionalProperties?: Record<string, unknown>;
}

export const success40Schema: Schema<Success40> = lazy(() =>
  typedExpandoObject(
    { mandates: ['mandates', array(mandate4Schema)] },
    'additionalProperties',
    optional(unknown())
  )
);
