/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Success49 {
  message: string;
  additionalProperties?: Record<string, unknown>;
}

export const success49Schema: Schema<Success49> = typedExpandoObject(
  { message: ['message', string()] },
  'additionalProperties',
  optional(unknown())
);
