/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Datum, datumSchema } from './datum.js';

export interface Success24 {
  paymentMethod: string;
  status: string;
  data: Datum[];
  additionalProperties?: Record<string, unknown>;
}

export const success24Schema: Schema<Success24> = lazy(() =>
  typedExpandoObject(
    {
      paymentMethod: ['paymentMethod', string()],
      status: ['status', string()],
      data: ['data', array(datumSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
