/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Client26, client26Schema } from './client26.js';
import { IssuerDetails11, issuerDetails11Schema } from './issuerDetails11.js';
import { Purchase17, purchase17Schema } from './purchase17.js';
import { StatusHistory, statusHistorySchema } from './statusHistory.js';

export interface Success7 {
  purchaseId: string;
  client: Client26;
  updatedOn: number;
  type: string;
  paymentMethod: string;
  amountUnit: string;
  errorMsg: string;
  redirectType: string;
  forceRecurring: boolean;
  createdOn: number;
  merchantRef: string;
  merchantName: string;
  purchase: Purchase17;
  issuerDetails: IssuerDetails11;
  transactionData?: unknown;
  status: string;
  statusHistory: StatusHistory[];
  isTest: boolean;
  brandId: string;
  sendReceipt: boolean;
  isRecurringToken: boolean;
  skipCapture: boolean;
  referenceGenerated: string;
  issued: string;
  due: number;
  refundUpto: number;
  ccDescriptor: string;
  fraudScore: string;
  trustScore: string;
  refundAvailability: string;
  refundableAmount: number;
  successRedirect: string;
  pendingRedirect: string;
  failureRedirect: string;
  cancelRedirect: string;
  successCallback: string;
  failureCallback: string;
  platform: string;
  createdFromIp: string;
  checkoutUrl: string;
  additionalProperties?: Record<string, unknown>;
}

export const success7Schema: Schema<Success7> = lazy(() =>
  typedExpandoObject(
    {
      purchaseId: ['purchaseId', string()],
      client: ['client', client26Schema],
      updatedOn: ['updated_on', number()],
      type: ['type', string()],
      paymentMethod: ['paymentMethod', string()],
      amountUnit: ['amountUnit', string()],
      errorMsg: ['errorMsg', string()],
      redirectType: ['redirectType', string()],
      forceRecurring: ['force_recurring', boolean()],
      createdOn: ['created_on', number()],
      merchantRef: ['merchantRef', string()],
      merchantName: ['merchantName', string()],
      purchase: ['purchase', purchase17Schema],
      issuerDetails: ['issuer_details', issuerDetails11Schema],
      transactionData: ['transaction_data', optional(unknown())],
      status: ['status', string()],
      statusHistory: ['status_history', array(statusHistorySchema)],
      isTest: ['is_test', boolean()],
      brandId: ['brand_id', string()],
      sendReceipt: ['send_receipt', boolean()],
      isRecurringToken: ['is_recurring_token', boolean()],
      skipCapture: ['skip_capture', boolean()],
      referenceGenerated: ['reference_generated', string()],
      issued: ['issued', string()],
      due: ['due', number()],
      refundUpto: ['refund_upto', number()],
      ccDescriptor: ['cc_descriptor', string()],
      fraudScore: ['fraudScore', string()],
      trustScore: ['trustScore', string()],
      refundAvailability: ['refund_availability', string()],
      refundableAmount: ['refundable_amount', number()],
      successRedirect: ['success_redirect', string()],
      pendingRedirect: ['pending_redirect', string()],
      failureRedirect: ['failure_redirect', string()],
      cancelRedirect: ['cancel_redirect', string()],
      successCallback: ['success_callback', string()],
      failureCallback: ['failure_callback', string()],
      platform: ['platform', string()],
      createdFromIp: ['created_from_ip', string()],
      checkoutUrl: ['checkout_url', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
