/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ToAddress {
  symbol: string;
  networkName: string;
  address: string;
  additionalProperties?: Record<string, unknown>;
}

export const toAddressSchema: Schema<ToAddress> = typedExpandoObject(
  {
    symbol: ['symbol', string()],
    networkName: ['networkName', string()],
    address: ['address', string()],
  },
  'additionalProperties',
  optional(unknown())
);
