/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TransactionData {
  paymentMethod: string;
  flow: string;
  extra?: unknown;
  country: string;
  attempts: string[];
  additionalProperties?: Record<string, unknown>;
}

export const transactionDataSchema: Schema<TransactionData> = typedExpandoObject(
  {
    paymentMethod: ['payment_method', string()],
    flow: ['flow', string()],
    extra: ['extra', optional(unknown())],
    country: ['country', string()],
    attempts: ['attempts', array(string())],
  },
  'additionalProperties',
  optional(unknown())
);
