/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Attempt28, attempt28Schema } from './attempt28.js';
import { Extra52, extra52Schema } from './extra52.js';

export interface TransactionData41 {
  paymentMethod: string;
  flow: string;
  extra: Extra52;
  country: string;
  attempts: Attempt28[];
  additionalProperties?: Record<string, unknown>;
}

export const transactionData41Schema: Schema<TransactionData41> = lazy(() =>
  typedExpandoObject(
    {
      paymentMethod: ['payment_method', string()],
      flow: ['flow', string()],
      extra: ['extra', extra52Schema],
      country: ['country', string()],
      attempts: ['attempts', array(attempt28Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
