/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Attempt5, attempt5Schema } from './attempt5.js';
import { Extra10, extra10Schema } from './extra10.js';

export interface TransactionData7 {
  paymentMethod: string;
  flow: string;
  extra: Extra10;
  country: string;
  attempts: Attempt5[];
  additionalProperties?: Record<string, unknown>;
}

export const transactionData7Schema: Schema<TransactionData7> = lazy(() =>
  typedExpandoObject(
    {
      paymentMethod: ['payment_method', string()],
      flow: ['flow', string()],
      extra: ['extra', extra10Schema],
      country: ['country', string()],
      attempts: ['attempts', array(attempt5Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
