/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Attempt1, attempt1Schema } from './attempt1.js';
import { Extra, extraSchema } from './extra.js';

export interface TransactionData2 {
  paymentMethod: string;
  flow: string;
  extra: Extra;
  country: string;
  attempts: Attempt1[];
  additionalProperties?: Record<string, unknown>;
}

export const transactionData2Schema: Schema<TransactionData2> = lazy(() =>
  typedExpandoObject(
    {
      paymentMethod: ['payment_method', string()],
      flow: ['flow', string()],
      extra: ['extra', extraSchema],
      country: ['country', string()],
      attempts: ['attempts', array(attempt1Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
