/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Attempt4, attempt4Schema } from './attempt4.js';
import { Extra8, extra8Schema } from './extra8.js';

export interface TransactionData6 {
  paymentMethod: string;
  flow: string;
  extra: Extra8;
  country: string;
  attempts: Attempt4[];
  additionalProperties?: Record<string, unknown>;
}

export const transactionData6Schema: Schema<TransactionData6> = lazy(() =>
  typedExpandoObject(
    {
      paymentMethod: ['payment_method', string()],
      flow: ['flow', string()],
      extra: ['extra', extra8Schema],
      country: ['country', string()],
      attempts: ['attempts', array(attempt4Schema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
