/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Transaction {
  transactionId: string;
  amount: number;
  currency: string;
  createdDate: number;
  additionalProperties?: Record<string, unknown>;
}

export const transactionSchema: Schema<Transaction> = typedExpandoObject(
  {
    transactionId: ['transactionId', string()],
    amount: ['amount', number()],
    currency: ['currency', string()],
    createdDate: ['createdDate', number()],
  },
  'additionalProperties',
  optional(unknown())
);
