/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { OptionalInput, optionalInputSchema } from './optionalInput.js';
import { Requiredinput, requiredinputSchema } from './requiredinput.js';

export interface TrustScoreDetailedRequest {
  requiredinput: Requiredinput;
  optionalInput: OptionalInput;
  additionalProperties?: Record<string, unknown>;
}

export const trustScoreDetailedRequestSchema: Schema<TrustScoreDetailedRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        requiredinput: ['requiredinput', requiredinputSchema],
        optionalInput: ['optionalInput', optionalInputSchema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
