/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TrustScoreExists1 {
  transactionAllowed: string;
  additionalProperties?: Record<string, unknown>;
}

export const trustScoreExists1Schema: Schema<TrustScoreExists1> = typedExpandoObject(
  { transactionAllowed: ['transactionAllowed', string()] },
  'additionalProperties',
  optional(unknown())
);
