/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TrustScoreExists {
  trustScore: number;
  deliverable: string;
  proxy: string;
  vpn: string;
  tor: string;
  activeVpn: string;
  activeTor: string;
  recentAbuse: string;
  botStatus: string;
  additionalProperties?: Record<string, unknown>;
}

export const trustScoreExistsSchema: Schema<TrustScoreExists> = typedExpandoObject(
  {
    trustScore: ['trustScore', number()],
    deliverable: ['deliverable', string()],
    proxy: ['proxy', string()],
    vpn: ['vpn', string()],
    tor: ['tor', string()],
    activeVpn: ['active_vpn', string()],
    activeTor: ['active_tor', string()],
    recentAbuse: ['recent_abuse', string()],
    botStatus: ['bot_status', string()],
  },
  'additionalProperties',
  optional(unknown())
);
