/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Data7, data7Schema } from './data7.js';

export interface UpdateMerchant {
  status: string;
  data: Data7;
  message: string;
  reqId: string;
  additionalProperties?: Record<string, unknown>;
}

export const updateMerchantSchema: Schema<UpdateMerchant> = lazy(() =>
  typedExpandoObject(
    {
      status: ['status', string()],
      data: ['data', data7Schema],
      message: ['message', string()],
      reqId: ['reqId', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
