/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface UpdateMerchantRequest {
  legalName: string;
  regNo: string;
  websiteUrl: string;
  iecNo: string;
  tradingStartDate: string;
  dateOfIncorporation: string;
  tradingAddress: string;
  tradingCountry: string;
  tradingState: string;
  tradingPostal: string;
  corporateAddress: string;
  corporateCountry: string;
  corporateState: string;
  corporatePostal: string;
  businessPhone: string;
  contactPhone: string;
  contactName: string;
  officerTitle: string;
  officerName: string;
  defaultCurrency: string;
  defaultTimezone: string;
  allowedPaymentMethods: string[];
  allowedCurrencies: string[];
  isLiveTransactionAllowed: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const updateMerchantRequestSchema: Schema<UpdateMerchantRequest> = typedExpandoObject(
  {
    legalName: ['legalName', string()],
    regNo: ['regNo', string()],
    websiteUrl: ['websiteUrl', string()],
    iecNo: ['iecNo', string()],
    tradingStartDate: ['tradingStartDate', string()],
    dateOfIncorporation: ['dateOfIncorporation', string()],
    tradingAddress: ['tradingAddress', string()],
    tradingCountry: ['tradingCountry', string()],
    tradingState: ['tradingState', string()],
    tradingPostal: ['tradingPostal', string()],
    corporateAddress: ['corporateAddress', string()],
    corporateCountry: ['corporateCountry', string()],
    corporateState: ['corporateState', string()],
    corporatePostal: ['corporatePostal', string()],
    businessPhone: ['businessPhone', string()],
    contactPhone: ['contactPhone', string()],
    contactName: ['contactName', string()],
    officerTitle: ['officerTitle', string()],
    officerName: ['officerName', string()],
    defaultCurrency: ['defaultCurrency', string()],
    defaultTimezone: ['defaultTimezone', string()],
    allowedPaymentMethods: ['allowedPaymentMethods', array(string())],
    allowedCurrencies: ['allowedCurrencies', array(string())],
    isLiveTransactionAllowed: ['isLiveTransactionAllowed', boolean()],
  },
  'additionalProperties',
  optional(unknown())
);
