/**
 * Paysecure API Documentation - LiveLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface WhitelistUploadSuccess {
  totalRecords: number;
  totalApproved: number;
  status: string;
  additionalProperties?: Record<string, unknown>;
}

export const whitelistUploadSuccessSchema: Schema<WhitelistUploadSuccess> = typedExpandoObject(
  {
    totalRecords: ['totalRecords', number()],
    totalApproved: ['totalApproved', number()],
    status: ['status', string()],
  },
  'additionalProperties',
  optional(unknown())
);
